"""Periodic table symbol/name lookup for Help-text parsing."""

PERIODIC_SYMBOL_BY_TOKEN = {
    'h': 'H',
    'hydrogen': 'H',
    'he': 'He',
    'helium': 'He',
    'li': 'Li',
    'lithium': 'Li',
    'be': 'Be',
    'beryllium': 'Be',
    'b': 'B',
    'boron': 'B',
    'c': 'C',
    'carbon': 'C',
    'n': 'N',
    'nitrogen': 'N',
    'o': 'O',
    'oxygen': 'O',
    'f': 'F',
    'fluorine': 'F',
    'ne': 'Ne',
    'neon': 'Ne',
    'na': 'Na',
    'sodium': 'Na',
    'mg': 'Mg',
    'magnesium': 'Mg',
    'al': 'Al',
    'aluminum': 'Al',
    'si': 'Si',
    'silicon': 'Si',
    'p': 'P',
    'phosphorus': 'P',
    's': 'S',
    'sulfur': 'S',
    'cl': 'Cl',
    'chlorine': 'Cl',
    'ar': 'Ar',
    'argon': 'Ar',
    'k': 'K',
    'potassium': 'K',
    'ca': 'Ca',
    'calcium': 'Ca',
    'sc': 'Sc',
    'scandium': 'Sc',
    'ti': 'Ti',
    'titanium': 'Ti',
    'v': 'V',
    'vanadium': 'V',
    'cr': 'Cr',
    'chromium': 'Cr',
    'mn': 'Mn',
    'manganese': 'Mn',
    'fe': 'Fe',
    'iron': 'Fe',
    'co': 'Co',
    'cobalt': 'Co',
    'ni': 'Ni',
    'nickel': 'Ni',
    'cu': 'Cu',
    'copper': 'Cu',
    'zn': 'Zn',
    'zinc': 'Zn',
    'ga': 'Ga',
    'gallium': 'Ga',
    'ge': 'Ge',
    'germanium': 'Ge',
    'as': 'As',
    'arsenic': 'As',
    'se': 'Se',
    'selenium': 'Se',
    'br': 'Br',
    'bromine': 'Br',
    'kr': 'Kr',
    'krypton': 'Kr',
    'rb': 'Rb',
    'rubidium': 'Rb',
    'sr': 'Sr',
    'strontium': 'Sr',
    'y': 'Y',
    'yttrium': 'Y',
    'zr': 'Zr',
    'zirconium': 'Zr',
    'nb': 'Nb',
    'niobium': 'Nb',
    'mo': 'Mo',
    'molybdenum': 'Mo',
    'tc': 'Tc',
    'technetium': 'Tc',
    'ru': 'Ru',
    'ruthenium': 'Ru',
    'rh': 'Rh',
    'rhodium': 'Rh',
    'pd': 'Pd',
    'palladium': 'Pd',
    'ag': 'Ag',
    'silver': 'Ag',
    'cd': 'Cd',
    'cadmium': 'Cd',
    'in': 'In',
    'indium': 'In',
    'sn': 'Sn',
    'tin': 'Sn',
    'sb': 'Sb',
    'antimony': 'Sb',
    'te': 'Te',
    'tellurium': 'Te',
    'i': 'I',
    'iodine': 'I',
    'xe': 'Xe',
    'xenon': 'Xe',
    'cs': 'Cs',
    'cesium': 'Cs',
    'ba': 'Ba',
    'barium': 'Ba',
    'la': 'La',
    'lanthanum': 'La',
    'ce': 'Ce',
    'cerium': 'Ce',
    'pr': 'Pr',
    'praseodymium': 'Pr',
    'nd': 'Nd',
    'neodymium': 'Nd',
    'pm': 'Pm',
    'promethium': 'Pm',
    'sm': 'Sm',
    'samarium': 'Sm',
    'eu': 'Eu',
    'europium': 'Eu',
    'gd': 'Gd',
    'gadolinium': 'Gd',
    'tb': 'Tb',
    'terbium': 'Tb',
    'dy': 'Dy',
    'dysprosium': 'Dy',
    'ho': 'Ho',
    'holmium': 'Ho',
    'er': 'Er',
    'erbium': 'Er',
    'tm': 'Tm',
    'thulium': 'Tm',
    'yb': 'Yb',
    'ytterbium': 'Yb',
    'lu': 'Lu',
    'lutetium': 'Lu',
    'hf': 'Hf',
    'hafnium': 'Hf',
    'ta': 'Ta',
    'tantalum': 'Ta',
    'w': 'W',
    'tungsten': 'W',
    're': 'Re',
    'rhenium': 'Re',
    'os': 'Os',
    'osmium': 'Os',
    'ir': 'Ir',
    'iridium': 'Ir',
    'pt': 'Pt',
    'platinum': 'Pt',
    'au': 'Au',
    'gold': 'Au',
    'hg': 'Hg',
    'mercury': 'Hg',
    'tl': 'Tl',
    'thallium': 'Tl',
    'pb': 'Pb',
    'lead': 'Pb',
    'bi': 'Bi',
    'bismuth': 'Bi',
    'po': 'Po',
    'polonium': 'Po',
    'at': 'At',
    'astatine': 'At',
    'rn': 'Rn',
    'radon': 'Rn',
    'fr': 'Fr',
    'francium': 'Fr',
    'ra': 'Ra',
    'radium': 'Ra',
    'ac': 'Ac',
    'actinium': 'Ac',
    'th': 'Th',
    'thorium': 'Th',
    'pa': 'Pa',
    'protactinium': 'Pa',
    'u': 'U',
    'uranium': 'U',
    'np': 'Np',
    'neptunium': 'Np',
    'pu': 'Pu',
    'plutonium': 'Pu',
    'am': 'Am',
    'americium': 'Am',
    'cm': 'Cm',
    'curium': 'Cm',
    'bk': 'Bk',
    'berkelium': 'Bk',
    'cf': 'Cf',
    'californium': 'Cf',
    'es': 'Es',
    'einsteinium': 'Es',
    'fm': 'Fm',
    'fermium': 'Fm',
    'md': 'Md',
    'mendelevium': 'Md',
    'no': 'No',
    'nobelium': 'No',
    'lr': 'Lr',
    'lawrencium': 'Lr',
    'rf': 'Rf',
    'rutherfordium': 'Rf',
    'db': 'Db',
    'dubnium': 'Db',
    'sg': 'Sg',
    'seaborgium': 'Sg',
    'bh': 'Bh',
    'bohrium': 'Bh',
    'hs': 'Hs',
    'hassium': 'Hs',
    'mt': 'Mt',
    'meitnerium': 'Mt',
    'ds': 'Ds',
    'darmstadtium': 'Ds',
    'rg': 'Rg',
    'roentgenium': 'Rg',
    'cn': 'Cn',
    'copernicium': 'Cn',
    'nh': 'Nh',
    'nihonium': 'Nh',
    'fl': 'Fl',
    'flerovium': 'Fl',
    'mc': 'Mc',
    'moscovium': 'Mc',
    'lv': 'Lv',
    'livermorium': 'Lv',
    'ts': 'Ts',
    'tennessine': 'Ts',
    'og': 'Og',
    'oganesson': 'Og',
}


def parse_periodic_help_text(help_text):
    """
    Parse PERIODIC_TABLE Help text.
    Returns (disabled_symbols, preselected_symbols).
    Lines starting with '/' (e.g. /C) are locked preselected; other lines are disabled.
    """
    disabled = set()
    preselected = set()
    if not help_text or not isinstance(help_text, str):
        return disabled, preselected

    for raw_line in help_text.splitlines():
        line = (raw_line or "").strip()
        if not line:
            continue
        is_pre = line.startswith("/")
        token_src = line[1:].strip() if is_pre else line
        token_src = token_src.replace(",", " ").replace(";", " ").strip()
        if not token_src:
            continue
        first = token_src.split()[0].strip()
        sym = PERIODIC_SYMBOL_BY_TOKEN.get(first.lower()) or PERIODIC_SYMBOL_BY_TOKEN.get(
            token_src.lower()
        )
        if not sym:
            continue
        if is_pre:
            preselected.add(sym)
        else:
            disabled.add(sym)

    for sym in preselected:
        disabled.discard(sym)
    return disabled, preselected

