# Generated by Django 5.2.9 on 2026-07-23 17:46

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("equipment", "0172_equipment_slot_tolerance_minutes"),
        ("users", "0095_initial_payment_models"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razorpay_order_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('receipt', models.CharField(db_index=True, max_length=64)),
                ('purpose', models.CharField(choices=[('BOOKING_SHORTFALL', 'Booking balance payment'), ('WALLET_RECHARGE', 'Wallet recharge')], max_length=32)),
                ('base_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('convenience_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('fee_gst', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='INR', max_length=8)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('PAID', 'Paid'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], db_index=True, default='CREATED', max_length=16)),
                ('idempotency_key', models.CharField(db_index=True, max_length=128, unique=True)),
                ('fee_percent_snapshot', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=8)),
                ('fee_gst_percent_snapshot', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=8)),
                ('raw_create_response', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='razorpay_payment_orders', to='equipment.booking')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='razorpay_payment_orders', to='users.department')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='razorpay_payment_orders', to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='razorpay_payment_orders', to='users.wallet')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razorpay_payment_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('razorpay_signature', models.CharField(blank=True, max_length=255)),
                ('method', models.CharField(blank=True, max_length=64)),
                ('gateway_reference', models.CharField(blank=True, help_text='Bank / RRN / gateway reference when available', max_length=128)),
                ('customer_txn_ref', models.CharField(blank=True, max_length=128)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('CAPTURED', 'Captured'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded'), ('PARTIALLY_REFUNDED', 'Partially refunded')], db_index=True, default='CAPTURED', max_length=24)),
                ('verified_via', models.CharField(choices=[('CHECKOUT', 'Checkout verify'), ('WEBHOOK', 'Webhook')], default='CHECKOUT', max_length=16)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='payments.paymentorder')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentRefund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razorpay_refund_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSED', 'Processed'), ('FAILED', 'Failed')], default='PENDING', max_length=16)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='razorpay_refunds_initiated', to=settings.AUTH_USER_MODEL)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='payments.payment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settlement_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('bank_utr', models.CharField(blank=True, db_index=True, max_length=128)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('settled_on', models.DateField(blank=True, null=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payments', models.ManyToManyField(blank=True, related_name='settlements', to='payments.payment')),
            ],
            options={
                'ordering': ['-settled_on', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='paymentorder',
            index=models.Index(fields=['purpose', 'status'], name='payments_pa_purpose_45566a_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentorder',
            index=models.Index(fields=['booking', 'status'], name='payments_pa_booking_2bc994_idx'),
        ),
    ]
