# Generated by Django for CMS app

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HomePageContent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("key", models.CharField(db_index=True, max_length=100, unique=True, verbose_name="Key")),
                ("value", models.TextField(blank=True, verbose_name="Value")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["key"],
                "verbose_name": "Home page content",
                "verbose_name_plural": "Home page content",
            },
        ),
        migrations.CreateModel(
            name="MenuItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("label", models.CharField(max_length=100, verbose_name="Label")),
                (
                    "link_type",
                    models.CharField(
                        choices=[
                            ("internal_anchor", "Internal anchor (#section)"),
                            ("internal_route", "Internal route (/path)"),
                            ("external_url", "External URL"),
                            ("trigger", "Trigger (e.g. Contact / Ticket form)"),
                        ],
                        default="internal_anchor",
                        max_length=20,
                        verbose_name="Link type",
                    ),
                ),
                (
                    "url",
                    models.CharField(
                        blank=True,
                        help_text="Anchor (#section), path (/equipments), or full URL. Leave blank for trigger.",
                        max_length=500,
                        verbose_name="URL or anchor",
                    ),
                ),
                ("priority", models.PositiveIntegerField(default=0, help_text="Lower number = higher position in menu.", verbose_name="Priority")),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                ("open_in_new_tab", models.BooleanField(default=False, verbose_name="Open in new tab")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Set for submenu items.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="cms.menuitem",
                    ),
                ),
            ],
            options={
                "ordering": ["priority", "id"],
                "verbose_name": "Menu item",
                "verbose_name_plural": "Menu items",
            },
        ),
    ]
