# Generated by Django 5.2.9 on 2026-03-08 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_homepagecontent_font_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='page',
            field=models.ForeignKey(blank=True, help_text="CMS page to link to. Used when Link type is 'CMS page'.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu_items', to='cms.cmspage'),
        ),
    ]
