"""Models package for users app."""

from ..managers import UserManager
from .department import Department, DepartmentType
from .organization_request import OrganizationRequest
from .user import User, UserType, Gender
from .wallet import (
    Wallet,
    SubWallet,
    SubWalletTransaction,
    WalletRazorpayOrder,
    WalletJoinRequest,
    WalletJoinRequestStatus,
    WalletRechargeRequest,
    WalletRechargeRequestStatus,
    WalletRechargeRejectionReason,
    WalletRechargeCancellationSource,
    WalletRechargeCreditFacilityStatus,
    WalletRechargeMode,
    WalletRechargeRequestAuditLog,
    WalletRechargeImportRecord,
    WalletRechargeParseEntry,
    ExternalUserBankDetails,
    WalletWithdrawalRequest,
    WalletWithdrawalRequestStatus,
    WalletPeerTransfer,
    WalletPeerTransferStatus,
)
from .wallet_credit_facility_settings import WalletCreditFacilitySettings
from .wallet_credit_facility import (
    WalletCreditPolicy,
    WalletCreditFacility,
    WalletCreditFacilityStatus,
    WalletCreditLedgerEntry,
    WalletCreditLedgerKind,
    WalletCreditInvoice,
    WalletCreditInvoiceStatus,
    WalletCreditPayment,
    WalletCreditAuditEvent,
)
from .channel_i_identity import (
    ChannelIIdentityProfile,
    ChannelIIdentityHistory,
    StudentDegreeClassification,
    ChannelIDepartmentMapping,
    HeadOfDepartmentAssignment,
    UserAffiliation,
    StudentValidityExtension,
    StudentLifecycleEvent,
    PortalUserClassification,
    DegreeClassificationKind,
    StudentValiditySource,
    AffiliationKind,
)
from .supervisor_invite import SupervisorInvite, SupervisorInviteEvent, SupervisorInviteStatus
from .registration_approval import (
    RegistrationApproval,
    RegistrationApprovalChannel,
    RegistrationApprovalEvent,
    RegistrationApprovalPolicy,
    RegistrationApprovalStatus,
    RegistrationApprovalToken,
    RegistrationExtensionRequest,
    RegistrationExtensionStatus,
)
from .wallet_student_recharge_settings import WalletStudentRechargeSettings
from .department_faculty_credit_facility import (
    DepartmentFacultyCreditFacilitySettings,
    FacultyDepartmentCreditFacility,
    FacultyDepartmentCreditFacilityStatus,
    FacultyDepartmentCreditFacilityAuditEvent,
    FacultyDepartmentCreditFacilityAuditLog,
)
from .user_document import UserDocument
from .user_group import UserGroup, UserGroupMember
from .project import Project
from .auth_lock import UserLoginLock
from .mobile_device_session import MobileDeviceSession
from .auth_settings import AuthSettings
from .wallet_sric_settings import WalletCashbookMailboxMessage, WalletSricSettings
from .wallet_payment_modes import (
    DepartmentModeState,
    WalletDirectRecharge,
    WalletDirectRechargeGrant,
    WalletDirectRechargeMode,
    WalletModeDepartmentSetting,
    WalletModeEmailRecipients,
    WalletModeOption,
    WalletPaymentModeAuditEvent,
    WalletPaymentModeConfig,
)
from .wallet_admin_adjustment import (
    WalletAdminAdjustment,
    WalletAdminAdjustmentDirection,
    WalletAdminAdjustmentReason,
)
from .test_account_email_settings import TestAccountEmailSettings
from .user_type_inactivity import UserTypeInactivityTimeout
from .billing import ExternalBillingProfile
from .payment import (
    DepartmentPaymentReceipt,
    PaymentGatewayTransaction,
    SricTransferRequest,
)
from .equipment_supply_chain_role import (
    EquipmentSupplyChainRole,
    UserEquipmentSupplyChainRole,
)
from .rbac import PermissionDefinition, DeptAdminPermissionGrant, StaffPermissionGrant
from .admin_panel_access import AdminPanelRoleConfig
from .sync_agent import SyncAgent
from .portal_migration import (
    PortalMigrationPhase,
    PortalMigrationState,
    LegacyWalletMappingStatus,
    LegacyLedgerDirection,
    LegacyWalletAccountMapping,
    LegacyWalletLedgerEntry,
    LegacyWalletSyncDeadLetter,
    PortalMigrationPhaseTransition,
    FacultyWalletSyncCutoffChange,
    LegacyBookingHistoryRecord,
    MigrationSettlementType,
    MigrationSettlementStatus,
    MigrationBookingSettlement,
    LegacyEquipmentMappingStatus,
    LegacyEquipmentMapping,
    LegacyEquipmentCapacitySplitStatus,
    LegacyEquipmentCapacitySplitPolicy,
    LegacyEquipmentCapacitySplit,
    LegacyBookingMigrationBatchStatus,
    LegacyBookingMigrationBatch,
    LegacyBookingBlockStatus,
    LegacyBookingBlock,
    MigrationNotificationTemplate,
    MigrationNotificationStatus,
    MigrationNotificationBatch,
    MigrationNotificationRecipient,
    MigrationT0Event,
)

__all__ = [
    "UserManager",
    "SupervisorInvite",
    "SupervisorInviteEvent",
    "SupervisorInviteStatus",
    "RegistrationApproval",
    "RegistrationApprovalChannel",
    "RegistrationApprovalEvent",
    "RegistrationApprovalPolicy",
    "RegistrationApprovalStatus",
    "RegistrationApprovalToken",
    "RegistrationExtensionRequest",
    "RegistrationExtensionStatus",
    "Department",
    "DepartmentType",
    "OrganizationRequest",
    "User",
    "UserType",
    "Gender",
    "Wallet",
    "SubWallet",
    "SubWalletTransaction",
    "WalletRazorpayOrder",
    "WalletAdminAdjustment",
    "WalletAdminAdjustmentDirection",
    "WalletAdminAdjustmentReason",
    "WalletJoinRequest",
    "WalletJoinRequestStatus",
    "WalletRechargeRequest",
    "WalletRechargeRequestStatus",
    "WalletRechargeRejectionReason",
    "WalletRechargeCancellationSource",
    "WalletRechargeCreditFacilityStatus",
    "WalletRechargeMode",
    "WalletRechargeRequestAuditLog",
    "WalletCreditFacilitySettings",
    "WalletCreditPolicy",
    "WalletCreditFacility",
    "WalletCreditFacilityStatus",
    "WalletCreditLedgerEntry",
    "WalletCreditLedgerKind",
    "WalletCreditInvoice",
    "WalletCreditInvoiceStatus",
    "WalletCreditPayment",
    "WalletCreditAuditEvent",
    "WalletStudentRechargeSettings",
    "DepartmentFacultyCreditFacilitySettings",
    "FacultyDepartmentCreditFacility",
    "FacultyDepartmentCreditFacilityStatus",
    "FacultyDepartmentCreditFacilityAuditEvent",
    "FacultyDepartmentCreditFacilityAuditLog",
    "WalletRechargeImportRecord",
    "WalletRechargeParseEntry",
    "ExternalUserBankDetails",
    "WalletWithdrawalRequest",
    "WalletWithdrawalRequestStatus",
    "WalletPeerTransfer",
    "WalletPeerTransferStatus",
    "UserDocument",
    "UserGroup",
    "UserGroupMember",
    "Project",
    "UserLoginLock",
    "MobileDeviceSession",
    "AuthSettings",
    "WalletSricSettings",
    "WalletCashbookMailboxMessage",
    "TestAccountEmailSettings",
    "UserTypeInactivityTimeout",
    "ExternalBillingProfile",
    "PaymentGatewayTransaction",
    "DepartmentPaymentReceipt",
    "SricTransferRequest",
    "EquipmentSupplyChainRole",
    "UserEquipmentSupplyChainRole",
    "PermissionDefinition",
    "DeptAdminPermissionGrant",
    "StaffPermissionGrant",
    "AdminPanelRoleConfig",
    "SyncAgent",
    "PortalMigrationPhase",
    "PortalMigrationState",
    "LegacyWalletMappingStatus",
    "LegacyLedgerDirection",
    "LegacyWalletAccountMapping",
    "LegacyWalletLedgerEntry",
    "LegacyWalletSyncDeadLetter",
    "PortalMigrationPhaseTransition",
    "FacultyWalletSyncCutoffChange",
    "LegacyBookingHistoryRecord",
    "MigrationSettlementType",
    "MigrationSettlementStatus",
    "MigrationBookingSettlement",
    "LegacyEquipmentMappingStatus",
    "LegacyEquipmentMapping",
    "LegacyEquipmentCapacitySplitStatus",
    "LegacyEquipmentCapacitySplitPolicy",
    "LegacyEquipmentCapacitySplit",
    "LegacyBookingMigrationBatchStatus",
    "LegacyBookingMigrationBatch",
    "LegacyBookingBlockStatus",
    "LegacyBookingBlock",
    "MigrationNotificationTemplate",
    "MigrationNotificationStatus",
    "MigrationNotificationBatch",
    "MigrationNotificationRecipient",
    "MigrationT0Event",
    "ChannelIIdentityProfile",
    "ChannelIIdentityHistory",
    "StudentDegreeClassification",
    "ChannelIDepartmentMapping",
    "HeadOfDepartmentAssignment",
    "UserAffiliation",
    "StudentValidityExtension",
    "StudentLifecycleEvent",
    "PortalUserClassification",
    "DegreeClassificationKind",
    "StudentValiditySource",
    "AffiliationKind",
]

