# Generated by Django 5.2.9 on 2026-08-06 13:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("equipment", "0184_equipment_analysis_checkin_policy"),
        ("users", "0095_initial_payment_models"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProvisionedDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_type', models.CharField(choices=[('dsa', 'Department Sync Agent'), ('equipment_pc', 'Equipment PC'), ('remote_analysis', 'Remote Analysis Workstation'), ('gpu_workstation', 'GPU Workstation'), ('ai_assistant', 'AI Assistant'), ('iot_gateway', 'IoT Gateway'), ('other', 'Other')], db_index=True, max_length=32)),
                ('lifecycle', models.CharField(choices=[('unknown', 'Unknown Device'), ('pending_approval', 'Pending Approval'), ('provisioning', 'Provisioning'), ('active', 'Active'), ('suspended', 'Suspended'), ('revoked', 'Revoked'), ('retired', 'Retired')], db_index=True, default='pending_approval', max_length=32)),
                ('display_name', models.CharField(blank=True, default='', max_length=255)),
                ('hostname', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('machine_guid', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('fingerprint', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('application_version', models.CharField(blank=True, default='', max_length=64)),
                ('windows_version', models.CharField(blank=True, default='', max_length=128)),
                ('inventory_snapshot', models.JSONField(blank=True, default=dict)),
                ('access_token_hash', models.CharField(blank=True, default='', max_length=128)),
                ('access_token_prefix', models.CharField(blank=True, default='', max_length=16)),
                ('access_token_issued_at', models.DateTimeField(blank=True, null=True)),
                ('access_token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('bootstrap_public_key', models.TextField(blank=True, default='')),
                ('legacy_dsa_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('legacy_workstation_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provisioned_at', models.DateTimeField(blank=True, null=True)),
                ('retired_at', models.DateTimeField(blank=True, null=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provisioned_devices', to='users.department')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='DevicePolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_type', models.CharField(blank=True, choices=[('dsa', 'Department Sync Agent'), ('equipment_pc', 'Equipment PC'), ('remote_analysis', 'Remote Analysis Workstation'), ('gpu_workstation', 'GPU Workstation'), ('ai_assistant', 'AI Assistant'), ('iot_gateway', 'IoT Gateway'), ('other', 'Other')], default='', max_length=32)),
                ('name', models.CharField(max_length=128)),
                ('version', models.PositiveIntegerField(default=1)),
                ('document', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='device_provisioning.provisioneddevice')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='DeviceInventory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_records', to='device_provisioning.provisioneddevice')),
            ],
            options={
                'ordering': ['-reported_at'],
            },
        ),
        migrations.CreateModel(
            name='DeviceHeartbeat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(blank=True, default='ok', max_length=32)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('client_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heartbeats', to='device_provisioning.provisioneddevice')),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='DeviceCertificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('issued', 'Issued'), ('revoked', 'Revoked'), ('expired', 'Expired')], default='pending', max_length=16)),
                ('fingerprint_sha256', models.CharField(blank=True, default='', max_length=64)),
                ('subject', models.CharField(blank=True, default='', max_length=255)),
                ('not_before', models.DateTimeField(blank=True, null=True)),
                ('not_after', models.DateTimeField(blank=True, null=True)),
                ('pem_public', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='device_provisioning.provisioneddevice')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workstation_role', models.CharField(blank=True, default='', max_length=64)),
                ('notes', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_assignments', to='users.department')),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_assignments', to='equipment.equipment')),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assignment', to='device_provisioning.provisioneddevice')),
            ],
        ),
        migrations.CreateModel(
            name='ProvisioningSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_type', models.CharField(choices=[('dsa', 'Department Sync Agent'), ('equipment_pc', 'Equipment PC'), ('remote_analysis', 'Remote Analysis Workstation'), ('gpu_workstation', 'GPU Workstation'), ('ai_assistant', 'AI Assistant'), ('iot_gateway', 'IoT Gateway'), ('other', 'Other')], db_index=True, max_length=32)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('claimed', 'Claimed'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=24)),
                ('session_proof_hash', models.CharField(blank=True, default='', max_length=128)),
                ('session_proof_prefix', models.CharField(blank=True, default='', max_length=16)),
                ('hostname', models.CharField(blank=True, default='', max_length=255)),
                ('machine_guid', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('fingerprint', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('windows_version', models.CharField(blank=True, default='', max_length=128)),
                ('application_version', models.CharField(blank=True, default='', max_length=64)),
                ('cpu', models.CharField(blank=True, default='', max_length=255)),
                ('ram_gb', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('mac_addresses', models.JSONField(blank=True, default=list)),
                ('local_ips', models.JSONField(blank=True, default=list)),
                ('bootstrap_public_key', models.TextField(blank=True, default='')),
                ('inventory', models.JSONField(blank=True, default=dict)),
                ('display_name', models.CharField(blank=True, default='', max_length=255)),
                ('requested_equipment_id', models.PositiveIntegerField(blank=True, null=True)),
                ('requested_workstation_role', models.CharField(blank=True, default='', max_length=64)),
                ('client_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=512)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.CharField(blank=True, default='', max_length=500)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_provisioning_sessions', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provisioning_sessions', to='users.department')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='device_provisioning.provisioneddevice')),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_provisioning_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeviceBootstrapToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_hash', models.CharField(max_length=128)),
                ('token_prefix', models.CharField(blank=True, default='', max_length=16)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bootstrap_tokens', to='device_provisioning.provisioneddevice')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bootstrap_tokens', to='device_provisioning.provisioningsession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeviceAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('created', 'Created'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('provisioned', 'Provisioned'), ('reprovisioned', 'Reprovisioned'), ('suspended', 'Suspended'), ('revoked', 'Revoked'), ('retired', 'Retired'), ('renamed', 'Renamed'), ('assigned', 'Assigned'), ('heartbeat', 'Heartbeat'), ('policy_updated', 'Policy Updated')], db_index=True, max_length=32)),
                ('message', models.CharField(blank=True, default='', max_length=500)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('client_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_provisioning_audit_logs', to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='device_provisioning.provisioneddevice')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='device_provisioning.provisioningsession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='provisioneddevice',
            index=models.Index(fields=['device_type', 'lifecycle'], name='device_prov_device__3e29ec_idx'),
        ),
        migrations.AddIndex(
            model_name='provisioneddevice',
            index=models.Index(fields=['hostname', 'device_type'], name='device_prov_hostnam_3ef112_idx'),
        ),
        migrations.AddIndex(
            model_name='devicepolicy',
            index=models.Index(fields=['device_type', 'is_active'], name='device_prov_device__1ea21b_idx'),
        ),
        migrations.AddConstraint(
            model_name='deviceassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('equipment__isnull', False)), fields=('equipment',), name='uniq_device_assignment_equipment'),
        ),
        migrations.AddIndex(
            model_name='provisioningsession',
            index=models.Index(fields=['status', 'device_type'], name='device_prov_status_ed5ab7_idx'),
        ),
        migrations.AddIndex(
            model_name='provisioningsession',
            index=models.Index(fields=['status', 'created_at'], name='device_prov_status_a601e3_idx'),
        ),
        migrations.AddIndex(
            model_name='deviceauditlog',
            index=models.Index(fields=['action', 'created_at'], name='device_prov_action_87133e_idx'),
        ),
    ]
