from django.urls import path

from . import views, views_ops

app_name = "training"

urlpatterns = [
    path("bootstrap/", views.bootstrap, name="bootstrap"),
    path("equipment/", views.equipment_list, name="equipment-list"),
    path("equipment/<int:equipment_id>/", views.equipment_detail, name="equipment-detail"),
    path("equipment/<int:equipment_id>/free-windows/", views.free_windows, name="free-windows"),
    path("equipment/<int:equipment_id>/demo-quote/", views.demo_quote, name="demo-quote"),
    path("demo-requests/", views.demo_requests, name="demo-requests"),
    path("demo-requests/<int:pk>/", views.demo_request_detail, name="demo-request-detail"),
    path(
        "demo-requests/<int:pk>/<str:action>/",
        views.demo_request_action,
        name="demo-request-action",
    ),
    path("calls/", views.calls, name="calls"),
    path("calls/<int:pk>/", views.call_detail, name="call-detail"),
    path("calls/<int:pk>/close/", views.call_close, name="call-close"),
    path("calls/<int:pk>/nominations/", views.call_nominations, name="call-nominations"),
    path("calls/<int:pk>/shortlist/", views.call_shortlist, name="call-shortlist"),
    path("calls/<int:pk>/results/", views.call_results, name="call-results"),
    path("nominations/", views.nominations, name="nominations"),
    path("nominations/<int:pk>/<str:action>/", views.nomination_action, name="nomination-action"),
    path("shortlist-runs/<int:pk>/publish/", views.run_publish, name="run-publish"),
    path("shortlist-runs/<int:pk>/export/", views.run_export, name="run-export"),
    path("shortlist-runs/<int:pk>/verify/", views.run_verify, name="run-verify"),
    path("shortlist-entries/<int:pk>/override/", views.entry_override, name="entry-override"),
    path("shortlist-entries/<int:pk>/appeal/", views.entry_appeal, name="entry-appeal"),
    path("appeals/", views.appeals, name="appeals"),
    path("appeals/<int:pk>/decide/", views.appeal_decide, name="appeal-decide"),
    path("events/", views.events, name="events"),
    path("events/<int:pk>/", views.event_detail, name="event-detail"),
    path("events/<int:pk>/cancel/", views.event_cancel, name="event-cancel"),
    path("events/<int:pk>/sessions/", views.event_sessions, name="event-sessions"),
    path("sessions/<int:pk>/", views.session_detail, name="session-detail"),
    path("sessions/<int:pk>/reserve/", views.session_reserve, name="session-reserve"),
    path("sessions/<int:pk>/release/", views.session_release, name="session-release"),
    path("sessions/<int:pk>/attendance/", views.session_attendance, name="session-attendance"),
    path("attendance/sessions/", views.attendance_sessions, name="attendance-sessions"),
    path("certifications/", views.certifications, name="certifications"),
    path("badges/", views.badges, name="badges"),
    path("me/trainings/", views.my_trainings, name="my-trainings"),
    path("faculty/students-trainings/", views.faculty_students_trainings, name="faculty-students-trainings"),
    path("workspace/summary/", views.workspace_summary, name="workspace-summary"),
    path("policy/", views.policy, name="policy"),
    path("policy/history/", views.policy_history, name="policy-history"),
    path("admin/module/", views.module_settings, name="module-settings"),
    path("admin/equipment/", views.module_equipment, name="module-equipment"),
    path("admin/equipment/<int:equipment_id>/", views.module_equipment_toggle, name="module-equipment-toggle"),
    # Competency assessment and certificates
    path("levels/", views_ops.levels, name="levels"),
    path("equipment/<int:equipment_id>/checklist/", views_ops.checklist, name="checklist"),
    path("assessments/", views_ops.assessments, name="assessments"),
    path("assessments/<int:pk>/sign-off/", views_ops.assessment_sign_off, name="assessment-sign-off"),
    path("assessment-candidates/", views_ops.assessment_candidates, name="assessment-candidates"),
    path("certifications/<int:pk>/", views_ops.certification_detail, name="certification-detail"),
    path("certifications/<int:pk>/certificate.pdf", views_ops.certificate_pdf, name="certificate-pdf"),
    path("certifications/<int:pk>/<str:action>/", views_ops.certification_action, name="certification-action"),
    path("verify/<str:token>/", views_ops.verify_certificate, name="verify-certificate"),
    # Operator roster and duty
    path("roster/", views_ops.roster_list, name="roster"),
    path("roster/people/", views_ops.roster_people, name="roster-people"),
    path("roster/<int:pk>/", views_ops.roster_detail, name="roster-detail"),
    path("roster/<int:pk>/<str:action>/", views_ops.roster_action, name="roster-action"),
    path("duty/plan/", views_ops.duty_plan, name="duty-plan"),
    path("duty/allocations/", views_ops.duty_allocations, name="duty-allocations"),
    path("duty/allocations/<int:pk>/", views_ops.duty_allocation_detail, name="duty-allocation-detail"),
    path("duty/allocations/<int:pk>/<str:action>/", views_ops.duty_allocation_action, name="duty-allocation-action"),
    path("duty/respond/", views_ops.duty_respond, name="duty-respond"),
    path("duty/shifts/<int:pk>/<str:action>/", views_ops.duty_shift_action, name="duty-shift-action"),
    path("duty/calendar/", views_ops.duty_calendar, name="duty-calendar"),
    path("duty/me/", views_ops.duty_me, name="duty-me"),
    path("duty/accounting/", views_ops.duty_accounting, name="duty-accounting"),
    path("duty/accounting/export/", views_ops.duty_accounting_export, name="duty-accounting-export"),
    path("duty/statement/", views_ops.duty_statement, name="duty-statement"),
    path("duty/live/", views_ops.duty_live, name="duty-live"),
    path("operator-policy/", views_ops.operator_policy_view, name="operator-policy"),
    path("operator-policy/history/", views_ops.operator_policy_history, name="operator-policy-history"),
]
