# Generated by Django 5.2.9 on 2026-10-05 03:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0130_procurement_user_types'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentModuleAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_label', models.CharField(blank=True, default='', max_length=255)),
                ('module_key', models.CharField(choices=[('dsa', 'Department Sync Agent'), ('remote_analysis', 'Remote Analysis'), ('training', 'Training & Certification'), ('procurement', 'Procurement & Assets')], max_length=32)),
                ('action', models.CharField(max_length=40)),
                ('old_value', models.JSONField(blank=True, default=dict)),
                ('new_value', models.JSONField(blank=True, default=dict)),
                ('reason', models.TextField(blank=True, default='')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='module_audit_logs', to='users.department')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['department', 'module_key', 'created_at'], name='department__departm_4d8769_idx'), models.Index(fields=['created_at'], name='department__created_bd8016_idx')],
            },
        ),
        migrations.CreateModel(
            name='DepartmentModulesInstallation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installed_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='DepartmentModuleSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_key', models.CharField(choices=[('dsa', 'Department Sync Agent'), ('remote_analysis', 'Remote Analysis'), ('training', 'Training & Certification')], max_length=32)),
                ('enabled', models.BooleanField(default=False)),
                ('test_users_only', models.BooleanField(default=False)),
                ('disabled_at', models.DateTimeField(blank=True, help_text='When the switch was last turned off. Work started before this (e.g. earlier bookings) may finish.', null=True)),
                ('test_only_since', models.DateTimeField(blank=True, help_text='When test-users-only was last turned on. Work started before this may finish.', null=True)),
                ('source', models.CharField(choices=[('seed', 'Initial state from existing data'), ('admin', 'Main Administrator'), ('new', 'New department (starts off)')], default='admin', max_length=10)),
                ('seed_note', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_settings', to='users.department')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['department_id', 'module_key'],
                'constraints': [models.UniqueConstraint(fields=('department', 'module_key'), name='department_module_setting_unique')],
            },
        ),
    ]
