# Generated by Django 5.2.9 on 2025-12-28 18:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Unique name/identifier for this template', max_length=255, unique=True, verbose_name='Template Name')),
                ('code', models.CharField(db_index=True, help_text='Unique code for programmatic access to this template', max_length=100, unique=True, verbose_name='Template Code')),
                ('communication_type', models.CharField(choices=[('email', 'Email'), ('push_notification', 'Push Notification'), ('sms', 'SMS')], db_index=True, help_text='Type of communication (email, push notification, or SMS)', max_length=50, verbose_name='Communication Type')),
                ('subject', models.CharField(blank=True, help_text='Email subject or push notification title (supports template variables)', max_length=255, verbose_name='Subject/Title')),
                ('body_text', models.TextField(help_text='Plain text body for email/SMS or message for push notification (supports template variables)', verbose_name='Plain Text Body')),
                ('body_html', models.TextField(blank=True, help_text='HTML body for email (supports template variables, not used for push/SMS)', verbose_name='HTML Body')),
                ('sms_body', models.TextField(blank=True, help_text='SMS message body (supports template variables, used only for SMS)', verbose_name='SMS Body')),
                ('push_data', models.JSONField(blank=True, default=dict, help_text='Additional data payload for push notifications', verbose_name='Push Notification Data')),
                ('description', models.TextField(blank=True, help_text='Description of when and how this template is used', verbose_name='Description')),
                ('variable_help', models.TextField(blank=True, help_text='Documentation of available template variables (e.g., {{ user_name }}, {{ verification_url }})', verbose_name='Variable Help')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this template is active and can be used', verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_communication_templates', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_communication_templates', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Communication Template',
                'verbose_name_plural': 'Communication Templates',
                'ordering': ['communication_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CommunicationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('communication_type', models.CharField(choices=[('email', 'Email'), ('push_notification', 'Push Notification'), ('sms', 'SMS')], db_index=True, help_text='Type of communication (email, push notification, or SMS)', max_length=50, verbose_name='Communication Type')),
                ('subject', models.CharField(blank=True, help_text='Email subject or push notification title', max_length=255, verbose_name='Subject/Title')),
                ('message', models.TextField(blank=True, help_text='Message content of the communication', verbose_name='Message')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read'), ('failed', 'Failed'), ('bounced', 'Bounced'), ('rejected', 'Rejected')], db_index=True, default='pending', help_text='Current status of the communication', max_length=50, verbose_name='Status')),
                ('sent_at', models.DateTimeField(blank=True, help_text='Timestamp when the communication was sent', null=True, verbose_name='Sent At')),
                ('delivered_at', models.DateTimeField(blank=True, help_text='Timestamp when the communication was delivered', null=True, verbose_name='Delivered At')),
                ('read_at', models.DateTimeField(blank=True, help_text='Timestamp when the communication was read (for push notifications)', null=True, verbose_name='Read At')),
                ('error_message', models.TextField(blank=True, help_text='Error message if the communication failed', verbose_name='Error Message')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata about the communication (e.g., provider response, tracking IDs)', verbose_name='Metadata')),
                ('provider_message_id', models.CharField(blank=True, db_index=True, help_text='Message ID from the communication provider (e.g., email service, push service)', max_length=255, verbose_name='Provider Message ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_communication_logs', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('recipient', models.ForeignKey(help_text='User who received or should receive this communication', on_delete=django.db.models.deletion.PROTECT, related_name='communication_logs', to=settings.AUTH_USER_MODEL, verbose_name='Recipient')),
                ('template', models.ForeignKey(blank=True, help_text='Template used for this communication', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communication_logs', to='communication.communicationtemplate', verbose_name='Template')),
            ],
            options={
                'verbose_name': 'Communication Log',
                'verbose_name_plural': 'Communication Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommunicationWebhookEventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webhook_event_type', models.CharField(choices=[('email_sent', 'Email Sent'), ('email_delivered', 'Email Delivered'), ('email_opened', 'Email Opened'), ('email_clicked', 'Email Clicked'), ('email_bounced', 'Email Bounced'), ('email_complained', 'Email Complained'), ('email_failed', 'Email Failed'), ('push_sent', 'Push Sent'), ('push_delivered', 'Push Delivered'), ('push_opened', 'Push Opened'), ('push_failed', 'Push Failed'), ('sms_sent', 'SMS Sent'), ('sms_delivered', 'SMS Delivered'), ('sms_failed', 'SMS Failed'), ('sms_received', 'SMS Received'), ('other', 'Other')], db_index=True, help_text='Type of webhook event received', max_length=50, verbose_name='Webhook Event Type')),
                ('provider_type', models.CharField(choices=[('mailgun', 'Mailgun'), ('sendgrid', 'SendGrid'), ('aws_ses', 'AWS SES'), ('firebase', 'Firebase Cloud Messaging'), ('apns', 'Apple Push Notification Service'), ('fcm', 'Firebase Cloud Messaging'), ('twilio', 'Twilio'), ('other', 'Other')], db_index=True, help_text='Communication provider that sent the webhook', max_length=50, verbose_name='Provider Type')),
                ('provider_message_id', models.CharField(blank=True, db_index=True, help_text='Message ID from the provider', max_length=255, verbose_name='Provider Message ID')),
                ('recipient_email', models.CharField(blank=True, help_text='Recipient email address (from webhook payload)', max_length=255, verbose_name='Recipient Email')),
                ('recipient_phone', models.CharField(blank=True, help_text='Recipient phone number (from webhook payload)', max_length=20, verbose_name='Recipient Phone')),
                ('webhook_payload', models.JSONField(default=dict, help_text='Full webhook payload received from the provider', verbose_name='Webhook Payload')),
                ('processed', models.BooleanField(default=False, help_text='Whether this webhook event has been processed', verbose_name='Processed')),
                ('processed_at', models.DateTimeField(blank=True, help_text='Timestamp when the webhook was processed', null=True, verbose_name='Processed At')),
                ('processing_error', models.TextField(blank=True, help_text='Error message if webhook processing failed', verbose_name='Processing Error')),
                ('event_timestamp', models.DateTimeField(blank=True, help_text='Timestamp of the event from the provider', null=True, verbose_name='Event Timestamp')),
                ('received_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the webhook was received', verbose_name='Received At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('communication_log', models.ForeignKey(blank=True, help_text='Related communication log entry (if matched)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_events', to='communication.communicationlog', verbose_name='Communication Log')),
                ('recipient_user', models.ForeignKey(blank=True, help_text='Matched user from recipient email/phone', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_events', to=settings.AUTH_USER_MODEL, verbose_name='Recipient User')),
            ],
            options={
                'verbose_name': 'Communication Webhook Event Log',
                'verbose_name_plural': 'Communication Webhook Event Logs',
                'ordering': ['-received_at'],
            },
        ),
        migrations.AddIndex(
            model_name='communicationtemplate',
            index=models.Index(fields=['communication_type', 'is_active'], name='communicati_communi_648035_idx'),
        ),
        migrations.AddConstraint(
            model_name='communicationtemplate',
            constraint=models.UniqueConstraint(fields=('code', 'communication_type'), name='unique_template_code_per_type'),
        ),
        migrations.AddIndex(
            model_name='communicationlog',
            index=models.Index(fields=['communication_type', 'status'], name='communicati_communi_da3981_idx'),
        ),
        migrations.AddIndex(
            model_name='communicationlog',
            index=models.Index(fields=['recipient', 'status'], name='communicati_recipie_f42130_idx'),
        ),
        migrations.AddIndex(
            model_name='communicationwebhookeventlog',
            index=models.Index(fields=['provider_type', 'webhook_event_type'], name='communicati_provide_78c8e2_idx'),
        ),
        migrations.AddIndex(
            model_name='communicationwebhookeventlog',
            index=models.Index(fields=['processed', 'received_at'], name='communicati_process_ecc226_idx'),
        ),
    ]
