# Generated by Django 5.2.9 on 2026-01-19 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0002_notice'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notice',
            new_name='communicati_is_acti_2447e0_idx',
            old_name='communicati_is_acti_123456_idx',
        ),
        migrations.RenameIndex(
            model_name='notice',
            new_name='communicati_notice__ef55c8_idx',
            old_name='communicati_notice__789012_idx',
        ),
    ]
