# Generated by Django 5.2.9 on 2026-03-17 14:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_recipient_email(apps, schema_editor):
    CommunicationLog = apps.get_model("communication", "CommunicationLog")
    # Backfill for existing rows so logs remain readable after user deletion.
    for log in CommunicationLog.objects.select_related("recipient").only("id", "recipient_id", "recipient_email"):
        if log.recipient_email:
            continue
        recipient = getattr(log, "recipient", None)
        if recipient and getattr(recipient, "email", None):
            CommunicationLog.objects.filter(id=log.id, recipient_email="").update(recipient_email=recipient.email)


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0024_update_registration_self_verification_email_expiry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='communicationlog',
            name='recipient_email',
            field=models.CharField(blank=True, db_index=True, help_text='Snapshot of recipient email (kept if user is deleted)', max_length=255, verbose_name='Recipient Email'),
        ),
        migrations.AlterField(
            model_name='communicationlog',
            name='recipient',
            field=models.ForeignKey(blank=True, help_text='User who received or should receive this communication', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communication_logs', to=settings.AUTH_USER_MODEL, verbose_name='Recipient'),
        ),
        migrations.RunPython(backfill_recipient_email, reverse_code=migrations.RunPython.noop),
        migrations.AddIndex(
            model_name='communicationlog',
            index=models.Index(fields=['recipient_email', 'status'], name='communicati_recipie_118b23_idx'),
        ),
    ]
