# Generated by Django 5.2.9 on 2026-01-20 13:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0014_holiday'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticket_id', models.AutoField(primary_key=True, serialize=False)),
                ('public_name', models.CharField(blank=True, help_text='Name of public user (if not authenticated)', max_length=255, null=True, verbose_name='Name')),
                ('public_email', models.EmailField(blank=True, help_text='Email of public user (if not authenticated)', max_length=254, null=True, verbose_name='Email')),
                ('public_phone', models.CharField(blank=True, help_text='Phone number of public user (if not authenticated)', max_length=20, null=True, verbose_name='Phone Number')),
                ('ticket_type', models.CharField(choices=[('query', 'Query'), ('request', 'Request'), ('complaint', 'Complaint'), ('equipment_issue', 'Equipment Issue'), ('booking_issue', 'Booking Issue'), ('other', 'Other')], db_index=True, default='query', help_text='Type of ticket', max_length=50, verbose_name='Ticket Type')),
                ('subject', models.CharField(help_text='Subject/title of the ticket', max_length=255, verbose_name='Subject')),
                ('description', models.TextField(help_text='Detailed description of the issue/query/request', verbose_name='Description')),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], db_index=True, default='open', help_text='Current status of the ticket', max_length=20, verbose_name='Status')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], db_index=True, default='medium', help_text='Priority level of the ticket', max_length=20, verbose_name='Priority')),
                ('resolution_notes', models.TextField(blank=True, help_text='Notes about how the ticket was resolved', null=True, verbose_name='Resolution Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('resolved_at', models.DateTimeField(blank=True, help_text='Timestamp when the ticket was resolved', null=True, verbose_name='Resolved at')),
                ('closed_at', models.DateTimeField(blank=True, help_text='Timestamp when the ticket was closed', null=True, verbose_name='Closed at')),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Staff member assigned to handle this ticket', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Assigned To')),
                ('related_booking', models.ForeignKey(blank=True, help_text='Booking related to this ticket (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='equipment.booking', verbose_name='Related Booking')),
                ('related_equipment', models.ForeignKey(blank=True, help_text='Equipment related to this ticket (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='equipment.equipment', verbose_name='Related Equipment')),
                ('user', models.ForeignKey(blank=True, help_text='Authenticated user who created the ticket (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketComment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.TextField(help_text='Comment text', verbose_name='Comment')),
                ('is_internal', models.BooleanField(default=False, help_text='Whether this comment is internal (only visible to staff)', verbose_name='Is Internal')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('ticket', models.ForeignKey(help_text='Ticket this comment belongs to', on_delete=django.db.models.deletion.PROTECT, related_name='comments', to='support.ticket', verbose_name='Ticket')),
                ('user', models.ForeignKey(blank=True, help_text='User who made the comment (staff or ticket creator)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_comments', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Ticket Comment',
                'verbose_name_plural': 'Ticket Comments',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['status', 'created_at'], name='support_tic_status_d0b46e_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['ticket_type', 'status'], name='support_tic_ticket__425f94_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['priority', 'status'], name='support_tic_priorit_eb856a_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['user', 'status'], name='support_tic_user_id_bbc719_idx'),
        ),
    ]
