# Generated by Django 5.2.9 on 2026-01-20 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketType',
            fields=[
                ('ticket_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, help_text="Unique code for this ticket type (e.g., 'query', 'request')", max_length=50, unique=True, verbose_name='Code')),
                ('name', models.CharField(help_text='Display name for this ticket type', max_length=255, verbose_name='Name')),
                ('description', models.TextField(blank=True, help_text='Description of when to use this ticket type', null=True, verbose_name='Description')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this ticket type is active and can be used', verbose_name='Is Active')),
                ('display_order', models.IntegerField(default=0, help_text='Order in which this type should be displayed', verbose_name='Display Order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Ticket Type',
                'verbose_name_plural': 'Ticket Types',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.RenameIndex(
            model_name='ticket',
            new_name='support_tic_ticket__e42be8_idx',
            old_name='support_tic_ticket__425f94_idx',
        ),
        migrations.AddIndex(
            model_name='tickettype',
            index=models.Index(fields=['is_active', 'display_order'], name='support_tic_is_acti_8614d8_idx'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_type',
            field=models.ForeignKey(help_text='Type of ticket', on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='support.tickettype', verbose_name='Ticket Type'),
        ),
    ]
