# Generated by Django 5.2.9 on 2026-02-12 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_tickettype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_type',
            field=models.CharField(choices=[('booking', 'Booking'), ('equipment', 'Equipment'), ('other', 'Other')], db_index=True, default='other', help_text='Type of ticket', max_length=50, verbose_name='Ticket Type'),
        ),
        migrations.RenameIndex(
            model_name='ticket',
            new_name='support_tic_ticket__425f94_idx',
            old_name='support_tic_ticket__e42be8_idx',
        ),
        migrations.DeleteModel(
            name='TicketType',
        ),
    ]
