# Generated by Django 5.2.9 on 2026-03-08 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0004_ticket_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_type',
            field=models.CharField(choices=[('booking', 'Booking'), ('equipment', 'Equipment'), ('other', 'Other'), ('quality_improvement', 'Quality improvement suggestions/Bugs')], db_index=True, default='other', help_text='Type of ticket', max_length=50, verbose_name='Ticket Type'),
        ),
    ]
