# Generated by Django 5.2.9 on 2026-07-18 11:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0007_ticketevent_and_expanded_types'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalFeedback',
            fields=[
                ('feedback_id', models.AutoField(primary_key=True, serialize=False)),
                ('overall_rating', models.IntegerField(help_text='1–5 stars', verbose_name='Overall rating')),
                ('ease_of_booking', models.IntegerField(help_text='1–5 stars', verbose_name='Ease of booking')),
                ('website_usability', models.IntegerField(help_text='1–5 stars', verbose_name='Website usability')),
                ('equipment_booking_experience', models.IntegerField(help_text='1–5 stars', verbose_name='Equipment booking experience')),
                ('suggestions', models.TextField(blank=True, default='', verbose_name='Suggestions for improvement')),
                ('comments', models.TextField(blank=True, default='', verbose_name='Additional comments')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='portal_feedback', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Portal Feedback',
                'verbose_name_plural': 'Portal Feedback',
                'ordering': ['-updated_at'],
                'constraints': [models.UniqueConstraint(fields=('user',), name='unique_portal_feedback_per_user')],
            },
        ),
    ]
