# Generated by Django 5.2.9 on 2025-12-20 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_add_lab_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_time', models.TimeField(help_text='Opening time for equipment booking', verbose_name='Open Time')),
                ('close_time', models.TimeField(help_text='Closing time for equipment booking', verbose_name='Close Time')),
                ('slot_duration_minutes', models.IntegerField(help_text='Duration of each booking slot in minutes', verbose_name='Slot Duration (minutes)')),
                ('cooling_time_minutes', models.IntegerField(default=0, help_text='Cooling time required between bookings in minutes', verbose_name='Cooling Time (minutes)')),
                ('variance_minutes', models.IntegerField(default=0, help_text='Allowed variance in booking time in minutes', verbose_name='Variance (minutes)')),
                ('internal_weekly_limit', models.IntegerField(default=0, help_text='Weekly booking limit for internal users', verbose_name='Internal Weekly Limit')),
                ('internal_monthly_limit', models.IntegerField(default=0, help_text='Monthly booking limit for internal users', verbose_name='Internal Monthly Limit')),
                ('external_weekly_limit', models.IntegerField(default=0, help_text='Weekly booking limit for external users', verbose_name='External Weekly Limit')),
                ('external_monthly_limit', models.IntegerField(default=0, help_text='Monthly booking limit for external users', verbose_name='External Monthly Limit')),
                ('external_quota_percent', models.IntegerField(default=0, help_text='Percentage of slots reserved for external users', verbose_name='External Quota Percent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
            ],
            options={
                'verbose_name': 'Equipment Group',
                'verbose_name_plural': 'Equipment Groups',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='lab',
            name='location',
            field=models.TextField(blank=True, help_text='Location of the lab', verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='lab',
            name='name',
            field=models.CharField(help_text='Name of the lab', max_length=150, verbose_name='Lab Name'),
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the equipment', max_length=150, verbose_name='Equipment Name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('lab', models.ForeignKey(help_text='Lab this equipment belongs to', on_delete=django.db.models.deletion.PROTECT, related_name='equipment', to='users.lab', verbose_name='Lab')),
                ('group', models.ForeignKey(blank=True, help_text='Equipment group for slot rules', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment', to='users.equipmentgroup', verbose_name='Equipment Group')),
            ],
            options={
                'verbose_name': 'Equipment',
                'verbose_name_plural': 'Equipment',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentAccessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the accessory', max_length=150, verbose_name='Accessory Name')),
                ('is_optional', models.BooleanField(default=False, help_text='Whether this accessory is optional', verbose_name='Is Optional')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('equipment', models.ForeignKey(help_text='Equipment this accessory belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='accessories', to='users.equipment', verbose_name='Equipment')),
            ],
            options={
                'verbose_name': 'Equipment Accessory',
                'verbose_name_plural': 'Equipment Accessories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MasterLookup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the lookup value', max_length=255, verbose_name='Name')),
                ('code', models.CharField(help_text='Unique code for the lookup value', max_length=100, unique=True, verbose_name='Code')),
                ('category', models.CharField(help_text="Category/type of lookup (e.g., 'status', 'equipment_status')", max_length=100, verbose_name='Category')),
                ('description', models.TextField(blank=True, help_text='Optional description', verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
            ],
            options={
                'verbose_name': 'Master Lookup',
                'verbose_name_plural': 'Master Lookups',
                'ordering': ['category', 'name'],
                'indexes': [models.Index(fields=['category'], name='users_maste_categor_e2944b_idx')],
            },
        ),
        migrations.AddField(
            model_name='equipment',
            name='equipment_status',
            field=models.ForeignKey(blank=True, help_text='Status of the equipment', limit_choices_to={'category': 'equipment_status'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment', to='users.masterlookup', verbose_name='Equipment Status'),
        ),
        migrations.AddField(
            model_name='lab',
            name='status',
            field=models.ForeignKey(blank=True, help_text='Status of the lab', limit_choices_to={'category': 'lab_status'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='labs', to='users.masterlookup', verbose_name='Status'),
        ),
        migrations.CreateModel(
            name='EquipmentSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spec_key', models.CharField(help_text='Key/name of the specification', max_length=100, verbose_name='Specification Key')),
                ('spec_value', models.TextField(help_text='Value of the specification', verbose_name='Specification Value')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('equipment', models.ForeignKey(help_text='Equipment this specification belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='users.equipment', verbose_name='Equipment')),
            ],
            options={
                'verbose_name': 'Equipment Specification',
                'verbose_name_plural': 'Equipment Specifications',
                'ordering': ['spec_key'],
                'indexes': [models.Index(fields=['equipment', 'spec_key'], name='users_equip_equipme_d95ea1_idx')],
            },
        ),
    ]
