# Generated by Django 5.2.9 on 2025-12-20 17:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_equipmentgroup_lab_location_alter_lab_name_equipment_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='masterlookup',
            options={'ordering': ['category', 'display_order', 'name'], 'verbose_name': 'Master Lookup', 'verbose_name_plural': 'Master Lookups'},
        ),
        migrations.AddField(
            model_name='masterlookup',
            name='display_order',
            field=models.IntegerField(default=0, help_text='Order in which this value should be displayed (lower numbers first)', verbose_name='Display Order'),
        ),
        migrations.AddField(
            model_name='masterlookup',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this lookup value is active and available for use', verbose_name='Is Active'),
        ),
        migrations.AddField(
            model_name='masterlookup',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='equipment_status',
            field=models.ForeignKey(blank=True, help_text='Status of the equipment', limit_choices_to={'category': 'equipment_status', 'is_active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment', to='users.masterlookup', verbose_name='Equipment Status'),
        ),
        migrations.AlterField(
            model_name='lab',
            name='status',
            field=models.ForeignKey(blank=True, help_text='Status of the lab', limit_choices_to={'category': 'lab_status', 'is_active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='labs', to='users.masterlookup', verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='masterlookup',
            name='category',
            field=models.CharField(help_text="Category/type of lookup (e.g., 'lab_status', 'user_type', 'user_role')", max_length=100, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='masterlookup',
            name='code',
            field=models.CharField(help_text='Unique code for the lookup value within its category', max_length=100, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='masterlookup',
            name='name',
            field=models.CharField(help_text='Display name of the lookup value', max_length=255, verbose_name='Name'),
        ),
        # Note: user_type and transaction_type field alterations moved to migration 0010
        # to handle data migration properly. Supervisor limit_choices_to will be updated in 0010.
        migrations.AddIndex(
            model_name='masterlookup',
            index=models.Index(fields=['category', 'is_active'], name='users_maste_categor_a9a32c_idx'),
        ),
        migrations.AddConstraint(
            model_name='masterlookup',
            constraint=models.UniqueConstraint(fields=('category', 'code'), name='unique_lookup_category_code'),
        ),
    ]
