# Generated by Django 5.2.9 on 2025-12-27 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_lab_equipment_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterlookup',
            name='category',
            field=models.CharField(choices=[('lab_status', 'Lab Status'), ('equipment_status', 'Equipment Status'), ('booking_status', 'Booking Status'), ('user_status', 'User Status'), ('user_type', 'User Type'), ('transaction_type', 'Transaction Type'), ('equipment_type', 'Equipment Type'), ('user_role', 'User Role'), ('system_role', 'System Role'), ('payment_status', 'Payment Status'), ('approval_status', 'Approval Status')], help_text="Category/type of lookup (e.g., 'lab_status', 'user_type', 'user_role')", max_length=100, verbose_name='Category'),
        ),
        migrations.DeleteModel(
            name='Supervisor',
        ),
    ]
