# Generated by Django 5.2.9 on 2025-12-29 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_fix_user_active_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='branch_name',
            field=models.CharField(blank=True, help_text='Branch name for students', max_length=255, null=True, verbose_name='Branch Name'),
        ),
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text="User's date of birth", null=True, verbose_name='Date of Birth'),
        ),
        migrations.AddField(
            model_name='user',
            name='degree_name',
            field=models.CharField(blank=True, help_text='Degree name for students', max_length=255, null=True, verbose_name='Degree Name'),
        ),
        migrations.AddField(
            model_name='user',
            name='designation',
            field=models.CharField(blank=True, help_text='Designation for faculty members', max_length=255, null=True, verbose_name='Designation'),
        ),
        migrations.AddField(
            model_name='user',
            name='internal_id',
            field=models.CharField(blank=True, help_text='Internal user ID from external system (e.g., Omniport)', max_length=100, null=True, verbose_name='Internal ID'),
        ),
        migrations.AddField(
            model_name='user',
            name='secondary_phone_number',
            field=models.CharField(blank=True, help_text='Secondary contact phone number', max_length=20, null=True, verbose_name='Secondary Phone Number'),
        ),
    ]
