# Generated by Django 5.2.9 on 2025-01-XX XX:XX

from django.db import migrations, models


def migrate_user_type_to_code(apps, schema_editor):
    """Migrate user_type from ForeignKey to CharField storing code."""
    User = apps.get_model("users", "User")
    
    # Migrate user_type ForeignKey to code string
    for user in User.objects.filter(user_type_id__isnull=False).select_related("user_type"):
        if user.user_type:
            User.objects.filter(pk=user.pk).update(user_type_code=user.user_type.code)


def migrate_transaction_type_to_code(apps, schema_editor):
    """Migrate transaction_type from ForeignKey to CharField storing code."""
    WalletTransaction = apps.get_model("users", "WalletTransaction")
    
    # Migrate transaction_type ForeignKey to code string
    for transaction in WalletTransaction.objects.filter(transaction_type_id__isnull=False).select_related("transaction_type"):
        if transaction.transaction_type:
            WalletTransaction.objects.filter(pk=transaction.pk).update(transaction_type_code=transaction.transaction_type.code)


def reverse_migrate_user_type(apps, schema_editor):
    """Reverse migration - convert codes back to ForeignKeys."""
    # This is a no-op since we're removing MasterLookup
    # In a real reverse, we would need to recreate MasterLookup entries
    pass


def reverse_migrate_transaction_type(apps, schema_editor):
    """Reverse migration - convert codes back to ForeignKeys."""
    # This is a no-op since we're removing MasterLookup
    # In a real reverse, we would need to recreate MasterLookup entries
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_add_omniport_fields'),
    ]

    operations = [
        # Step 1: Add temporary CharField for user_type
        migrations.AddField(
            model_name='user',
            name='user_type_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        # Step 2: Migrate data from ForeignKey to CharField
        migrations.RunPython(migrate_user_type_to_code, reverse_migrate_user_type),
        # Step 4: Remove old ForeignKey field
        migrations.RemoveField(
            model_name='user',
            name='user_type',
        ),
        # Step 5: Rename new field to user_type
        migrations.RenameField(
            model_name='user',
            old_name='user_type_code',
            new_name='user_type',
        ),
        # Step 6: Update field definition
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(
                blank=True,
                choices=[
                    ('admin', 'Admin'),
                    ('manager', 'Manager'),
                    ('operator', 'Operator'),
                    ('finance', 'Finance'),
                    ('student', 'Student'),
                    ('faculty', 'Faculty'),
                    ('external', 'External'),
                    ('RND', 'RND'),
                    ('Industry', 'Industry'),
                ],
                help_text='Type of user in the system',
                max_length=50,
                null=True,
                verbose_name='User Type',
            ),
        ),
        # Step 7: Add temporary CharField for transaction_type
        migrations.AddField(
            model_name='wallettransaction',
            name='transaction_type_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        # Step 8: Migrate data from ForeignKey to CharField
        migrations.RunPython(migrate_transaction_type_to_code, reverse_migrate_transaction_type),
        # Step 10: Remove old ForeignKey field
        migrations.RemoveField(
            model_name='wallettransaction',
            name='transaction_type',
        ),
        # Step 11: Rename new field to transaction_type
        migrations.RenameField(
            model_name='wallettransaction',
            old_name='transaction_type_code',
            new_name='transaction_type',
        ),
        # Step 12: Update field definition
        migrations.AlterField(
            model_name='wallettransaction',
            name='transaction_type',
            field=models.CharField(
                choices=[('credit', 'Credit'), ('debit', 'Debit')],
                help_text='Type of transaction',
                max_length=50,
                verbose_name='Transaction Type',
            ),
        ),
        # Step 13: Delete MasterLookup model
        migrations.DeleteModel(
            name='MasterLookup',
        ),
    ]

