# Generated by Django 5.2.9 on 2025-12-30 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_remove_masterlookup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('manager', 'Officer In Charge'), ('operator', 'Lab Incharge'), ('finance', 'Accounts In Charge'), ('student', 'Student'), ('faculty', 'Faculty'), ('external', 'Educational Institute'), ('RND', 'Govt R&D Center'), ('Industry', 'Industry')], help_text='Type of user in the system', max_length=50, null=True, verbose_name='User Type'),
        ),
    ]
