# Generated by Django 5.2.9 on 2026-01-04 15:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_user_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletJoinRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING', help_text='Status of the join request', max_length=20, verbose_name='Status')),
                ('message', models.TextField(blank=True, help_text='Optional message from student', verbose_name='Message')),
                ('faculty_response', models.TextField(blank=True, help_text='Optional response message from faculty', verbose_name='Faculty Response')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('responded_at', models.DateTimeField(blank=True, help_text='When the faculty responded to the request', null=True, verbose_name='Responded at')),
                ('faculty', models.ForeignKey(help_text='Faculty member whose wallet the student wants to join', on_delete=django.db.models.deletion.CASCADE, related_name='wallet_join_requests_received', to=settings.AUTH_USER_MODEL, verbose_name='Faculty')),
                ('student', models.ForeignKey(help_text='Student requesting to join the wallet', on_delete=django.db.models.deletion.CASCADE, related_name='wallet_join_requests', to=settings.AUTH_USER_MODEL, verbose_name='Student')),
                ('wallet', models.ForeignKey(blank=True, help_text='Wallet the student wants to join', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to='users.wallet', verbose_name='Wallet')),
            ],
            options={
                'verbose_name': 'Wallet Join Request',
                'verbose_name_plural': 'Wallet Join Requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['student', 'status'], name='users_walle_student_b822ac_idx'), models.Index(fields=['faculty', 'status'], name='users_walle_faculty_db334d_idx')],
            },
        ),
    ]
