# Generated by Django 5.2.9 on 2026-01-17 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_add_department_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('manager', 'Officer In Charge'), ('operator', 'Lab Incharge'), ('finance', 'Accounts In Charge'), ('student', 'Student'), ('individual_student', 'Individual Student'), ('faculty', 'Faculty'), ('external', 'Educational Institute'), ('RND', 'Govt R&D Center'), ('Industry', 'Industry'), ('other', 'Other')], help_text='Type of user in the system', max_length=50, null=True, verbose_name='User Type'),
        ),
    ]
