# Generated by Django 5.2.9 on 2026-01-20 14:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_alter_user_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletRechargeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount to recharge', max_digits=10, verbose_name='Amount')),
                ('project_details', models.TextField(blank=True, help_text='Optional project details for the recharge', verbose_name='Project Details')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING', help_text='Status of the recharge request', max_length=20, verbose_name='Status')),
                ('otp_code', models.CharField(blank=True, help_text='OTP code for email approval', max_length=6, verbose_name='OTP Code')),
                ('otp_expires_at', models.DateTimeField(blank=True, help_text='When the OTP expires', null=True, verbose_name='OTP Expires At')),
                ('approved_by_email', models.CharField(blank=True, help_text='Email address that approved/rejected the request', max_length=255, verbose_name='Approved By Email')),
                ('response_message', models.TextField(blank=True, help_text='Optional response message from accounts team', verbose_name='Response Message')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('responded_at', models.DateTimeField(blank=True, help_text='When the request was approved/rejected', null=True, verbose_name='Responded at')),
                ('user', models.ForeignKey(help_text='User requesting wallet recharge', on_delete=django.db.models.deletion.CASCADE, related_name='wallet_recharge_requests', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('wallet', models.ForeignKey(help_text='Wallet to be recharged', on_delete=django.db.models.deletion.CASCADE, related_name='recharge_requests', to='users.wallet', verbose_name='Wallet')),
            ],
            options={
                'verbose_name': 'Wallet Recharge Request',
                'verbose_name_plural': 'Wallet Recharge Requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='users_walle_user_id_8f7cc3_idx'), models.Index(fields=['status', 'created_at'], name='users_walle_status_224436_idx')],
            },
        ),
    ]
