# Generated by Django 5.2.9 on 2026-01-20 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_walletrechargerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='walletrechargerequest',
            name='user_otp_code',
            field=models.CharField(blank=True, help_text="OTP code sent to user's email for verification", max_length=6, verbose_name='User OTP Code'),
        ),
        migrations.AddField(
            model_name='walletrechargerequest',
            name='user_otp_expires_at',
            field=models.DateTimeField(blank=True, help_text='When the user OTP expires', null=True, verbose_name='User OTP Expires At'),
        ),
        migrations.AddField(
            model_name='walletrechargerequest',
            name='user_otp_verified',
            field=models.BooleanField(default=False, help_text='Whether user has verified their OTP', verbose_name='User OTP Verified'),
        ),
        migrations.AlterField(
            model_name='walletrechargerequest',
            name='otp_code',
            field=models.CharField(blank=True, help_text='OTP code for accounts team email approval', max_length=6, verbose_name='OTP Code'),
        ),
        migrations.AlterField(
            model_name='walletrechargerequest',
            name='otp_expires_at',
            field=models.DateTimeField(blank=True, help_text='When the accounts team OTP expires', null=True, verbose_name='OTP Expires At'),
        ),
    ]
