# Generated by Django 5.2.9 on 2026-02-03 08:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_walletrechargerequest_user_otp_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the user group', max_length=255, verbose_name='Group Name')),
                ('code', models.CharField(help_text='Short unique code for the group', max_length=50, unique=True, verbose_name='Group Code')),
                ('description', models.TextField(blank=True, help_text='Optional description of the group', null=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User Group',
                'verbose_name_plural': 'User Groups',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserGroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_group_memberships', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('user_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='members', to='users.usergroup', verbose_name='User Group')),
            ],
            options={
                'verbose_name': 'User Group Member',
                'verbose_name_plural': 'User Group Members',
                'ordering': ['user_group', 'user'],
                'unique_together': {('user_group', 'user')},
            },
        ),
    ]
