# Generated by Django 5.2.9

from django.db import migrations, models


def set_equipment_departments_to_internal(apps, schema_editor):
    """Reassign any department with type 'equipment' to 'internal'. Equipment now uses EquipmentCategory."""
    Department = apps.get_model('users', 'Department')
    Department.objects.filter(department_type='equipment').update(department_type='internal')


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_add_user_group_and_member'),
    ]

    operations = [
        migrations.RunPython(set_equipment_departments_to_internal, noop_reverse),
        migrations.AlterField(
            model_name='department',
            name='department_type',
            field=models.CharField(
                choices=[('internal', 'Internal Department'), ('external', 'External Department')],
                default='internal',
                help_text='Type of department: Internal or External',
                max_length=50,
                verbose_name='Department Type',
            ),
        ),
    ]
