# Generated by Django 5.2.9 on 2026-02-08 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_remove_equipment_department_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, help_text='Current sub-wallet balance for this department', max_digits=10, verbose_name='Balance')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('department', models.ForeignKey(help_text='Internal department this sub-wallet is for', limit_choices_to={'department_type': 'internal'}, on_delete=django.db.models.deletion.CASCADE, related_name='sub_wallets', to='users.department', verbose_name='Internal Department')),
                ('wallet', models.ForeignKey(help_text='Main wallet this sub-wallet belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='sub_wallets', to='users.wallet', verbose_name='Wallet')),
            ],
            options={
                'verbose_name': 'Sub-Wallet',
                'verbose_name_plural': 'Sub-Wallets',
                'ordering': ['department__name'],
            },
        ),
        migrations.CreateModel(
            name='SubWalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], max_length=50, verbose_name='Transaction Type')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('sub_wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='users.subwallet', verbose_name='Sub-Wallet')),
            ],
            options={
                'verbose_name': 'Sub-Wallet Transaction',
                'verbose_name_plural': 'Sub-Wallet Transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='subwallet',
            constraint=models.UniqueConstraint(fields=('wallet', 'department'), name='unique_wallet_department_subwallet'),
        ),
    ]
