# Generated by Django 5.2.9 on 2026-02-08 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_add_sub_wallet_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='walletrechargerequest',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Internal department whose sub-wallet will be credited. Required for new recharges.', limit_choices_to={'department_type': 'internal'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recharge_requests', to='users.department', verbose_name='Department (sub-wallet to credit)'),
        ),
        migrations.CreateModel(
            name='WalletRazorpayOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paise', models.IntegerField(help_text='Order amount in paise', verbose_name='Amount (paise)')),
                ('order_id', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Razorpay Order ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('department', models.ForeignKey(limit_choices_to={'department_type': 'internal'}, on_delete=django.db.models.deletion.CASCADE, related_name='razorpay_recharge_orders', to='users.department', verbose_name='Department (sub-wallet)')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='razorpay_orders', to='users.wallet', verbose_name='Wallet')),
            ],
            options={
                'verbose_name': 'Wallet Razorpay Order',
                'verbose_name_plural': 'Wallet Razorpay Orders',
                'ordering': ['-created_at'],
            },
        ),
    ]
