# Generated by Django 5.2.9 on 2026-02-12 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_remove_wallet_balance_and_transactions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walletrechargerequest',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Internal department whose sub-wallet will be credited. Required for all new recharge requests.', limit_choices_to={'department_type': 'internal'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recharge_requests', to='users.department', verbose_name='Department (sub-wallet to credit)'),
        ),
    ]
