# Generated by Django 5.2.9 on 2026-02-17 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_alter_walletrechargerequest_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the research project', max_length=255, verbose_name='Project Name')),
                ('project_code', models.CharField(help_text='Unique code for the project', max_length=100, verbose_name='Project Code')),
                ('agency', models.CharField(help_text='Name of the funding agency', max_length=255, verbose_name='Funding Agency')),
                ('start_date', models.DateField(blank=True, help_text='Project start date', null=True, verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, help_text='Project end date', null=True, verbose_name='End Date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('faculty', models.ForeignKey(help_text='Faculty member who owns this project', on_delete=django.db.models.deletion.PROTECT, related_name='projects', to=settings.AUTH_USER_MODEL, verbose_name='Faculty')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['faculty', '-created_at'], name='users_proje_faculty_idx'),
        ),
    ]
