# Generated by Django 5.2.9 on 2026-02-17 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_add_project_model'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='project',
            new_name='users_proje_faculty_ccc6b3_idx',
            old_name='users_proje_faculty_idx',
        ),
    ]
