# Generated by Django 5.2.9 on 2026-02-17 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_add_project_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether the project is currently active', verbose_name='Is Active'),
        ),
    ]
