# Generated by Django 5.2.9 on 2026-02-17 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_add_project_is_active'),
        ('users', '0031_rename_users_proje_faculty_idx_users_proje_faculty_ccc6b3_idx'),
    ]

    operations = [
    ]
