# Generated by Django 5.2.9 on 2026-02-17 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_add_project_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='walletrechargerequest',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Optional project associated with the recharge', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recharge_requests', to='users.project', verbose_name='Project'),
        ),
    ]
