# Generated by Django 5.2.9 on 2026-02-17 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_add_project_to_wallet_recharge_request'),
        ('users', '0032_merge_20260217_1603'),
    ]

    operations = [
    ]
