# Generated by Django 5.2.9 on 2026-02-17 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_add_auto_slot_selection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walletrechargerequest',
            name='project_details',
            field=models.TextField(blank=True, help_text='Optional project details for the recharge (deprecated, use project field instead)', verbose_name='Project Details'),
        ),
    ]
