# Generated by Django 5.2.9 on 2026-03-03 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0038_wallet_recharge_import_record'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='walletrechargeimportrecord',
            name='unique_receipt_per_fy',
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('manager', 'Officer In Charge'), ('operator', 'Lab Incharge'), ('finance', 'Accounts In Charge'), ('student', 'IITR Student'), ('individual_student', 'Individual Student'), ('faculty', 'IITR Faculty'), ('external', 'Educational Institute'), ('RND', 'Govt R&D Center'), ('Industry', 'Industry'), ('other', 'Other')], help_text='Type of user in the system', max_length=50, null=True, verbose_name='User Type'),
        ),
        migrations.AddConstraint(
            model_name='walletrechargeimportrecord',
            constraint=models.UniqueConstraint(condition=models.Q(('dated__isnull', False)), fields=('receipt_no', 'dated', 'user'), name='unique_receipt_dated_user'),
        ),
        migrations.AddConstraint(
            model_name='walletrechargeimportrecord',
            constraint=models.UniqueConstraint(condition=models.Q(('dated__isnull', True)), fields=('receipt_no', 'user'), name='unique_receipt_user_no_date'),
        ),
    ]
