# Generated by Django 5.2.9 on 2026-03-03 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0039_wallet_recharge_import_unique_date_receipt_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletRechargeParseEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dated', models.DateField(blank=True, null=True, verbose_name='Date')),
                ('receipt_no', models.CharField(db_index=True, max_length=50, verbose_name='Receipt No.')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Name')),
                ('emp_no', models.CharField(db_index=True, max_length=50, verbose_name='Emp No.')),
                ('department', models.CharField(blank=True, max_length=255, verbose_name='Department')),
                ('amount', models.CharField(max_length=50, verbose_name='Amount (display)')),
                ('payment', models.TextField(blank=True, verbose_name='Payment Details')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
            ],
            options={
                'verbose_name': 'Wallet Recharge Parse Entry',
                'verbose_name_plural': 'Wallet Recharge Parse Entries',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('dated__isnull', False)), fields=('receipt_no', 'dated', 'emp_no'), name='unique_parse_entry_dated'), models.UniqueConstraint(condition=models.Q(('dated__isnull', True)), fields=('receipt_no', 'emp_no'), name='unique_parse_entry_no_date')],
            },
        ),
    ]
