# Generated by Django 5.2.9

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0040_wallet_recharge_parse_entry"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="user_type_alias",
            field=models.CharField(
                blank=True,
                help_text="Optional display label for IITR Student only (e.g. Guest Student). Shown in UI; internally user remains IITR Student.",
                max_length=100,
                null=True,
                verbose_name="User Type Alias",
            ),
        ),
    ]
