# Generated by Django 5.2.9

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0041_user_user_type_alias"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="supervisor",
            field=models.ForeignKey(
                blank=True,
                help_text="IITR Faculty supervisor for Post Doctoral Fellows and Research Associates in Projects",
                limit_choices_to={"user_type": "faculty"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="supervised_users",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Supervisor (IITR Faculty)",
            ),
        ),
    ]
