# Generated by Django for program/course duration and validation

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0042_add_user_supervisor"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="supervisor_approved",
            field=models.BooleanField(
                default=False,
                help_text="For IITR Post Doctoral Fellows and Research Associates: supervisor must approve before admin approval.",
                verbose_name="Supervisor Approved",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="program_start_date",
            field=models.DateField(
                blank=True,
                help_text="Start date of program, course, or position. Used with end date to enforce access duration and revalidation if > 1 year.",
                null=True,
                verbose_name="Program/Course Start Date",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="program_end_date",
            field=models.DateField(
                blank=True,
                help_text="End date of program, course, or position. Access is disabled after this date.",
                null=True,
                verbose_name="Program/Course End Date",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="access_on_hold",
            field=models.BooleanField(
                default=False,
                help_text="When True, access is blocked until user revalidates by submitting documentary evidence (e.g. when program duration > 1 year).",
                verbose_name="Access On Hold",
            ),
        ),
    ]
