# Generated by Django 5.2.9 on 2026-03-04 13:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0043_program_duration_and_validation'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='external_subcategory',
            field=models.CharField(blank=True, choices=[('educational_institute', 'Educational Institute'), ('govt_rnd', 'Govt R&D Organizations'), ('industries', 'Industries')], help_text='For External departments only: Educational Institute, Govt R&D Organizations, or Industries', max_length=50, null=True, verbose_name='External subcategory'),
        ),
        migrations.AlterField(
            model_name='department',
            name='department_type',
            field=models.CharField(choices=[('internal', 'Internal'), ('external', 'External')], default='internal', help_text='Type of department: Internal or External', max_length=50, verbose_name='Department Type'),
        ),
        migrations.AlterField(
            model_name='user',
            name='supervisor',
            field=models.ForeignKey(blank=True, help_text='IITR Faculty supervisor for Post Doctoral Fellows and Research Associates in Projects', limit_choices_to={'department__department_type': 'internal', 'user_type': 'faculty'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_users', to=settings.AUTH_USER_MODEL, verbose_name='Supervisor (IITR Faculty)'),
        ),
    ]
