# Generated by Django 5.2.9 on 2026-03-04 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0045_add_external_department_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='internal_subcategory',
            field=models.CharField(blank=True, choices=[('iit_roorkee_dept_centres', 'IIT Roorkee Department/Centres'), ('startups', 'Startups')], help_text='For Internal departments only: IIT Roorkee Department/Centres or Startups', max_length=50, null=True, verbose_name='Internal subcategory'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('manager', 'Officer In Charge'), ('operator', 'Lab Incharge'), ('finance', 'Accounts In Charge'), ('student', 'IITR Student'), ('individual_student', 'Individual Student'), ('faculty', 'IITR Faculty'), ('external', 'Educational Institute'), ('RND', 'Govt R&D Organizations'), ('Industry', 'Industry'), ('other', 'Other')], help_text='Type of user in the system', max_length=50, null=True, verbose_name='User Type'),
        ),
    ]
