# Generated by Django 5.2.9 on 2026-03-08 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0052_revert_inactivity_timeout_to_seconds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authsettings',
            name='inactivity_timeout_seconds',
            field=models.PositiveIntegerField(default=1800, help_text='Seconds of inactivity after which the user is automatically logged out (default 1800 = 30 minutes).'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], help_text='Gender (optional)', max_length=30, null=True, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='user',
            name='program_end_date',
            field=models.DateField(blank=True, help_text='Program valid until. Access is disabled after this date.', null=True, verbose_name='Program Valid Until'),
        ),
        migrations.AlterField(
            model_name='usertypeinactivitytimeout',
            name='inactivity_timeout_seconds',
            field=models.PositiveIntegerField(default=1800, help_text='Seconds of inactivity after which this user type is automatically logged out (e.g. 1800 = 30 min).'),
        ),
        migrations.AlterField(
            model_name='usertypeinactivitytimeout',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Officer In Charge'), ('operator', 'Lab Incharge'), ('finance', 'Accounts In Charge'), ('student', 'IITR Student'), ('individual_student', 'Individual Student'), ('faculty', 'IITR Faculty'), ('external', 'Educational Institute'), ('RND', 'Govt R&D Organizations'), ('Industry', 'Industry'), ('other', 'Other')], help_text='User type (e.g. student, faculty, admin). Each type can have its own timeout.', max_length=50, unique=True),
        ),
    ]
