# Generated by Django 5.2.9 on 2026-03-17 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0060_organizationrequest_requester_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalbillingprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='program_end_date',
            field=models.DateField(blank=True, help_text='Current program or employment validity. Access is disabled after this date.', null=True, verbose_name='Current Program/Employment Validity'),
        ),
    ]
