# Generated by Django 5.2.9 on 2026-03-23 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0064_add_use_discounted_charge_profile'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='walletwithdrawalrequest',
            new_name='users_walle_user_id_7e351e_idx',
            old_name='users_walletw_user_id_6b678f_idx',
        ),
        migrations.RenameIndex(
            model_name='walletwithdrawalrequest',
            new_name='users_walle_status_1ed7dc_idx',
            old_name='users_walletw_status_439209_idx',
        ),
    ]
