# Generated by Django 5.2 — department head for OIC leave intimation and similar FYI emails

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0074_user_istem_portal_acknowledged"),
    ]

    operations = [
        migrations.AddField(
            model_name="department",
            name="head",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional. If set, this user receives informational emails (e.g. OIC self-service leave) for members of this department.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="headed_departments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Department head",
            ),
        ),
    ]
