# Generated by Django 5.2.9 on 2026-07-14 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0078_user_oic_dashboard_flags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="department",
            name="internal_grant_code",
            field=models.CharField(
                blank=True,
                help_text=(
                    "SRIC / accounts grant code for this internal department (instrument cost centre). "
                    "Also editable under Admin → Wallet SRIC office notification settings. "
                    "Used in SRIC Office recharge emails and the SRIC transfer API."
                ),
                max_length=80,
                verbose_name="Internal grant code",
            ),
        ),
        migrations.AlterField(
            model_name="walletsricsettings",
            name="grant_code_for_credit",
            field=models.CharField(
                default="IIC-000-002",
                help_text=(
                    "Used in the SRIC Office recharge email only when the selected internal department "
                    "has no grant code of its own. Prefer setting codes per department below / on this page."
                ),
                max_length=80,
                verbose_name="Default grant code (fallback)",
            ),
        ),
    ]
