# Generated by Django 5.2.9 on 2026-07-15 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0080_user_is_test_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletStudentRechargeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_iitr_student_wallet_recharge', models.BooleanField(default=False, help_text='When on, IITR Students may recharge via SBIePay or Offline Request (payment receipt upload). Funds park in the concerned faculty wallet. Individual Students keep their own wallet and are not gated by this flag.', verbose_name='Enable IITR Student wallet recharge')),
            ],
            options={
                'verbose_name': 'Wallet student recharge settings',
                'verbose_name_plural': 'Wallet student recharge settings',
                'db_table': 'users_walletstudentrechargesettings',
            },
        ),
        migrations.AddField(
            model_name='departmentpaymentreceipt',
            name='receipt_file',
            field=models.FileField(blank=True, help_text='Scanned / photographed payment receipt (required for IITR Student offline recharge).', null=True, upload_to='wallet_payment_receipts/%Y/%m/%d/', verbose_name='Payment receipt file'),
        ),
        migrations.AlterField(
            model_name='department',
            name='external_subcategory',
            field=models.CharField(blank=True, choices=[('educational_institute', 'Educational Institute'), ('govt_rnd', 'Govt R&D Organizations'), ('industries', 'Industries'), ('external_startup_msme', 'External Startup/MSME')], help_text='For External departments only: Educational Institute, Govt R&D Organizations, Industries, or External Startup/MSME', max_length=50, null=True, verbose_name='External subcategory'),
        ),
        migrations.AlterField(
            model_name='organizationrequest',
            name='external_subcategory',
            field=models.CharField(choices=[('educational_institute', 'Educational Institute'), ('govt_rnd', 'Govt R&D Organizations'), ('industries', 'Industries'), ('external_startup_msme', 'External Startup/MSME')], default='govt_rnd', help_text='External subcategory (e.g. Educational Institute, Govt R&D Organizations, Industries).', max_length=50, verbose_name='External subcategory'),
        ),
        migrations.AlterField(
            model_name='paymentgatewaytransaction',
            name='gateway_transaction_id',
            field=models.CharField(blank=True, help_text='SBIePay ATRN / bank reference after payment', max_length=128, verbose_name='Gateway transaction reference'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('manager', 'Officer In Charge'), ('operator', 'Lab Incharge'), ('finance', 'Accounts In Charge'), ('student', 'IITR Student'), ('individual_student', 'Individual Student'), ('faculty', 'IITR Faculty'), ('external', 'Educational Institute'), ('RND', 'Govt R&D Organizations'), ('Industry', 'Industry'), ('startup_incubated_iitr', 'Startup Incubated at IIT Roorkee'), ('external_startup_msme', 'External Startup/MSME'), ('other', 'Other')], help_text='Type of user in the system', max_length=50, null=True, verbose_name='User Type'),
        ),
        migrations.AlterField(
            model_name='usertypeinactivitytimeout',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Officer In Charge'), ('operator', 'Lab Incharge'), ('finance', 'Accounts In Charge'), ('student', 'IITR Student'), ('individual_student', 'Individual Student'), ('faculty', 'IITR Faculty'), ('external', 'Educational Institute'), ('RND', 'Govt R&D Organizations'), ('Industry', 'Industry'), ('startup_incubated_iitr', 'Startup Incubated at IIT Roorkee'), ('external_startup_msme', 'External Startup/MSME'), ('other', 'Other')], help_text='User type (e.g. student, faculty, admin). Each type can have its own timeout.', max_length=50, unique=True),
        ),
    ]
