# Generated by Django 5.2.9 on 2026-07-18 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0080_user_oic_enable_multi_mode'),
        ('users', '0082_internal_rbac_hierarchy'),
    ]

    operations = [
    ]
