# Generated by Django 5.2.9 on 2026-07-19 08:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0085_user_user_guide_viewed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('dept_admin', 'Department Administrator'), ('manager', 'Officer In Charge'), ('operator', 'Lab Incharge'), ('finance', 'Accounts In Charge'), ('org_admin', 'Organization Administrator'), ('external_relations', 'External Relations Administrator'), ('student', 'IITR Student'), ('individual_student', 'Individual Student'), ('faculty', 'IITR Faculty'), ('external', 'Educational Institute'), ('RND', 'Govt R&D Organizations'), ('Industry', 'Industry'), ('startup_incubated_iitr', 'Startup Incubated at IIT Roorkee'), ('external_startup_msme', 'External Startup/MSME'), ('other', 'Other')], help_text='Type of user in the system', max_length=50, null=True, verbose_name='User Type'),
        ),
        migrations.AlterField(
            model_name='usertypeinactivitytimeout',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('dept_admin', 'Department Administrator'), ('manager', 'Officer In Charge'), ('operator', 'Lab Incharge'), ('finance', 'Accounts In Charge'), ('org_admin', 'Organization Administrator'), ('external_relations', 'External Relations Administrator'), ('student', 'IITR Student'), ('individual_student', 'Individual Student'), ('faculty', 'IITR Faculty'), ('external', 'Educational Institute'), ('RND', 'Govt R&D Organizations'), ('Industry', 'Industry'), ('startup_incubated_iitr', 'Startup Incubated at IIT Roorkee'), ('external_startup_msme', 'External Startup/MSME'), ('other', 'Other')], help_text='User type (e.g. student, faculty, admin). Each type can have its own timeout.', max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='AdminPanelRoleConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('admin', 'Admin'), ('dept_admin', 'Department Administrator'), ('manager', 'Officer In Charge'), ('operator', 'Lab Incharge'), ('finance', 'Accounts In Charge'), ('org_admin', 'Organization Administrator'), ('external_relations', 'External Relations Administrator'), ('student', 'IITR Student'), ('individual_student', 'Individual Student'), ('faculty', 'IITR Faculty'), ('external', 'Educational Institute'), ('RND', 'Govt R&D Organizations'), ('Industry', 'Industry'), ('startup_incubated_iitr', 'Startup Incubated at IIT Roorkee'), ('external_startup_msme', 'External Startup/MSME'), ('other', 'Other')], help_text='User type this configuration applies to', max_length=50)),
                ('admin_panel_enabled', models.BooleanField(default=False, help_text='When false (default), Admin Panel is hidden and APIs reject access.')),
                ('module_keys', models.JSONField(blank=True, default=list, help_text='List of Admin Settings module keys granted when panel is enabled.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(help_text='Department scope for this user-type configuration', on_delete=django.db.models.deletion.CASCADE, related_name='admin_panel_role_configs', to='users.department')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_admin_panel_role_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin Panel Role Config',
                'verbose_name_plural': 'Admin Panel Role Configs',
                'ordering': ['department__name', 'user_type'],
                'unique_together': {('user_type', 'department')},
            },
        ),
    ]
