# Generated by Django 5.2.9 on 2026-07-21 10:35

import django.db.models.deletion
import django.utils.timezone
import iic_booking.users.models.sync_agent
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0086_admin_panel_role_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncAgent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('agent_name', models.CharField(max_length=200, verbose_name='Agent name')),
                ('department_code', models.CharField(max_length=50, verbose_name='Department code')),
                ('machine_name', models.CharField(blank=True, max_length=200, verbose_name='Machine name')),
                ('machine_guid', models.UUIDField(db_index=True, unique=True, verbose_name='Machine GUID')),
                ('version', models.CharField(blank=True, max_length=50, verbose_name='Agent version')),
                ('operating_system', models.CharField(blank=True, max_length=200, verbose_name='Operating system')),
                ('registration_token', models.CharField(default=iic_booking.users.models.sync_agent._generate_token, max_length=128, unique=True, verbose_name='Registration token')),
                ('refresh_token', models.CharField(blank=True, default='', max_length=128, verbose_name='Refresh token')),
                ('access_token', models.CharField(blank=True, default='', max_length=128, verbose_name='Access token')),
                ('access_token_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Access token expires at')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('registered_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Registered at')),
                ('last_authenticated_at', models.DateTimeField(blank=True, null=True, verbose_name='Last authenticated at')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sync_agents', to='users.department')),
            ],
            options={
                'verbose_name': 'Sync Agent',
                'verbose_name_plural': 'Sync Agents',
                'ordering': ['-registered_at'],
            },
        ),
    ]
