# Generated by Django 5.2.9 on 2026-07-21 15:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0087_sync_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='walletrechargerequest',
            name='account_incharge',
            field=models.ForeignKey(blank=True, help_text='Accounts In Charge selected / notified for this request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_recharge_requests_as_incharge', to=settings.AUTH_USER_MODEL, verbose_name='Department Account In-charge'),
        ),
        migrations.AddField(
            model_name='walletrechargerequest',
            name='action_token',
            field=models.CharField(blank=True, db_index=True, help_text='Secure token for email Approve / Reject links', max_length=64, null=True, unique=True, verbose_name='Action Token'),
        ),
        migrations.AddField(
            model_name='walletrechargerequest',
            name='cancellation_source',
            field=models.CharField(blank=True, choices=[('user', 'Cancelled by User'), ('admin', 'Cancelled by Administrator'), ('dept_admin', 'Cancelled by Department Administrator'), ('system', 'Cancelled by System')], help_text='Who cancelled the pending request', max_length=20, verbose_name='Cancellation Source'),
        ),
        migrations.AddField(
            model_name='walletrechargerequest',
            name='department_grant_code',
            field=models.CharField(blank=True, help_text='Wallet credit grant code for the selected recharge department', max_length=100, verbose_name='Department Grant Code (Credit)'),
        ),
        migrations.AddField(
            model_name='walletrechargerequest',
            name='employee_number',
            field=models.CharField(blank=True, help_text='Snapshot of user emp_id / employee number at request time', max_length=50, verbose_name='Employee Number'),
        ),
        migrations.AddField(
            model_name='walletrechargerequest',
            name='processed_by',
            field=models.ForeignKey(blank=True, help_text='Authenticated user who approved/rejected/cancelled (if any)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_wallet_recharge_requests', to=settings.AUTH_USER_MODEL, verbose_name='Processed By'),
        ),
        migrations.AddField(
            model_name='walletrechargerequest',
            name='project_grant_code',
            field=models.CharField(blank=True, help_text='Project grant code used for debit (typically project_code)', max_length=100, verbose_name='Project Grant Code (Debit)'),
        ),
        migrations.AddField(
            model_name='walletrechargerequest',
            name='rejection_reason_code',
            field=models.CharField(blank=True, choices=[('wrong_project_grant', 'Wrong Project Grant Code'), ('insufficient_balance', 'Insufficient Balance in Project Grant'), ('mismatch_user_info', 'Mismatch in User Information'), ('other', 'Others')], help_text='Predefined rejection reason when status is Rejected', max_length=40, verbose_name='Rejection Reason Code'),
        ),
        migrations.AddField(
            model_name='walletrechargerequest',
            name='rejection_reason_text',
            field=models.TextField(blank=True, help_text='Free-text rejection reason (required when reason is Others)', verbose_name='Rejection Reason Text'),
        ),
        migrations.AddField(
            model_name='walletrechargerequest',
            name='user_department_name',
            field=models.CharField(blank=True, help_text="Snapshot of the requesting user's home department name", max_length=255, verbose_name='User Department'),
        ),
        migrations.AlterField(
            model_name='walletrechargerequest',
            name='approved_by_email',
            field=models.CharField(blank=True, help_text='Email address that approved/rejected/cancelled the request', max_length=255, verbose_name='Approved / Rejected By Email'),
        ),
        migrations.AlterField(
            model_name='walletrechargerequest',
            name='otp_code',
            field=models.CharField(blank=True, help_text='Deprecated: accounts team OTP (no longer required for email approval)', max_length=6, verbose_name='OTP Code'),
        ),
        migrations.AlterField(
            model_name='walletrechargerequest',
            name='otp_expires_at',
            field=models.DateTimeField(blank=True, help_text='Deprecated: when the accounts team OTP expires', null=True, verbose_name='OTP Expires At'),
        ),
        migrations.AlterField(
            model_name='walletrechargerequest',
            name='responded_at',
            field=models.DateTimeField(blank=True, help_text='When the request was approved/rejected/cancelled', null=True, verbose_name='Responded at'),
        ),
        migrations.AlterField(
            model_name='walletrechargerequest',
            name='response_message',
            field=models.TextField(blank=True, help_text='Optional response / notes from approver or rejector', verbose_name='Response Message'),
        ),
        migrations.AlterField(
            model_name='walletrechargerequest',
            name='sric_notification_sent',
            field=models.BooleanField(default=False, help_text='Set when the SRIC Office approval email has been sent for this request.', verbose_name='SRIC office notification sent'),
        ),
        migrations.CreateModel(
            name='WalletRechargeRequestAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=20, verbose_name='From Status')),
                ('to_status', models.CharField(max_length=20, verbose_name='To Status')),
                ('action', models.CharField(help_text='created / submitted / approved / rejected / cancelled', max_length=40, verbose_name='Action')),
                ('actor_email', models.CharField(blank=True, max_length=255, verbose_name='Actor Email')),
                ('message', models.TextField(blank=True, verbose_name='Message')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_recharge_audit_actions', to=settings.AUTH_USER_MODEL, verbose_name='Actor')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='users.walletrechargerequest', verbose_name='Recharge Request')),
            ],
            options={
                'verbose_name': 'Wallet Recharge Request Audit Log',
                'verbose_name_plural': 'Wallet Recharge Request Audit Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
