# Generated by Django 5.2.9 on 2026-07-22 17:57

from django.db import migrations, models


def seed_default_redirect(apps, schema_editor):
    TestAccountEmailSettings = apps.get_model("users", "TestAccountEmailSettings")
    TestAccountEmailSettings.objects.get_or_create(
        pk=1,
        defaults={"recipient_emails": "ravisaini.15@gmail.com"},
    )


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0093_wallet_recharge_mode_and_fund_verification"),
    ]

    operations = [
        migrations.CreateModel(
            name="TestAccountEmailSettings",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "recipient_emails",
                    models.TextField(
                        blank=True,
                        help_text=(
                            "One address per line, or comma/semicolon separated. "
                            "All listed addresses receive emails generated for test accounts. "
                            "If empty, falls back to the TEST_ACCOUNT_EMAIL_REDIRECT environment setting."
                        ),
                        verbose_name="Test account email redirect addresses",
                    ),
                ),
            ],
            options={
                "verbose_name": "Test account email redirect settings",
                "verbose_name_plural": "Test account email redirect settings",
                "db_table": "users_testaccountemailsettings",
            },
        ),
        migrations.RunPython(seed_default_redirect, migrations.RunPython.noop),
    ]
