# Generated by Django 5.2.9 on 2026-08-20 04:28

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0097_portal_migration_observability'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletCreditAuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=64)),
                ('previous_value', models.TextField(blank=True, default='')),
                ('new_value', models.TextField(blank=True, default='')),
                ('reason', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Wallet credit audit event',
                'verbose_name_plural': 'Wallet credit audit events',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='WalletCreditFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_reference', models.CharField(db_index=True, max_length=32, unique=True)),
                ('requested_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('approved_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('outstanding_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('purpose', models.TextField()),
                ('remarks', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under review'), ('APPROVED', 'Approved'), ('CREDITED', 'Credited'), ('PARTIALLY_SETTLED', 'Partially settled'), ('CLEARED', 'Cleared'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired'), ('WRITTEN_OFF', 'Written off'), ('CLARIFICATION', 'Returned for clarification')], db_index=True, default='DRAFT', max_length=32)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approval_reason', models.TextField(blank=True, default='')),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('due_date', models.DateField(blank=True, null=True)),
                ('credited_at', models.DateTimeField(blank=True, null=True)),
                ('cleared_at', models.DateTimeField(blank=True, null=True)),
                ('credit_posting_key', models.CharField(blank=True, default='', help_text='Idempotency key for credit posting.', max_length=64)),
                ('profile_snapshot', models.JSONField(blank=True, default=dict, help_text='Audit snapshot of Channel-I/portal profile at submit/approve.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Wallet credit facility',
                'verbose_name_plural': 'Wallet credit facilities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WalletCreditInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=40, unique=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ISSUED', 'Issued'), ('PARTIALLY_PAID', 'Partially paid'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=24)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('approved_credit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('amount_settled', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('outstanding_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('payment_instructions', models.TextField(blank=True, default='')),
                ('terms', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Wallet credit invoice',
                'verbose_name_plural': 'Wallet credit invoices',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WalletCreditLedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('WALLET_CREDIT', 'Wallet credit posted'), ('CREDIT_REPAYMENT', 'Credit repayment'), ('CREDIT_ADJUSTMENT', 'Credit adjustment'), ('CREDIT_REVERSAL', 'Credit reversal')], max_length=32)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reference', models.CharField(max_length=64, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Wallet credit ledger entry',
                'verbose_name_plural': 'Wallet credit ledger entries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WalletCreditPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_date', models.DateField()),
                ('mode', models.CharField(blank=True, default='', max_length=64)),
                ('utr_or_reference', models.CharField(blank=True, default='', max_length=128)),
                ('remarks', models.TextField(blank=True, default='')),
                ('receipt_number', models.CharField(max_length=40, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Wallet credit payment',
                'verbose_name_plural': 'Wallet credit payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WalletCreditPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singleton_key', models.CharField(default='default', max_length=16, unique=True)),
                ('enabled', models.BooleanField(default=False, help_text='Master switch for the admin-approved wallet credit facility.')),
                ('max_credit_amount', models.DecimalField(decimal_places=2, default=Decimal('50000.00'), max_digits=12)),
                ('max_outstanding_amount', models.DecimalField(decimal_places=2, default=Decimal('50000.00'), max_digits=12)),
                ('min_request_amount', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=12)),
                ('max_credit_duration_days', models.PositiveIntegerField(default=30)),
                ('reminder_days_before_due', models.PositiveIntegerField(default=3)),
                ('overdue_reminder_interval_days', models.PositiveIntegerField(default=7)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Wallet credit policy',
                'verbose_name_plural': 'Wallet credit policy',
            },
        ),
        migrations.AddField(
            model_name='walletcreditauditevent',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_credit_audit_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='walletcreditfacility',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_credits_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='walletcreditfacility',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_credit_facilities', to='users.department'),
        ),
        migrations.AddField(
            model_name='walletcreditfacility',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_credits_rejected', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='walletcreditfacility',
            name='sub_wallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_credit_facilities', to='users.subwallet'),
        ),
        migrations.AddField(
            model_name='walletcreditfacility',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wallet_credit_facilities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='walletcreditauditevent',
            name='facility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='users.walletcreditfacility'),
        ),
        migrations.AddField(
            model_name='walletcreditinvoice',
            name='facility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='users.walletcreditfacility'),
        ),
        migrations.AddField(
            model_name='walletcreditinvoice',
            name='issued_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_credit_invoices_issued', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='walletcreditledgerentry',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_credit_ledger_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='walletcreditledgerentry',
            name='facility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='users.walletcreditfacility'),
        ),
        migrations.AddField(
            model_name='walletcreditledgerentry',
            name='subwallet_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_credit_ledger_entries', to='users.subwallettransaction'),
        ),
        migrations.AddField(
            model_name='walletcreditpayment',
            name='facility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='users.walletcreditfacility'),
        ),
        migrations.AddField(
            model_name='walletcreditpayment',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='users.walletcreditinvoice'),
        ),
        migrations.AddField(
            model_name='walletcreditpayment',
            name='ledger_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='users.walletcreditledgerentry'),
        ),
        migrations.AddField(
            model_name='walletcreditpayment',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_credit_payments_recorded', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='walletcreditfacility',
            index=models.Index(fields=['status', 'user'], name='users_walle_status_705552_idx'),
        ),
        migrations.AddIndex(
            model_name='walletcreditfacility',
            index=models.Index(fields=['due_date', 'status'], name='users_walle_due_dat_f3881a_idx'),
        ),
        migrations.AddConstraint(
            model_name='walletcreditfacility',
            constraint=models.CheckConstraint(condition=models.Q(('requested_amount__gt', 0)), name='wallet_credit_requested_amount_gt_0'),
        ),
    ]
