# Generated by Django 5.2.9 on 2026-08-20 06:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seed_undergraduate_degrees(apps, schema_editor):
    StudentDegreeClassification = apps.get_model("users", "StudentDegreeClassification")
    for name in ("B.Tech", "B.E.", "B.Sc."):
        key = " ".join(name.strip().split()).casefold()
        StudentDegreeClassification.objects.get_or_create(
            channel_i_degree_name_normalized=key,
            defaults={
                "channel_i_degree_name": name,
                "normalized_degree_name": name,
                "classification": "UNDERGRADUATE",
                "active": True,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0098_wallet_credit_facility_v2'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelIDepartmentMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_i_department_name', models.CharField(max_length=255)),
                ('channel_i_department_name_normalized', models.CharField(max_length=255, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Channel-I department mapping',
                'ordering': ['channel_i_department_name'],
            },
        ),
        migrations.CreateModel(
            name='ChannelIIdentityHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=64)),
                ('previous_value', models.TextField(blank=True, default='')),
                ('new_value', models.TextField(blank=True, default='')),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Channel-I identity history',
                'ordering': ['recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='ChannelIIdentityProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_i_user_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('channel_i_username', models.CharField(blank=True, default='', max_length=128)),
                ('student_degree_name', models.CharField(blank=True, default='', max_length=255)),
                ('student_department_name', models.CharField(blank=True, default='', max_length=255)),
                ('student_start_date', models.DateField(blank=True, null=True)),
                ('student_end_date', models.DateField(blank=True, null=True)),
                ('faculty_department_name', models.CharField(blank=True, default='', max_length=255)),
                ('faculty_designation', models.CharField(blank=True, default='', max_length=255)),
                ('has_student_payload', models.BooleanField(default=False)),
                ('has_faculty_payload', models.BooleanField(default=False)),
                ('derived_end_date', models.DateField(blank=True, null=True)),
                ('validity_source', models.CharField(choices=[('CHANNEL_I_END_DATE', 'Channel-I end date'), ('START_DATE_PLUS_5_YEARS', 'Start date + 5 years'), ('ADMIN_EXTENSION', 'Admin-approved extension'), ('UNRESOLVED', 'Unresolved')], default='UNRESOLVED', max_length=32)),
                ('last_channel_i_sync', models.DateTimeField(blank=True, null=True)),
                ('profile_last_changed_at', models.DateTimeField(blank=True, null=True)),
                ('raw_student_keys', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Channel-I identity profile',
                'verbose_name_plural': 'Channel-I identity profiles',
            },
        ),
        migrations.CreateModel(
            name='HeadOfDepartmentAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Head of Department assignment',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentDegreeClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_i_degree_name', models.CharField(max_length=255)),
                ('channel_i_degree_name_normalized', models.CharField(max_length=255, unique=True)),
                ('normalized_degree_name', models.CharField(blank=True, default='', max_length=255)),
                ('classification', models.CharField(choices=[('UNDERGRADUATE', 'Undergraduate'), ('POSTGRADUATE', 'Postgraduate'), ('RESEARCH', 'Research'), ('OTHER', 'Other')], max_length=32)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Student degree classification',
                'ordering': ['channel_i_degree_name'],
            },
        ),
        migrations.CreateModel(
            name='StudentLifecycleEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=64)),
                ('reason', models.CharField(blank=True, default='', max_length=64)),
                ('previous_value', models.TextField(blank=True, default='')),
                ('new_value', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Student lifecycle event',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentValidityExtension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_expiry', models.DateField()),
                ('requested_expiry', models.DateField()),
                ('approved_expiry', models.DateField(blank=True, null=True)),
                ('extension_months', models.PositiveSmallIntegerField(default=6)),
                ('reason', models.TextField()),
                ('status', models.CharField(default='SUBMITTED', max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Student validity extension',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserAffiliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('FACULTY', 'Faculty'), ('HEAD_OF_DEPARTMENT', 'Head of Department'), ('LAB', 'Lab'), ('PROJECT', 'Project'), ('DEPARTMENT', 'Department'), ('OTHER', 'Other')], max_length=32)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'User affiliation',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='channelidepartmentmapping',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dept_mappings_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='channelidepartmentmapping',
            name='internal_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='channel_i_mappings', to='users.department'),
        ),
        migrations.AddField(
            model_name='channelidepartmentmapping',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dept_mappings_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='channeliidentityprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='channel_i_identity', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='channeliidentityhistory',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='users.channeliidentityprofile'),
        ),
        migrations.AddField(
            model_name='headofdepartmentassignment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hod_assignments_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='headofdepartmentassignment',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hod_assignments', to='users.department'),
        ),
        migrations.AddField(
            model_name='headofdepartmentassignment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hod_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentdegreeclassification',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='degree_classifications_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentdegreeclassification',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='degree_classifications_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentlifecycleevent',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_lifecycle_events_acted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentlifecycleevent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_lifecycle_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentvalidityextension',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validity_extensions_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentvalidityextension',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='validity_extensions_requested', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentvalidityextension',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='validity_extensions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='useraffiliation',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_affiliations', to='users.department'),
        ),
        migrations.AddField(
            model_name='useraffiliation',
            name='related_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affiliations_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='useraffiliation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='affiliations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='useraffiliation',
            name='wallet_join_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affiliations', to='users.walletjoinrequest'),
        ),
        migrations.AddConstraint(
            model_name='headofdepartmentassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True)), fields=('department',), name='one_active_hod_per_department'),
        ),
        migrations.RunPython(seed_undergraduate_degrees, migrations.RunPython.noop),
    ]
