# Generated by Django 5.x

from django.db import migrations


def clear_verbose_booking_lock_message(apps, schema_editor):
    PortalMigrationState = apps.get_model("users", "PortalMigrationState")
    for state in PortalMigrationState.objects.all():
        msg = (getattr(state, "booking_lock_message", None) or "").strip()
        if not msg:
            continue
        verbose = (
            "New IIC Equipment Booking Portal" in msg
            or msg.count("\n") >= 2
            or len(msg) > 280
        )
        if verbose:
            state.booking_lock_message = ""
            state.save(update_fields=["booking_lock_message"])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0106_department_equipment_booking_and_cutover"),
    ]

    operations = [
        migrations.RunPython(clear_verbose_booking_lock_message, noop_reverse),
    ]
