# Generated by Django 5.2.9 on 2026-10-03 10:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0126_mobiledevicesession'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletDirectRecharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, db_index=True, max_length=32)),
                ('client_request_id', models.CharField(max_length=64, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('mode', models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank transfer'), ('cheque', 'Cheque'), ('dd', 'Demand draft'), ('internal_adjustment', 'Internal adjustment'), ('other', 'Other')], max_length=32)),
                ('reference_number', models.CharField(blank=True, max_length=120)),
                ('transaction_date', models.DateField()),
                ('remarks', models.TextField()),
                ('attachment', models.FileField(blank=True, max_length=255, null=True, upload_to='wallet_direct_recharge/%Y/%m/%d/')),
                ('balance_before', models.DecimalField(decimal_places=2, max_digits=12)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=12)),
                ('performed_as', models.CharField(max_length=24)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('email_to', models.JSONField(blank=True, default=list)),
                ('email_cc', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Direct wallet recharge',
                'verbose_name_plural': 'Direct wallet recharges',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WalletDirectRechargeGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_from', models.DateTimeField()),
                ('valid_until', models.DateTimeField()),
                ('max_amount_per_transaction', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revoke_reason', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Direct wallet recharge grant',
                'verbose_name_plural': 'Direct wallet recharge grants',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WalletModeDepartmentSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_grant', models.CharField(choices=[('inherit', 'Follows master'), ('disabled', 'Disabled')], default='inherit', max_length=16)),
                ('direct_cash', models.CharField(choices=[('inherit', 'Follows master'), ('disabled', 'Disabled')], default='inherit', max_length=16)),
                ('online_gateway', models.CharField(choices=[('inherit', 'Follows master'), ('disabled', 'Disabled')], default='inherit', max_length=16)),
                ('peer_transfer', models.CharField(choices=[('inherit', 'Follows master'), ('disabled', 'Disabled')], default='inherit', max_length=16)),
                ('direct_recharge', models.CharField(choices=[('inherit', 'Follows master'), ('disabled', 'Disabled')], default='inherit', max_length=16)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Wallet payment mode (department)',
                'verbose_name_plural': 'Wallet payment modes (department)',
            },
        ),
        migrations.CreateModel(
            name='WalletModeEmailRecipients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(choices=[('project_grant', 'Recharge via Project Grant'), ('direct_cash', 'Direct Cash Deposit / Bank Transfer'), ('online_gateway', 'Online payment gateway'), ('peer_transfer', 'Transfer within the same department'), ('credit', 'Credit Limit'), ('direct_recharge', 'Direct wallet recharge')], max_length=32)),
                ('to_recipients', models.JSONField(blank=True, default=list)),
                ('cc_recipients', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Wallet payment mode email recipients',
                'verbose_name_plural': 'Wallet payment mode email recipients',
            },
        ),
        migrations.CreateModel(
            name='WalletPaymentModeAuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=64)),
                ('target', models.CharField(blank=True, max_length=120)),
                ('before', models.JSONField(blank=True, default=dict)),
                ('after', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Wallet payment mode audit event',
                'verbose_name_plural': 'Wallet payment mode audit events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WalletPaymentModeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direct_recharge_enabled', models.BooleanField(default=False, help_text='When on, the Main Administrator and currently valid designated persons can add funds directly to a selected wallet.', verbose_name='Allow direct wallet recharge')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Wallet payment mode configuration',
                'verbose_name_plural': 'Wallet payment mode configuration',
            },
        ),
        migrations.AddField(
            model_name='walletdirectrecharge',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='users.department'),
        ),
        migrations.AddField(
            model_name='walletdirectrecharge',
            name='performed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='walletdirectrecharge',
            name='sub_wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='direct_recharges', to='users.subwallet'),
        ),
        migrations.AddField(
            model_name='walletdirectrecharge',
            name='sub_wallet_transaction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='direct_recharge', to='users.subwallettransaction'),
        ),
        migrations.AddField(
            model_name='walletdirectrecharge',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='direct_recharges', to='users.wallet'),
        ),
        migrations.AddField(
            model_name='walletdirectrechargegrant',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Leave empty to allow every department.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wallet_direct_recharge_grants', to='users.department'),
        ),
        migrations.AddField(
            model_name='walletdirectrechargegrant',
            name='granted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='walletdirectrechargegrant',
            name='revoked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='walletdirectrechargegrant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_direct_recharge_grants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='walletdirectrecharge',
            name='grant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recharges', to='users.walletdirectrechargegrant'),
        ),
        migrations.AddField(
            model_name='walletmodedepartmentsetting',
            name='department',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_mode_setting', to='users.department'),
        ),
        migrations.AddField(
            model_name='walletmodedepartmentsetting',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='walletmodeemailrecipients',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wallet_mode_email_recipients', to='users.department'),
        ),
        migrations.AddField(
            model_name='walletmodeemailrecipients',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='walletpaymentmodeauditevent',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='walletpaymentmodeconfig',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='walletdirectrechargegrant',
            index=models.Index(fields=['user', 'valid_until'], name='wallet_drg_user_until_idx'),
        ),
        migrations.AddConstraint(
            model_name='walletmodeemailrecipients',
            constraint=models.UniqueConstraint(condition=models.Q(('department__isnull', False)), fields=('option', 'department'), name='uniq_wallet_mode_recipients_option_dept'),
        ),
        migrations.AddConstraint(
            model_name='walletmodeemailrecipients',
            constraint=models.UniqueConstraint(condition=models.Q(('department__isnull', True)), fields=('option',), name='uniq_wallet_mode_recipients_option_default'),
        ),
    ]
