# Generated by Django 5.2.9 on 2026-10-09 13:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

SCHEDULE_NAME = "Read SRIC wallet recharge emails (every 5 min)"
RECEIVERS = (
    ("IIC-000-002", "IIC", ("IIC",), ("Instrumentation Centre",)),
    ("TINK-000-01", "Tinkering", ("TINK", "TL"), ("Tinkering",)),
)


def _department_for(Department, grant_code, codes, name_hints):
    internal = Department.objects.filter(department_type="internal")
    for qs in (
        internal.filter(internal_grant_code__iexact=grant_code),
        internal.filter(code__in=codes),
        *(internal.filter(name__icontains=hint) for hint in name_hints),
    ):
        if qs.count() == 1:
            return qs.first()
    return None


def seed(apps, schema_editor):
    Department = apps.get_model("users", "Department")
    Mapping = apps.get_model("users", "SricReceiverMapping")
    Settings = apps.get_model("users", "SricWalletRechargeSettings")
    Settings.objects.get_or_create(pk=1)
    for code, label, codes, hints in RECEIVERS:
        if not Mapping.objects.filter(code=code).exists():
            Mapping.objects.create(code=code, label=label, department=_department_for(Department, code, codes, hints))

    IntervalSchedule = apps.get_model("django_celery_beat", "IntervalSchedule")
    PeriodicTask = apps.get_model("django_celery_beat", "PeriodicTask")
    every_5_minutes, _ = IntervalSchedule.objects.get_or_create(every=5, period="minutes")
    if not PeriodicTask.objects.filter(name=SCHEDULE_NAME).exists():
        PeriodicTask.objects.create(
            name=SCHEDULE_NAME,
            task="users.scan_sric_wallet_recharge_mailbox",
            interval=every_5_minutes,
            enabled=True,
        )


def unseed(apps, schema_editor):
    apps.get_model("django_celery_beat", "PeriodicTask").objects.filter(name=SCHEDULE_NAME).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0134_wallet_recharge_delete_reminder_cutoff'),
        ('django_celery_beat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SricReceiverMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=80, unique=True, verbose_name='Receiver Project code')),
                ('label', models.CharField(help_text='As shown in the SRIC portal, e.g. IIC.', max_length=120, verbose_name='Receiver type')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SRIC receiver mapping',
                'verbose_name_plural': 'SRIC receiver mappings',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='SricWalletMailMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder', models.CharField(max_length=120, verbose_name='Folder')),
                ('uid', models.CharField(max_length=32, verbose_name='IMAP UID')),
                ('message_id', models.CharField(blank=True, db_index=True, max_length=500, verbose_name='Message-ID')),
                ('received_at', models.DateTimeField(blank=True, null=True, verbose_name='Email date')),
                ('from_addr', models.CharField(blank=True, max_length=255, verbose_name='From')),
                ('attachment_name', models.CharField(blank=True, max_length=255, verbose_name='Attachment')),
                ('attachment_sha256', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='Attachment SHA-256')),
                ('row_count', models.PositiveIntegerField(default=0, verbose_name='Rows')),
                ('authenticated', models.BooleanField(default=False, verbose_name='Origin verified')),
                ('auth_verdict', models.CharField(blank=True, max_length=500, verbose_name='Origin check')),
                ('status', models.CharField(choices=[('processed', 'Processed'), ('dry_run', 'Dry run (nothing stored)'), ('no_attachment', 'No Wallet_Recharge.csv attachment'), ('parse_error', 'File could not be read'), ('before_cutoff', 'Sent before the cutoff date'), ('duplicate_message', 'Same email already processed'), ('wrong_sender', 'Not from the SRIC sender'), ('error', 'Error')], max_length=32, verbose_name='Status')),
                ('error', models.TextField(blank=True, verbose_name='Error')),
                ('trigger', models.CharField(blank=True, max_length=40, verbose_name='Trigger')),
                ('processed_at', models.DateTimeField(auto_now_add=True, verbose_name='Processed at')),
            ],
            options={
                'verbose_name': 'SRIC wallet recharge email',
                'verbose_name_plural': 'SRIC wallet recharge emails',
                'ordering': ['-processed_at'],
            },
        ),
        migrations.CreateModel(
            name='SricWalletRecharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveIntegerField(default=0, verbose_name='Row in file')),
                ('project_number', models.CharField(blank=True, max_length=120, verbose_name='Project Number')),
                ('pi_name', models.CharField(blank=True, max_length=255, verbose_name='PI Name')),
                ('employee_id', models.CharField(blank=True, max_length=60, verbose_name='Employee ID')),
                ('ledger_id', models.CharField(db_index=True, max_length=80, verbose_name='Ledger ID')),
                ('receiver_code', models.CharField(blank=True, max_length=80, verbose_name='Receiver Project')),
                ('amount_raw', models.CharField(blank=True, max_length=60, verbose_name='Amount as in file')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Amount')),
                ('financial_year', models.CharField(db_index=True, max_length=9, verbose_name='Financial year')),
                ('status', models.CharField(choices=[('credited', 'Credited'), ('awaiting_credit', 'Ready to credit (auto-credit off)'), ('needs_review', 'Needs review'), ('duplicate', 'Duplicate'), ('failed', 'Failed'), ('rejected', 'Rejected')], db_index=True, max_length=20, verbose_name='Status')),
                ('review_reason', models.CharField(blank=True, max_length=40, verbose_name='Review reason')),
                ('review_message', models.TextField(blank=True, verbose_name='Review details')),
                ('origin_verified', models.BooleanField(default=False, verbose_name='Email origin verified')),
                ('credit_key', models.CharField(blank=True, max_length=120, null=True, unique=True, verbose_name='Credit key')),
                ('balance_after', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('credited_at', models.DateTimeField(blank=True, null=True, verbose_name='Credited at')),
                ('confirmation_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Confirmation email sent at')),
                ('fund_receipt_verified', models.BooleanField(db_index=True, default=False, verbose_name='Fund receipt verified')),
                ('fund_receipt_verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Fund receipt verified at')),
                ('fund_receipt_verification_remarks', models.TextField(blank=True, verbose_name='Verification remarks')),
                ('rejected_at', models.DateTimeField(blank=True, null=True, verbose_name='Rejected at')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Rejection reason')),
                ('history', models.JSONField(blank=True, default=list, verbose_name='History')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SRIC wallet recharge',
                'verbose_name_plural': 'SRIC wallet recharges',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SricWalletRechargeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_enabled', models.BooleanField(default=False, help_text='Every 5 minutes (and on Refresh), read new Wallet_Recharge.csv emails from the SRIC portal.', verbose_name='Read SRIC wallet recharge emails')),
                ('auto_credit_enabled', models.BooleanField(default=False, help_text='When on, rows that match a faculty member and a receiver, from an email whose origin is verified, are credited at once. When off, they wait for the Main Administrator to credit them.', verbose_name='Auto-credit SRIC recharges')),
                ('sender_email', models.CharField(default='no-reply@sric.iitr.ac.in', max_length=255, verbose_name='Sender address')),
                ('attachment_name', models.CharField(default='Wallet_Recharge.csv', max_length=255, verbose_name='Attachment name')),
                ('auto_credit_max_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Rows above this amount wait for the Main Administrator. Empty = no limit.', max_digits=12, null=True, verbose_name='Auto-credit only up to (₹ per row)')),
                ('trusted_authserv_ids', models.TextField(blank=True, help_text='authserv-id of our own mail servers whose Authentication-Results header is trusted (SPF / DKIM / DMARC pass for the sender domain). One per line. Empty = not used.', verbose_name='Trusted Authentication-Results servers')),
                ('require_internal_relay', models.BooleanField(default=True, help_text='Without a trusted Authentication-Results pass, the email counts as genuine only if every relay that handled it has a private (campus) address or one of the trusted relay ranges, and the gateway marker matches.', verbose_name='Require delivery through internal mail relays')),
                ('trusted_relay_ranges', models.TextField(blank=True, help_text='Extra public IP ranges (CIDR, one per line) treated as internal relays.', verbose_name='Trusted public relay ranges')),
                ('gateway_marker_header', models.CharField(blank=True, default='mail_from_trusted_domains', help_text='Header the campus mail gateway adds to mail from trusted domains. Empty = not required.', max_length=120, verbose_name='Gateway marker header')),
                ('gateway_marker_value', models.CharField(blank=True, default='true', max_length=120, verbose_name='Gateway marker value')),
                ('confirmation_cc_emails', models.TextField(blank=True, help_text='Optional addresses copied on every credit confirmation sent to the faculty member.', verbose_name='Copy credit confirmations to')),
                ('review_alert_emails', models.TextField(blank=True, help_text='Empty = every active Main Administrator.', verbose_name="Send 'needs review' alerts to")),
                ('last_scan_at', models.DateTimeField(blank=True, null=True, verbose_name='Last scan at')),
                ('last_scan_result', models.JSONField(blank=True, default=dict, verbose_name='Last scan result')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'SRIC wallet recharge settings',
                'verbose_name_plural': 'SRIC wallet recharge settings',
            },
        ),
        migrations.RenameIndex(
            model_name='legacybookingblock',
            new_name='users_legac_new_equ_49a788_idx',
            old_name='users_legac_new_equ_8bidx_idx',
        ),
        migrations.RenameIndex(
            model_name='legacywalletaccountmapping',
            new_name='users_legac_mapping_e53d3c_idx',
            old_name='users_legac_mapping_2d1c4a_idx',
        ),
        migrations.RenameIndex(
            model_name='legacywalletledgerentry',
            new_name='users_legac_employe_6028c1_idx',
            old_name='users_legac_employe_7a91b2_idx',
        ),
        migrations.RenameIndex(
            model_name='legacywalletledgerentry',
            new_name='users_legac_source__320efd_idx',
            old_name='users_legac_source__9c12e3_idx',
        ),
        migrations.RenameIndex(
            model_name='migrationbookingsettlement',
            new_name='users_migra_status_798267_idx',
            old_name='users_migra_status_0c7f1a_idx',
        ),
        migrations.RenameIndex(
            model_name='migrationbookingsettlement',
            new_name='users_migra_legacy__2641f9_idx',
            old_name='users_migra_legacy__b2a1c3_idx',
        ),
        migrations.RenameIndex(
            model_name='migrationnotificationrecipient',
            new_name='users_migra_status_f95f1e_idx',
            old_name='users_migr_status_8c_idx',
        ),
        migrations.RenameIndex(
            model_name='walletpeertransfer',
            new_name='users_walle_sender__bb3502_idx',
            old_name='users_walle_sender__a8c1e1_idx',
        ),
        migrations.RenameIndex(
            model_name='walletpeertransfer',
            new_name='users_walle_recipie_28e1c4_idx',
            old_name='users_walle_recipie_b2f4c2_idx',
        ),
        migrations.RenameIndex(
            model_name='walletpeertransfer',
            new_name='users_walle_status_c1b086_idx',
            old_name='users_walle_status__c3d5e3_idx',
        ),
        migrations.AlterField(
            model_name='department',
            name='enable_student_wallet_recharge',
            field=models.BooleanField(default=False, help_text='Main-administrator switch: when enabled, IITR Students may request a wallet recharge for this department (amount + department → email Accept/Reject). Disabled by default for every department.', verbose_name='IITR student wallet recharge enabled'),
        ),
        migrations.AlterField(
            model_name='portalmigrationstate',
            name='booking_lock_message',
            field=models.TextField(blank=True, default='New IIC Equipment Booking Portal\n\nThe new portal is currently being prepared for launch.\n\nOnline equipment booking will be available from:\n\n    {date}\n    {time}\n\nUntil then, please continue using the existing IIC Booking Portal.\n\nYour wallet migration is being synchronized and your wallet balance and transaction history will remain available.'),
        ),
        migrations.AlterField(
            model_name='portalmigrationstate',
            name='phase',
            field=models.CharField(choices=[('PREPARATION', 'Preparation'), ('PARALLEL_OPERATION', 'Parallel operation'), ('FINANCIAL_FREEZE', 'Financial freeze'), ('FINAL_SYNC', 'Final sync'), ('RECONCILIATION', 'Reconciliation'), ('NEW_PORTAL_ACTIVE', 'New portal active'), ('OLD_PORTAL_READ_ONLY', 'Old portal read-only'), ('OLD_PORTAL_REDIRECT', 'Old portal redirect'), ('ARCHIVED', 'Archived'), ('MIGRATION_INTERRUPTED', 'Migration interrupted')], default='PREPARATION', max_length=32),
        ),
        migrations.AlterField(
            model_name='walletrechargerequest',
            name='account_incharge',
            field=models.ForeignKey(blank=True, help_text='Department Account In-charge notified for this request. This role monitors and manages department financial activities including wallet recharges, grant utilization, wallet transactions, credit facility usage, and related department financial records.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_recharge_requests_as_incharge', to=settings.AUTH_USER_MODEL, verbose_name='Department Account In-charge'),
        ),
        migrations.AlterField(
            model_name='walletsricsettings',
            name='recipient_emails',
            field=models.TextField(blank=True, help_text='One address per line, or comma/semicolon separated. Used when a faculty member sends a Project Grant wallet recharge request to the SRIC Office.', verbose_name='SRIC Office email addresses'),
        ),
        migrations.AddField(
            model_name='sricreceivermapping',
            name='department',
            field=models.ForeignKey(blank=True, limit_choices_to={'department_type': 'internal'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sric_receiver_mappings', to='users.department', verbose_name='Department sub-wallet'),
        ),
        migrations.AddField(
            model_name='sricreceivermapping',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='sricwalletmailmessage',
            constraint=models.UniqueConstraint(fields=('folder', 'uid'), name='unique_sric_wallet_mail_folder_uid'),
        ),
        migrations.AddField(
            model_name='sricwalletrecharge',
            name='credited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sricwalletrecharge',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sric_wallet_recharges', to='users.department'),
        ),
        migrations.AddField(
            model_name='sricwalletrecharge',
            name='duplicate_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='users.sricwalletrecharge'),
        ),
        migrations.AddField(
            model_name='sricwalletrecharge',
            name='fund_receipt_verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sricwalletrecharge',
            name='matched_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sric_wallet_recharges', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sricwalletrecharge',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rows', to='users.sricwalletmailmessage'),
        ),
        migrations.AddField(
            model_name='sricwalletrecharge',
            name='receiver_mapping',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='users.sricreceivermapping'),
        ),
        migrations.AddField(
            model_name='sricwalletrecharge',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sricwalletrecharge',
            name='sub_wallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sric_recharges', to='users.subwallet'),
        ),
        migrations.AddField(
            model_name='sricwalletrecharge',
            name='wallet_transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sric_wallet_recharge', to='users.subwallettransaction'),
        ),
        migrations.AddField(
            model_name='sricwalletrechargesettings',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='sricwalletrecharge',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'duplicate'), _negated=True), fields=('ledger_id', 'financial_year'), name='unique_sric_wallet_recharge_ledger_fy'),
        ),
        migrations.RunPython(seed, unseed),
    ]
