# Generated by Django 5.2.9 on 2026-10-09 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0135_sric_wallet_recharge'),
    ]

    operations = [
        migrations.AddField(
            model_name='sricwalletmailmessage',
            name='is_test',
            field=models.BooleanField(default=False, verbose_name='Test email'),
        ),
        migrations.AddField(
            model_name='sricwalletrecharge',
            name='is_test',
            field=models.BooleanField(default=False, verbose_name='Test row'),
        ),
    ]
