# Generated by Django 5.2.9 on 2026-10-09 14:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0136_sric_wallet_recharge_is_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='sricwalletrecharge',
            name='reversal_ref',
            field=models.CharField(blank=True, help_text='Wallet ledger adjustment that debited this credit back.', max_length=40, verbose_name='Reversal reference'),
        ),
        migrations.AddField(
            model_name='sricwalletrecharge',
            name='reversed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Credit reversed at'),
        ),
        migrations.AddField(
            model_name='sricwalletrecharge',
            name='reversed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
