# Generated by Django 5.2.9 on 2026-10-09 16:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0137_sric_wallet_recharge_reversal'),
    ]

    operations = [
        migrations.AddField(
            model_name='sricwalletrechargesettings',
            name='quiet_window_enabled',
            field=models.BooleanField(default=True, help_text='The 5-minute check and the faculty Refresh do not read the mailbox in this weekly window (IST). The first check after it reads everything that arrived meanwhile. Main Administrator Refresh still works.', verbose_name='Pause mailbox checks during peak booking time'),
        ),
        migrations.AddField(
            model_name='sricwalletrechargesettings',
            name='quiet_window_end',
            field=models.TimeField(default=datetime.time(21, 15), verbose_name='Resume at (IST)'),
        ),
        migrations.AddField(
            model_name='sricwalletrechargesettings',
            name='quiet_window_start',
            field=models.TimeField(default=datetime.time(20, 55), verbose_name='Pause from (IST)'),
        ),
        migrations.AddField(
            model_name='sricwalletrechargesettings',
            name='quiet_window_weekday',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], default=2, help_text='Day of the week (IST).', verbose_name='Pause on'),
        ),
    ]
