# Generated by Django 5.2.9 on 2025-12-28 19:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('equipment_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name of the equipment', max_length=255)),
                ('code', models.CharField(help_text='Code of the equipment', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of the equipment', null=True)),
                ('status', models.CharField(blank=True, choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('MAINTENANCE', 'Maintenance'), ('REPAIR', 'Repair'), ('DISPOSED', 'Disposed'), ('OTHER', 'Other')], help_text='Status of the equipment', max_length=255, null=True)),
                ('location', models.TextField(blank=True, help_text='Location of the equipment', null=True)),
                ('s3_path', models.CharField(blank=True, help_text='S3 path of the equipment image', max_length=255, null=True)),
                ('banner_text', models.TextField(blank=True, help_text='Banner text of the equipment', null=True)),
                ('banner_color', models.CharField(blank=True, choices=[('RED', 'Red'), ('GREEN', 'Green'), ('BLUE', 'Blue'), ('YELLOW', 'Yellow'), ('ORANGE', 'Orange'), ('PURPLE', 'Purple'), ('PINK', 'Pink'), ('BROWN', 'Brown')], help_text='Banner color of the equipment', max_length=255, null=True)),
                ('specifications', models.JSONField(blank=True, default=dict, help_text='Specifications of the equipment', null=True)),
                ('accessories', models.JSONField(blank=True, default=dict, help_text='Accessories of the equipment', null=True)),
                ('additional_accessories', models.JSONField(blank=True, default=dict, help_text='Additional accessories of the equipment', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time the equipment was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time the equipment was updated')),
                ('manager', models.ForeignKey(blank=True, help_text='Manager of the equipment', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equipment_manager', to=settings.AUTH_USER_MODEL)),
                ('operator', models.ForeignKey(blank=True, help_text='Operator of the equipment', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equipment_operator', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Equipment',
                'verbose_name_plural': 'Equipment',
                'ordering': ['name'],
            },
        ),
    ]
