# Generated by Django 5.2.9 on 2025-12-28 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentGroup',
            fields=[
                ('equipment_group_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name of the equipment group', max_length=255)),
                ('code', models.CharField(help_text='Code of the equipment group', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of the equipment group', null=True)),
                ('internal_weekly_limit', models.IntegerField(help_text='Weekly booking limit in minutes for internal users')),
                ('internal_monthly_limit', models.IntegerField(help_text='Monthly booking limit in minutes for internal users')),
                ('open_date_internal', models.DateField(blank=True, default=dict, help_text='Open date interval for internal users', null=True)),
                ('close_date_internal', models.DateField(blank=True, default=dict, help_text='Close date interval for internal users', null=True)),
                ('external_quota_percent', models.IntegerField(help_text='Percentage of slots reserved for external users')),
                ('external_weekly_limit', models.IntegerField(help_text='Weekly booking limit in minutes for external users')),
                ('external_monthly_limit', models.IntegerField(help_text='Monthly booking limit in minutes for external users')),
                ('open_date_external', models.DateField(blank=True, default=dict, help_text='Open date interval for external users', null=True)),
                ('close_date_external', models.DateField(blank=True, default=dict, help_text='Close date interval for external users', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time the equipment group was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time the equipment group was updated')),
            ],
            options={
                'verbose_name': 'Equipment Group',
                'verbose_name_plural': 'Equipment Groups',
                'ordering': ['name'],
            },
        ),
    ]
