# Generated by Django 5.2.9 on 2025-12-30 11:50

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_equipmentgroup'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date of this slot')),
                ('start_datetime', models.DateTimeField(help_text='Start datetime of this slot')),
                ('end_datetime', models.DateTimeField(help_text='End datetime of this slot')),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('BOOKED', 'Booked'), ('BLOCKED', 'Blocked')], default='AVAILABLE', help_text='Availability status of this slot', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Daily Slot',
                'verbose_name_plural': 'Daily Slots',
                'ordering': ['date', 'start_datetime'],
            },
        ),
        migrations.CreateModel(
            name='ChargeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(help_text='User type this profile applies to', max_length=50)),
                ('profile_type', models.CharField(choices=[('SAMPLE', 'Sample-based'), ('HOUR', 'Hour-based'), ('SAMPLE_ELEMENT', 'Sample + Element'), ('MULTI_PARAM', 'Multi-parameter')], help_text='Type of charge profile', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this profile is active')),
                ('primary_unit_charge', models.DecimalField(decimal_places=2, help_text='Primary unit charge amount', max_digits=10)),
                ('secondary_unit_charge', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Secondary unit charge amount', max_digits=10)),
                ('breakpoint', models.DecimalField(blank=True, decimal_places=2, help_text='Breakpoint value for tiered pricing', max_digits=10, null=True)),
                ('time_formula', models.CharField(blank=True, help_text='Formula for time calculation (e.g., "(A * C) + B")', max_length=500, null=True)),
                ('secondary_flat_charge', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='Optional secondary flat charge (for HOUR type)', max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('equipment', models.ForeignKey(help_text='Equipment this profile applies to', on_delete=django.db.models.deletion.CASCADE, related_name='charge_profiles', to='equipment.equipment')),
            ],
            options={
                'verbose_name': 'Charge Profile',
                'verbose_name_plural': 'Charge Profiles',
                'ordering': ['equipment', 'user_type'],
                'unique_together': {('equipment', 'user_type', 'profile_type')},
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_type_snapshot', models.CharField(help_text='User type at time of booking (snapshot)', max_length=50)),
                ('total_time_minutes', models.IntegerField(help_text='Total booking time in minutes')),
                ('total_charge', models.DecimalField(decimal_places=2, help_text='Total charge for this booking', max_digits=10)),
                ('input_values', models.JSONField(default=dict, help_text='Dynamic input field values (A-G)')),
                ('selected_parameters', models.JSONField(blank=True, default=list, help_text='Selected parameter codes (for MULTI_PARAM)', null=True)),
                ('charge_breakdown', models.JSONField(default=list, help_text='Line-by-line charge breakdown for audit')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('ABSENT', 'Absent'), ('REFUNDED', 'Refunded')], default='PENDING', help_text='Booking status', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Additional notes for this booking', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('equipment', models.ForeignKey(help_text='Equipment being booked', on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='equipment.equipment')),
                ('user', models.ForeignKey(help_text='User who made the booking', on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('charge_profile', models.ForeignKey(help_text='Charge profile used (snapshot)', on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='equipment.chargeprofile')),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookingSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(help_text='Booking this slot belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='booking_slots', to='equipment.booking')),
                ('daily_slot', models.ForeignKey(help_text='Daily slot allocated to this booking', on_delete=django.db.models.deletion.PROTECT, related_name='booking_slots', to='equipment.dailyslot')),
            ],
            options={
                'verbose_name': 'Booking Slot',
                'verbose_name_plural': 'Booking Slots',
            },
        ),
        migrations.CreateModel(
            name='DynamicInputField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_key', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G')], help_text='Field key (A-G)', max_length=1)),
                ('field_label', models.CharField(help_text='Label for this field', max_length=255)),
                ('field_type', models.CharField(choices=[('NUMERIC', 'Numeric'), ('TEXT', 'Text'), ('RADIO', 'Radio'), ('COMBO', 'Combo/Dropdown'), ('MULTI_SELECT', 'Multi-select')], help_text='Type of input field', max_length=20)),
                ('is_required', models.BooleanField(default=False, help_text='Whether this field is required')),
                ('default_value', models.CharField(blank=True, help_text='Default value for this field', max_length=500, null=True)),
                ('options', models.JSONField(blank=True, default=list, help_text='Options for radio/combo/multi-select fields', null=True)),
                ('help_text', models.TextField(blank=True, help_text='Help text for this field', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('charge_profile', models.ForeignKey(help_text='Charge profile this field belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='input_fields', to='equipment.chargeprofile')),
            ],
            options={
                'verbose_name': 'Dynamic Input Field',
                'verbose_name_plural': 'Dynamic Input Fields',
                'ordering': ['charge_profile', 'field_key'],
            },
        ),
        migrations.CreateModel(
            name='ExternalUserQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quota_type', models.CharField(choices=[('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly')], help_text='Type of quota (weekly/monthly)', max_length=20)),
                ('limit_type', models.CharField(choices=[('HOURS', 'Total Hours'), ('BOOKINGS', 'Number of Bookings'), ('CHARGE', 'Total Charge Amount')], help_text='What this quota limits', max_length=20)),
                ('limit_value', models.DecimalField(decimal_places=2, help_text='Quota limit value', max_digits=10)),
                ('is_paid', models.BooleanField(default=False, help_text='Whether this is a paid quota')),
                ('is_enforced', models.BooleanField(default=True, help_text='Whether this quota is enforced')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('equipment', models.ForeignKey(help_text='Equipment this quota applies to', on_delete=django.db.models.deletion.CASCADE, related_name='external_user_quotas', to='equipment.equipment')),
            ],
            options={
                'verbose_name': 'External User Quota',
                'verbose_name_plural': 'External User Quotas',
                'ordering': ['equipment', 'quota_type'],
            },
        ),
        migrations.CreateModel(
            name='HolidayCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holiday_name', models.CharField(help_text='Name of the holiday', max_length=255)),
                ('start_date', models.DateField(help_text='Start date of holiday')),
                ('end_date', models.DateField(help_text='End date of holiday')),
                ('holiday_type', models.CharField(choices=[('FULL', 'Full Holiday'), ('PARTIAL', 'Partial Holiday')], default='FULL', help_text='Type of holiday', max_length=20)),
                ('open_time', models.TimeField(blank=True, help_text='Open time (for partial holidays)', null=True)),
                ('close_time', models.TimeField(blank=True, help_text='Close time (for partial holidays)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('equipment', models.ForeignKey(blank=True, help_text='Equipment this holiday applies to (null = global)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='equipment.equipment')),
            ],
            options={
                'verbose_name': 'Holiday Calendar',
                'verbose_name_plural': 'Holiday Calendar',
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='MultiParamDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('param_name', models.CharField(help_text='Name of the parameter', max_length=255)),
                ('param_code', models.CharField(help_text='Code/identifier for the parameter', max_length=50)),
                ('unit_time_minutes', models.IntegerField(help_text='Unit time in minutes for this parameter')),
                ('unit_charge', models.DecimalField(decimal_places=2, help_text='Unit charge for this parameter', max_digits=10)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this parameter is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('charge_profile', models.ForeignKey(help_text='Charge profile this parameter belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='param_definitions', to='equipment.chargeprofile')),
            ],
            options={
                'verbose_name': 'Multi-Parameter Definition',
                'verbose_name_plural': 'Multi-Parameter Definitions',
                'ordering': ['charge_profile', 'param_name'],
            },
        ),
        migrations.CreateModel(
            name='OperatingHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], help_text='Day of week (0=Monday, 6=Sunday)')),
                ('is_closed', models.BooleanField(default=False, help_text='Whether equipment is closed on this day')),
                ('open_time', models.TimeField(blank=True, help_text='Opening time (required if not closed)', null=True)),
                ('close_time', models.TimeField(blank=True, help_text='Closing time (required if not closed)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('equipment', models.ForeignKey(help_text='Equipment these hours apply to', on_delete=django.db.models.deletion.CASCADE, related_name='operating_hours', to='equipment.equipment')),
            ],
            options={
                'verbose_name': 'Operating Hours',
                'verbose_name_plural': 'Operating Hours',
                'ordering': ['equipment', 'day_of_week'],
            },
        ),
        migrations.CreateModel(
            name='SlotMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_name', models.CharField(blank=True, help_text='Optional name for this slot', max_length=100, null=True)),
                ('start_time', models.TimeField(help_text='Slot start time')),
                ('end_time', models.TimeField(help_text='Slot end time')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this slot is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('equipment', models.ForeignKey(help_text='Equipment this slot belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='slot_masters', to='equipment.equipment')),
            ],
            options={
                'verbose_name': 'Slot Master',
                'verbose_name_plural': 'Slot Masters',
                'ordering': ['equipment', 'start_time'],
            },
        ),
        migrations.AddField(
            model_name='dailyslot',
            name='slot_master',
            field=models.ForeignKey(help_text='Slot master this daily slot references', on_delete=django.db.models.deletion.CASCADE, related_name='daily_slots', to='equipment.slotmaster'),
        ),
        migrations.CreateModel(
            name='SlotSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_duration_minutes', models.IntegerField(help_text='Duration of each slot in minutes')),
                ('slots_per_day', models.IntegerField(help_text='Number of slots per day (template value)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('equipment', models.OneToOneField(help_text='Equipment these slot settings apply to', on_delete=django.db.models.deletion.CASCADE, related_name='slot_settings', to='equipment.equipment')),
            ],
            options={
                'verbose_name': 'Slot Settings',
                'verbose_name_plural': 'Slot Settings',
            },
        ),
        migrations.CreateModel(
            name='UserTypeQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(help_text='User type this quota applies to', max_length=50)),
                ('quota_type', models.CharField(choices=[('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly')], help_text='Type of quota (weekly/monthly)', max_length=20)),
                ('limit_type', models.CharField(choices=[('HOURS', 'Total Hours'), ('BOOKINGS', 'Number of Bookings'), ('CHARGE', 'Total Charge Amount')], help_text='What this quota limits', max_length=20)),
                ('limit_value', models.DecimalField(decimal_places=2, help_text='Quota limit value', max_digits=10)),
                ('is_enforced', models.BooleanField(default=True, help_text='Whether this quota is enforced')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('equipment', models.ForeignKey(help_text='Equipment this quota applies to', on_delete=django.db.models.deletion.CASCADE, related_name='user_type_quotas', to='equipment.equipment')),
            ],
            options={
                'verbose_name': 'User Type Quota',
                'verbose_name_plural': 'User Type Quotas',
                'ordering': ['equipment', 'user_type'],
            },
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['user', 'status'], name='equipment_b_user_id_37c0ab_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['equipment', 'status'], name='equipment_b_equipme_7b9561_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status', 'created_at'], name='equipment_b_status_e68b66_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bookingslot',
            unique_together={('booking', 'daily_slot')},
        ),
        migrations.AlterUniqueTogether(
            name='dynamicinputfield',
            unique_together={('charge_profile', 'field_key')},
        ),
        migrations.AlterUniqueTogether(
            name='externaluserquota',
            unique_together={('equipment', 'quota_type', 'limit_type')},
        ),
        migrations.AlterUniqueTogether(
            name='operatinghours',
            unique_together={('equipment', 'day_of_week')},
        ),
        migrations.AddIndex(
            model_name='dailyslot',
            index=models.Index(fields=['date', 'status'], name='equipment_d_date_daa883_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyslot',
            index=models.Index(fields=['slot_master', 'date'], name='equipment_d_slot_ma_424ecf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dailyslot',
            unique_together={('slot_master', 'date', 'start_datetime')},
        ),
        migrations.AlterUniqueTogether(
            name='usertypequota',
            unique_together={('equipment', 'user_type', 'quota_type', 'limit_type')},
        ),
    ]
