# Generated by Django 5.2.9 on 2026-01-02 15:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0003_dailyslot_chargeprofile_booking_bookingslot_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentAccessory',
            fields=[
                ('equipment_accessory_id', models.AutoField(primary_key=True, serialize=False)),
                ('accessory_name', models.CharField(help_text='Name of the accessory', max_length=255)),
                ('accessory_description', models.TextField(blank=True, help_text='Description of the accessory', null=True)),
                ('is_optional', models.BooleanField(default=False, help_text='Whether this accessory is optional')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time the equipment accessory was created')),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentAdditionalAccessory',
            fields=[
                ('equipment_additional_accessory_id', models.AutoField(primary_key=True, serialize=False)),
                ('additional_accessory_name', models.CharField(help_text='Name of the additional accessory', max_length=255)),
                ('additional_accessory_description', models.TextField(blank=True, help_text='Description of the additional accessory', null=True)),
                ('is_optional', models.BooleanField(default=False, help_text='Whether this additional accessory is optional')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time the equipment additional accessory was created')),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentManager',
            fields=[
                ('equipment_manager_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time the equipment manager was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time the equipment manager was updated')),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentOperator',
            fields=[
                ('equipment_operator_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time the equipment operator was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time the equipment operator was updated')),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentSpecification',
            fields=[
                ('equipment_specification_id', models.AutoField(primary_key=True, serialize=False)),
                ('spec_key', models.CharField(help_text='Key of the specification', max_length=255)),
                ('spec_value', models.TextField(help_text='Value of the specification')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time the equipment specification was created')),
            ],
        ),
        migrations.RemoveField(
            model_name='booking',
            name='charge_profile',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='equipment',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='bookingslot',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='bookingslot',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='bookingslot',
            name='daily_slot',
        ),
        migrations.AlterUniqueTogether(
            name='dailyslot',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='dailyslot',
            name='slot_master',
        ),
        migrations.DeleteModel(
            name='EquipmentGroup',
        ),
        migrations.AlterUniqueTogether(
            name='externaluserquota',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='externaluserquota',
            name='equipment',
        ),
        migrations.RemoveField(
            model_name='holidaycalendar',
            name='equipment',
        ),
        migrations.AlterUniqueTogether(
            name='operatinghours',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='operatinghours',
            name='equipment',
        ),
        migrations.RemoveField(
            model_name='slotmaster',
            name='equipment',
        ),
        migrations.RemoveField(
            model_name='slotsettings',
            name='equipment',
        ),
        migrations.AlterUniqueTogether(
            name='usertypequota',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='usertypequota',
            name='equipment',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='accessories',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='additional_accessories',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='banner_color',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='banner_text',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='operator',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='specifications',
        ),
        migrations.AddField(
            model_name='equipment',
            name='slot_duration_minutes',
            field=models.IntegerField(default=30, help_text='Duration of the slot in minutes'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='slots_per_day',
            field=models.IntegerField(default=12, help_text='Number of slots per day'),
        ),
        migrations.AlterField(
            model_name='dynamicinputfield',
            name='field_key',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J'), ('K', 'K'), ('L', 'L'), ('M', 'M'), ('N', 'N'), ('O', 'O'), ('P', 'P'), ('Q', 'Q'), ('R', 'R'), ('S', 'S'), ('T', 'T'), ('U', 'U'), ('V', 'V'), ('W', 'W'), ('X', 'X'), ('Y', 'Y'), ('Z', 'Z')], help_text='Field key (A-G)', max_length=1),
        ),
        migrations.AddField(
            model_name='equipmentaccessory',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_accessories', to='equipment.equipment'),
        ),
        migrations.AddField(
            model_name='equipmentadditionalaccessory',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_additional_accessories', to='equipment.equipment'),
        ),
        migrations.AddField(
            model_name='equipmentmanager',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_managers', to='equipment.equipment'),
        ),
        migrations.AddField(
            model_name='equipmentmanager',
            name='manager',
            field=models.ForeignKey(help_text='Manager of the equipment', limit_choices_to={'user_type': 'manager'}, on_delete=django.db.models.deletion.PROTECT, related_name='equipment_manager', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='equipmentoperator',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_operators', to='equipment.equipment'),
        ),
        migrations.AddField(
            model_name='equipmentoperator',
            name='operator',
            field=models.ForeignKey(help_text='Operator of the equipment', limit_choices_to={'user_type': 'operator'}, on_delete=django.db.models.deletion.PROTECT, related_name='equipment_operator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='equipmentspecification',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_specifications', to='equipment.equipment'),
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='BookingSlot',
        ),
        migrations.DeleteModel(
            name='DailySlot',
        ),
        migrations.DeleteModel(
            name='ExternalUserQuota',
        ),
        migrations.DeleteModel(
            name='HolidayCalendar',
        ),
        migrations.DeleteModel(
            name='OperatingHours',
        ),
        migrations.DeleteModel(
            name='SlotMaster',
        ),
        migrations.DeleteModel(
            name='SlotSettings',
        ),
        migrations.DeleteModel(
            name='UserTypeQuota',
        ),
    ]
