# Generated by Django 5.2.9 on 2026-01-02 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0004_equipmentaccessory_equipmentadditionalaccessory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='slot_duration_minutes',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='slots_per_day',
        ),
        migrations.RemoveField(
            model_name='equipmentaccessory',
            name='accessory_description',
        ),
        migrations.AddField(
            model_name='chargeprofile',
            name='external_monthly_quota',
            field=models.IntegerField(default=10, help_text='External monthly quota'),
        ),
        migrations.AddField(
            model_name='chargeprofile',
            name='external_weekly_quota',
            field=models.IntegerField(default=10, help_text='External weekly quota'),
        ),
        migrations.AddField(
            model_name='chargeprofile',
            name='internal_monthly_quota',
            field=models.IntegerField(default=10, help_text='Internal monthly quota'),
        ),
        migrations.AddField(
            model_name='chargeprofile',
            name='internal_weekly_quota',
            field=models.IntegerField(default=10, help_text='Internal weekly quota'),
        ),
        migrations.AddField(
            model_name='chargeprofile',
            name='slot_duration_minutes',
            field=models.IntegerField(default=30, help_text='Duration of the slot in minutes'),
        ),
        migrations.AddField(
            model_name='chargeprofile',
            name='slots_per_day',
            field=models.IntegerField(default=12, help_text='Number of slots per day'),
        ),
        migrations.AlterField(
            model_name='dynamicinputfield',
            name='field_type',
            field=models.CharField(choices=[('NUMERIC', 'Numeric'), ('TEXT', 'Text'), ('RADIO', 'Radio'), ('COMBO', 'Combo/Dropdown'), ('MULTI_SELECT', 'Multi-select'), ('TOGGLE', 'Toggle')], help_text='Type of input field', max_length=20),
        ),
        migrations.CreateModel(
            name='SlotMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_name', models.CharField(blank=True, help_text='Optional name for this slot', max_length=100, null=True)),
                ('slot_number', models.IntegerField(help_text='Slot number (1, 2, 3, etc.)')),
                ('open_time', models.TimeField(help_text='Slot open/start time')),
                ('close_time', models.TimeField(help_text='Slot close/end time')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this slot is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('charge_profile', models.ForeignKey(help_text='Charge profile this slot belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='slot_masters', to='equipment.chargeprofile')),
            ],
            options={
                'verbose_name': 'Slot Master',
                'verbose_name_plural': 'Slot Masters',
                'ordering': ['charge_profile', 'slot_number'],
                'unique_together': {('charge_profile', 'slot_number')},
            },
        ),
        migrations.CreateModel(
            name='DailySlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date of this slot')),
                ('start_datetime', models.DateTimeField(help_text='Start datetime of this slot')),
                ('end_datetime', models.DateTimeField(help_text='End datetime of this slot')),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('BOOKED', 'Booked'), ('BLOCKED', 'Blocked')], default='AVAILABLE', help_text='Availability status of this slot', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slot_master', models.ForeignKey(help_text='Slot master this daily slot references', on_delete=django.db.models.deletion.CASCADE, related_name='daily_slots', to='equipment.slotmaster')),
            ],
            options={
                'verbose_name': 'Daily Slot',
                'verbose_name_plural': 'Daily Slots',
                'ordering': ['date', 'start_datetime'],
                'indexes': [models.Index(fields=['date', 'status'], name='equipment_d_date_daa883_idx'), models.Index(fields=['slot_master', 'date'], name='equipment_d_slot_ma_424ecf_idx')],
                'unique_together': {('slot_master', 'date')},
            },
        ),
    ]
