# Generated by Django 5.2.9 on 2026-01-02 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0005_remove_equipment_slot_duration_minutes_and_more'),
    ]

    operations = [
        # First, add all new fields
        migrations.AddField(
            model_name='equipment',
            name='external_monthly_quota',
            field=models.IntegerField(default=10, help_text='External monthly quota'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='external_weekly_quota',
            field=models.IntegerField(default=10, help_text='External weekly quota'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='internal_monthly_quota',
            field=models.IntegerField(default=10, help_text='Internal monthly quota'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='internal_weekly_quota',
            field=models.IntegerField(default=10, help_text='Internal weekly quota'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='profile_type',
            field=models.CharField(blank=True, choices=[('SAMPLE', 'Sample-based'), ('HOUR', 'Hour-based'), ('SAMPLE_ELEMENT', 'Sample + Element'), ('MULTI_PARAM', 'Multi-parameter')], help_text='Type of equipment profile', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='slot_duration_minutes',
            field=models.IntegerField(default=30, help_text='Duration of the slot in minutes'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='slots_per_day',
            field=models.IntegerField(default=12, help_text='Number of slots per day'),
        ),
        migrations.AddField(
            model_name='dynamicinputfield',
            name='equipment',
            field=models.ForeignKey(blank=True, help_text='Equipment this field belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='input_fields', to='equipment.equipment'),
        ),
        migrations.AddField(
            model_name='multiparamdefinition',
            name='equipment',
            field=models.ForeignKey(blank=True, help_text='Equipment this parameter belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='param_definitions', to='equipment.equipment'),
        ),
        migrations.AddField(
            model_name='multiparamdefinition',
            name='user_type',
            field=models.CharField(blank=True, help_text='User type this parameter applies to', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='slotmaster',
            name='equipment',
            field=models.ForeignKey(blank=True, help_text='Equipment this slot belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slot_masters', to='equipment.equipment'),
        ),
        # Then, alter unique_together constraints (after fields are added)
        migrations.AlterUniqueTogether(
            name='chargeprofile',
            unique_together={('equipment', 'user_type')},
        ),
        migrations.AlterUniqueTogether(
            name='dynamicinputfield',
            unique_together={('equipment', 'field_key')},
        ),
        migrations.AlterUniqueTogether(
            name='slotmaster',
            unique_together={('equipment', 'slot_number')},
        ),
        # Then, update model options (after fields are added)
        migrations.AlterModelOptions(
            name='dynamicinputfield',
            options={'ordering': ['equipment', 'field_key'], 'verbose_name': 'Dynamic Input Field', 'verbose_name_plural': 'Dynamic Input Fields'},
        ),
        migrations.AlterModelOptions(
            name='multiparamdefinition',
            options={'ordering': ['equipment', 'param_name'], 'verbose_name': 'Multi-Parameter Definition', 'verbose_name_plural': 'Multi-Parameter Definitions'},
        ),
        migrations.AlterModelOptions(
            name='slotmaster',
            options={'ordering': ['equipment', 'slot_number'], 'verbose_name': 'Slot Master', 'verbose_name_plural': 'Slot Masters'},
        ),
        # Finally, remove old fields
        migrations.RemoveField(
            model_name='multiparamdefinition',
            name='charge_profile',
        ),
        migrations.RemoveField(
            model_name='chargeprofile',
            name='external_monthly_quota',
        ),
        migrations.RemoveField(
            model_name='chargeprofile',
            name='external_weekly_quota',
        ),
        migrations.RemoveField(
            model_name='chargeprofile',
            name='internal_monthly_quota',
        ),
        migrations.RemoveField(
            model_name='chargeprofile',
            name='internal_weekly_quota',
        ),
        migrations.RemoveField(
            model_name='chargeprofile',
            name='profile_type',
        ),
        migrations.RemoveField(
            model_name='chargeprofile',
            name='slot_duration_minutes',
        ),
        migrations.RemoveField(
            model_name='chargeprofile',
            name='slots_per_day',
        ),
        migrations.RemoveField(
            model_name='dynamicinputfield',
            name='charge_profile',
        ),
        migrations.RemoveField(
            model_name='slotmaster',
            name='charge_profile',
        ),
        migrations.DeleteModel(
            name='DailySlot',
        ),
    ]
