# Generated by Django 5.2.9 on 2026-01-04 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0006_alter_dynamicinputfield_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='multiparamdefinition',
            options={'ordering': ['equipment', 'user_type', 'param_name'], 'verbose_name': 'Slot Option Configuration', 'verbose_name_plural': 'Slot Options Configuration'},
        ),
        migrations.RemoveField(
            model_name='chargeprofile',
            name='secondary_flat_charge',
        ),
        migrations.AlterField(
            model_name='multiparamdefinition',
            name='equipment',
            field=models.ForeignKey(blank=True, help_text='Equipment this slot option belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='param_definitions', to='equipment.equipment'),
        ),
        migrations.AlterField(
            model_name='multiparamdefinition',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this slot option is active'),
        ),
        migrations.AlterField(
            model_name='multiparamdefinition',
            name='param_code',
            field=models.CharField(help_text='Code/identifier for the slot option (used in radio field)', max_length=50),
        ),
        migrations.AlterField(
            model_name='multiparamdefinition',
            name='param_name',
            field=models.CharField(help_text='Name of the slot option (e.g., "Slot 1", "Slot 2", "Morning Slot")', max_length=255),
        ),
        migrations.AlterField(
            model_name='multiparamdefinition',
            name='unit_charge',
            field=models.DecimalField(decimal_places=2, help_text='Charge per sample for this slot option', max_digits=10),
        ),
        migrations.AlterField(
            model_name='multiparamdefinition',
            name='unit_time_minutes',
            field=models.IntegerField(help_text='Time in minutes per sample for this slot option'),
        ),
        migrations.AlterField(
            model_name='multiparamdefinition',
            name='user_type',
            field=models.CharField(blank=True, help_text='User type this slot option applies to', max_length=50, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='multiparamdefinition',
            unique_together={('equipment', 'user_type', 'param_code')},
        ),
    ]
