# Generated by Django 5.2.9 on 2026-01-06 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0007_alter_multiparamdefinition_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date of this slot')),
                ('start_datetime', models.DateTimeField(help_text='Start datetime of this slot')),
                ('end_datetime', models.DateTimeField(help_text='End datetime of this slot')),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('BOOKED', 'Booked'), ('BLOCKED', 'Blocked')], default='AVAILABLE', help_text='Availability status of this slot', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slot_master', models.ForeignKey(help_text='Slot master this daily slot references', on_delete=django.db.models.deletion.CASCADE, related_name='daily_slots', to='equipment.slotmaster')),
            ],
            options={
                'verbose_name': 'Daily Slot',
                'verbose_name_plural': 'Daily Slots',
                'ordering': ['date', 'start_datetime'],
                'indexes': [models.Index(fields=['date', 'status'], name='equipment_d_date_daa883_idx'), models.Index(fields=['slot_master', 'date'], name='equipment_d_slot_ma_424ecf_idx')],
                'unique_together': {('slot_master', 'date')},
            },
        ),
    ]
