# Generated by Django 5.2.9 on 2026-01-06 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0008_dailyslot'),
    ]

    operations = [
        # Note: booking field addition moved to migration 0010
        # after Booking model is created to avoid circular dependency
    ]
