# Generated by Django 5.2.9 on 2026-01-08 18:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0009_add_booking_to_dailyslot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalUserQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quota_type', models.CharField(choices=[('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly')], help_text='Type of quota (weekly/monthly)', max_length=20)),
                ('limit_type', models.CharField(choices=[('HOURS', 'Total Hours'), ('BOOKINGS', 'Number of Bookings'), ('CHARGE', 'Total Charge Amount')], help_text='What this quota limits', max_length=20)),
                ('limit_value', models.DecimalField(decimal_places=2, help_text='Quota limit value', max_digits=10)),
                ('is_paid', models.BooleanField(default=False, help_text='Whether this is a paid quota')),
                ('is_enforced', models.BooleanField(default=True, help_text='Whether this quota is enforced')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('equipment', models.ForeignKey(help_text='Equipment this quota applies to', on_delete=django.db.models.deletion.CASCADE, related_name='external_user_quotas', to='equipment.equipment')),
            ],
            options={
                'verbose_name': 'External User Quota',
                'verbose_name_plural': 'External User Quotas',
                'ordering': ['equipment', 'quota_type'],
            },
        ),
        migrations.CreateModel(
            name='UserTypeQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(help_text='User type this quota applies to', max_length=50)),
                ('quota_type', models.CharField(choices=[('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly')], help_text='Type of quota (weekly/monthly)', max_length=20)),
                ('limit_type', models.CharField(choices=[('HOURS', 'Total Hours'), ('BOOKINGS', 'Number of Bookings'), ('CHARGE', 'Total Charge Amount')], help_text='What this quota limits', max_length=20)),
                ('limit_value', models.DecimalField(decimal_places=2, help_text='Quota limit value', max_digits=10)),
                ('is_enforced', models.BooleanField(default=True, help_text='Whether this quota is enforced')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('equipment', models.ForeignKey(help_text='Equipment this quota applies to', on_delete=django.db.models.deletion.CASCADE, related_name='user_type_quotas', to='equipment.equipment')),
            ],
            options={
                'verbose_name': 'User Type Quota',
                'verbose_name_plural': 'User Type Quotas',
                'ordering': ['equipment', 'user_type'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_type_snapshot', models.CharField(help_text='User type at time of booking (snapshot)', max_length=50)),
                ('total_time_minutes', models.IntegerField(help_text='Total booking time in minutes')),
                ('total_charge', models.DecimalField(decimal_places=2, help_text='Total charge for this booking', max_digits=10)),
                ('input_values', models.JSONField(default=dict, help_text='Dynamic input field values (A-G)')),
                ('selected_parameters', models.JSONField(blank=True, default=list, help_text='Selected parameter codes (for MULTI_PARAM)', null=True)),
                ('charge_breakdown', models.JSONField(default=list, help_text='Line-by-line charge breakdown for audit')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('ABSENT', 'Absent'), ('REFUNDED', 'Refunded')], default='PENDING', help_text='Booking status', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Additional notes for this booking', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('charge_profile', models.ForeignKey(help_text='Charge profile used (snapshot)', on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='equipment.chargeprofile')),
                ('equipment', models.ForeignKey(help_text='Equipment being booked', on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='equipment.equipment')),
                ('user', models.ForeignKey(help_text='User who made the booking', on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='equipment_b_user_id_37c0ab_idx'), models.Index(fields=['equipment', 'status'], name='equipment_b_equipme_7b9561_idx'), models.Index(fields=['status', 'created_at'], name='equipment_b_status_e68b66_idx')],
            },
        ),
        # Add booking field to DailySlot after Booking model is created
        migrations.AddField(
            model_name='dailyslot',
            name='booking',
            field=models.ForeignKey(
                blank=True,
                help_text='Booking associated with this slot',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='daily_slots',
                to='equipment.booking'
            ),
        ),
    ]
