# Generated by Django 5.2.9 on 2026-01-15 16:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0010_externaluserquota_usertypequota_booking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingEvent',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('CREATED', 'Created'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled'), ('RESCHEDULED', 'Rescheduled'), ('COMPLETED', 'Completed'), ('REFUNDED', 'Refunded'), ('ABSENT', 'Absent'), ('COMMENT', 'Comment'), ('STATUS_CHANGED', 'Status Changed')], help_text='Type of event', max_length=20)),
                ('previous_status', models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('ABSENT', 'Absent'), ('REFUNDED', 'Refunded')], help_text='Previous booking status (if status changed)', max_length=20, null=True)),
                ('new_status', models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('ABSENT', 'Absent'), ('REFUNDED', 'Refunded')], help_text='New booking status (if status changed)', max_length=20, null=True)),
                ('comment', models.TextField(blank=True, help_text='Comment or description for this event', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata (e.g., refund amount, new times, etc.)')),
                ('notification_sent', models.BooleanField(default=False, help_text='Whether notification was sent for this event')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(help_text='Booking this event belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='events', to='equipment.booking')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this event', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_events_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Booking Event',
                'verbose_name_plural': 'Booking Events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['booking', 'created_at'], name='equipment_b_booking_de8c43_idx'), models.Index(fields=['event_type', 'created_at'], name='equipment_b_event_t_880453_idx')],
            },
        ),
    ]
