# Generated by Django 5.2.9 on 2026-01-17 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0013_add_video_file_to_equipment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Holiday date', unique=True, verbose_name='Date')),
                ('reason', models.CharField(blank=True, help_text='Reason for the holiday', max_length=255, null=True, verbose_name='Reason')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this holiday is active', verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Holiday',
                'verbose_name_plural': 'Holidays',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['date', 'is_active'], name='equipment_h_date_df119b_idx')],
            },
        ),
    ]
