# Generated by Django 5.2.9 on 2026-02-03 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0014_holiday'),
        ('users', '0024_add_user_group_and_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='visibility_group',
            field=models.ForeignKey(blank=True, help_text='If set, only members of this group can see this equipment. Leave empty for public visibility.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment', to='users.usergroup', verbose_name='Visibility Group'),
        ),
    ]
