# Generated by Django 5.2.9

from django.db import migrations, models
import django.db.models.deletion


def migrate_department_to_category(apps, schema_editor):
    """Create EquipmentCategory from existing equipment departments and assign to equipment."""
    Equipment = apps.get_model('equipment', 'Equipment')
    EquipmentCategory = apps.get_model('equipment', 'EquipmentCategory')
    try:
        Department = apps.get_model('users', 'Department')
    except LookupError:
        return
    # Build mapping: department_id -> EquipmentCategory
    dept_to_category = {}
    for eq in Equipment.objects.filter(department_id__isnull=False).select_related('department'):
        if not eq.department_id or eq.department_id in dept_to_category:
            if eq.department_id:
                eq.category_id = dept_to_category[eq.department_id].pk
                eq.save(update_fields=['category_id'])
            continue
        dept = eq.department
        code = (dept.code and dept.code.strip()) or f"CAT-{dept.id}"
        cat, _ = EquipmentCategory.objects.get_or_create(
            code=code,
            defaults={'name': dept.name or code, 'description': getattr(dept, 'description', None) or ''}
        )
        dept_to_category[eq.department_id] = cat
        eq.category_id = cat.pk
        eq.save(update_fields=['category_id'])
    # Handle any equipment we missed (same department)
    for eq in Equipment.objects.filter(department_id__isnull=False):
        if eq.department_id in dept_to_category and not eq.category_id:
            eq.category_id = dept_to_category[eq.department_id].pk
            eq.save(update_fields=['category_id'])


def noop_reverse(apps, schema_editor):
    """No reverse migration for data."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0015_add_equipment_visibility_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the equipment category', max_length=255, verbose_name='Category Name')),
                ('code', models.CharField(blank=True, help_text='Short code for the category', max_length=100, null=True, unique=True, verbose_name='Category Code')),
                ('description', models.TextField(blank=True, help_text='Optional description of the category', null=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Equipment Category',
                'verbose_name_plural': 'Equipment Categories',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='equipment',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Category this equipment belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment', to='equipment.equipmentcategory', verbose_name='Category'),
        ),
        migrations.RunPython(migrate_department_to_category, noop_reverse),
        migrations.RemoveField(
            model_name='equipment',
            name='department',
        ),
    ]
