# Generated by Django 5.2.9 on 2026-02-08 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0016_equipment_category'),
        ('users', '0025_remove_equipment_department_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='internal_department',
            field=models.ForeignKey(blank=True, help_text='Internal department this equipment is mapped to', limit_choices_to={'department_type': 'internal'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment', to='users.department', verbose_name='Internal Department'),
        ),
    ]
