# Generated by Django 5.2.9 on 2026-02-08 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0017_add_internal_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('BOOKED', 'Booked'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('ABSENT', 'Absent'), ('REFUNDED', 'Refunded')], default='PENDING', help_text='Booking status', max_length=20),
        ),
        migrations.AlterField(
            model_name='bookingevent',
            name='new_status',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('BOOKED', 'Booked'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('ABSENT', 'Absent'), ('REFUNDED', 'Refunded')], help_text='New booking status (if status changed)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='bookingevent',
            name='previous_status',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('BOOKED', 'Booked'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('ABSENT', 'Absent'), ('REFUNDED', 'Refunded')], help_text='Previous booking status (if status changed)', max_length=20, null=True),
        ),
    ]
