# Generated by Django 5.2.9 on 2026-02-12 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0018_alter_booking_status_alter_bookingevent_new_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='reschedule_hours_threshold',
            field=models.IntegerField(default=48, help_text='Hours before booking start time when reschedule option becomes unavailable (default: 48)', verbose_name='Reschedule Hours Threshold'),
        ),
    ]
