# Generated by Django 5.2.9 on 2026-02-12 08:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0019_equipment_reschedule_hours_threshold'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingCancellationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING', help_text='Status of the cancellation request', max_length=20, verbose_name='Status')),
                ('notes', models.TextField(blank=True, help_text='Reason for cancellation', null=True, verbose_name='Cancellation Notes')),
                ('response_message', models.TextField(blank=True, help_text='Response message from admin', null=True, verbose_name='Response Message')),
                ('approved_by_email', models.EmailField(blank=True, help_text='Email of the admin who approved/rejected', max_length=254, null=True, verbose_name='Approved By Email')),
                ('requested_at', models.DateTimeField(auto_now_add=True, help_text='When the cancellation request was created', verbose_name='Requested At')),
                ('responded_at', models.DateTimeField(blank=True, help_text='When the cancellation request was approved/rejected', null=True, verbose_name='Responded At')),
                ('booking', models.ForeignKey(help_text='Booking to be cancelled', on_delete=django.db.models.deletion.CASCADE, related_name='cancellation_requests', to='equipment.booking', verbose_name='Booking')),
                ('user', models.ForeignKey(help_text='User requesting cancellation', on_delete=django.db.models.deletion.CASCADE, related_name='booking_cancellation_requests', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Booking Cancellation Request',
                'verbose_name_plural': 'Booking Cancellation Requests',
                'ordering': ['-requested_at'],
                'indexes': [models.Index(fields=['booking', 'status'], name='equipment_b_booking_728c4f_idx'), models.Index(fields=['user', 'status'], name='equipment_b_user_id_0f2ef8_idx'), models.Index(fields=['status', 'requested_at'], name='equipment_b_status_f3a162_idx')],
            },
        ),
    ]
