# Generated by Django - add important_instruction to Equipment

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0030_ensure_editing_required_column"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipment",
            name="important_instruction",
            field=models.TextField(blank=True, help_text="Important instructions shown prominently on the equipment page (above specifications).", null=True, verbose_name="Important Instruction"),
        ),
    ]
