# Generated by Django 5.2.9 on 2026-03-08 07:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def _safe_rename_indexes(apps, schema_editor):
    renames = (
        ("equipment_b_virtual_7a0b0d_idx", "equipment_b_virtual_535cdd_idx"),
        ("equipment_b_booking_7a1b2c_idx", "equipment_b_booking_ee2220_idx"),
        ("equip_waitlist_equip_created_idx", "equipment_w_equipme_f6710a_idx"),
    )
    with schema_editor.connection.cursor() as cursor:
        for old_name, new_name in renames:
            cursor.execute(
                "SELECT 1 FROM pg_indexes WHERE indexname = %s",
                [old_name],
            )
            if cursor.fetchone():
                cursor.execute(
                    'ALTER INDEX "%s" RENAME TO "%s"' % (old_name, new_name)
                )
                continue
            cursor.execute(
                "SELECT 1 FROM pg_indexes WHERE indexname = %s",
                [new_name],
            )
            if cursor.fetchone():
                continue


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0073_equipment_max_urgent_requests'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookingattemptlog',
            options={'ordering': ['-requested_at'], 'verbose_name': 'Booking request log entry', 'verbose_name_plural': 'Booking requests log'},
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(_safe_rename_indexes, migrations.RunPython.noop),
            ],
            state_operations=[
                migrations.RenameIndex(
                    model_name='booking',
                    new_name='equipment_b_virtual_535cdd_idx',
                    old_name='equipment_b_virtual_7a0b0d_idx',
                ),
                migrations.RenameIndex(
                    model_name='bookingsampletrace',
                    new_name='equipment_b_booking_ee2220_idx',
                    old_name='equipment_b_booking_7a1b2c_idx',
                ),
                migrations.RenameIndex(
                    model_name='waitlistentry',
                    new_name='equipment_w_equipme_f6710a_idx',
                    old_name='equip_waitlist_equip_created_idx',
                ),
            ],
        ),
        migrations.AlterField(
            model_name='bookingevent',
            name='event_type',
            field=models.CharField(choices=[('CREATED', 'Created'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled'), ('RESCHEDULED', 'Rescheduled'), ('COMPLETED', 'Completed'), ('REFUNDED', 'Refunded'), ('ABSENT', 'Operator Unavailable'), ('COMMENT', 'Comment'), ('STATUS_CHANGED', 'Status Changed'), ('CHARGE_RECALCULATED', 'Charge Recalculated'), ('REPEAT_SAMPLE_OFFERED', 'Repeat sample offered'), ('REPEAT_SAMPLE_CREATED', 'Repeat sample booking created')], help_text='Type of event', max_length=32),
        ),
        migrations.AlterField(
            model_name='bookingsampletrace',
            name='reason',
            field=models.TextField(blank=True, default='', help_text='Mandatory for Sample Rejected and Held at Office', verbose_name='Reason'),
        ),
        migrations.AlterField(
            model_name='bookingsampletrace',
            name='status',
            field=models.CharField(choices=[('SAMPLE_SENT', 'Sample Sent'), ('HELD_AT_OFFICE', 'Held at Office'), ('FORWARDED_TO_LAB', 'Forwarded to Lab'), ('SAMPLE_ACCEPTED', 'Sample Accepted'), ('SAMPLE_REJECTED', 'Sample Rejected'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed')], max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='dailyslot',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('BOOKED', 'Booked'), ('BLOCKED', 'Blocked'), ('UNDER_MAINTENANCE', 'Under Maintenance'), ('OPERATOR_ABSENT', 'Operator Absent'), ('BOOKING_NOT_UTILIZED', 'Booking Not Utilized')], default='AVAILABLE', help_text='Availability status of this slot', max_length=20),
        ),
        migrations.AlterField(
            model_name='dynamicinputfield',
            name='field_type',
            field=models.CharField(choices=[('NUMERIC', 'Numeric'), ('TEXT', 'Text'), ('RADIO', 'Radio'), ('COMBO', 'Combo/Dropdown'), ('MULTI_SELECT', 'Multi-select'), ('TOGGLE', 'Toggle'), ('PERIODIC_TABLE', 'Periodic table / Element selector'), ('TABLE', 'Table')], help_text='Type of input field', max_length=20),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='enable_charge_recalculation',
            field=models.BooleanField(default=False, help_text='When checked, the user can edit any input field on a confirmed (BOOKED) booking before completion, regardless of "editing required" status. On save, charges are recalculated; if the new charge is higher than the amount already deducted, the difference is debited from the wallet; if lower, the difference is credited. An email notification is sent to the user.', verbose_name='Enable charge recalculation'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='weekly_view_display',
            field=models.CharField(choices=[('TIME', 'Show time'), ('SLOT_ID', 'Hide time')], default='TIME', help_text='Weekly view vertical axis: Show time = time on axis; Hide time = time hidden (display only). Only admin and OIC can change this.', max_length=20, verbose_name='Weekly view display'),
        ),
        migrations.AlterField(
            model_name='urgentbookingrequest',
            name='wallet_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='urgent_requests_wallet_approved', to=settings.AUTH_USER_MODEL, verbose_name='Approved by Supervisor'),
        ),
        migrations.AlterField(
            model_name='urgentholdexpiryconfig',
            name='hold_expiry_hours',
            field=models.PositiveIntegerField(default=24, help_text='Deprecated: use urgent_booking_validity_days. Kept for DB backward compatibility.', verbose_name='Hold expiry (hours)'),
        ),
        migrations.AlterField(
            model_name='urgentholdexpiryconfig',
            name='urgent_booking_validity_days',
            field=models.PositiveIntegerField(blank=True, default=1, help_text='Urgent request is valid for this many days from request creation. After this period, PENDING requests are auto-expired (hold released, slots freed). Admin and OIC can set this.', null=True, verbose_name='Urgent booking validity (days)'),
        ),
    ]
