# Generated by Django 5.2.9 on 2026-03-10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0076_coupon_assignment_balance"),
        ("users", "0053_alter_authsettings_inactivity_timeout_seconds_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EquipmentUserGroup",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("purpose", models.CharField(choices=[("BOOKING_REQUESTERS", "Booking Requesters")], default="BOOKING_REQUESTERS", max_length=50, verbose_name="Purpose")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("equipment", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="user_groups", to="equipment.equipment", verbose_name="Equipment")),
                ("user_group", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="equipment_links", to="users.usergroup", verbose_name="User Group")),
            ],
            options={
                "verbose_name": "Equipment user group",
                "verbose_name_plural": "Equipment user groups",
                "unique_together": {("equipment", "purpose")},
            },
        ),
        migrations.AddIndex(
            model_name="equipmentusergroup",
            index=models.Index(fields=["equipment", "purpose"], name="equipment_equipm_7f1db2_idx"),
        ),
    ]

