# Generated by Django 5.2.9 on 2026-03-10 15:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0078_dailyslot_reserved_for_external'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. 2024-25 Odd, 2024-25 Even', max_length=100, verbose_name='Semester Name')),
                ('code', models.CharField(help_text='Short code e.g. 2024-25-Odd', max_length=50, unique=True, verbose_name='Semester Code')),
                ('start_date', models.DateField(help_text='Semester start date', verbose_name='Start Date')),
                ('end_date', models.DateField(help_text='Semester end date', verbose_name='End Date')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this semester is currently active for nominations', verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Semester',
                'verbose_name_plural': 'Semesters',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='StudentEquipmentNomination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20, verbose_name='Status')),
                ('remarks', models.TextField(blank=True, help_text='Optional remarks from supervisor or approver', null=True, verbose_name='Remarks')),
                ('nominated_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Student equipment operating nomination',
                'verbose_name_plural': 'Student equipment operating nominations',
                'ordering': ['-nominated_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='equipmentusergroup',
            new_name='equipment_e_equipme_a72b94_idx',
            old_name='equipment_equipm_7f1db2_idx',
        ),
        migrations.AddField(
            model_name='studentequipmentnomination',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='Admin or OIC who approved/rejected', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_nominations_approved', to=settings.AUTH_USER_MODEL, verbose_name='Approved by'),
        ),
        migrations.AddField(
            model_name='studentequipmentnomination',
            name='equipment',
            field=models.ForeignKey(help_text='Equipment the student is nominated to operate', on_delete=django.db.models.deletion.CASCADE, related_name='student_operating_nominations', to='equipment.equipment', verbose_name='Equipment'),
        ),
        migrations.AddField(
            model_name='studentequipmentnomination',
            name='semester',
            field=models.ForeignKey(help_text='Semester for which the nomination applies', on_delete=django.db.models.deletion.CASCADE, related_name='nominations', to='equipment.semester', verbose_name='Semester'),
        ),
        migrations.AddField(
            model_name='studentequipmentnomination',
            name='student',
            field=models.ForeignKey(help_text='Student nominated to operate the equipment', limit_choices_to={'user_type__in': ['student', 'individual_student']}, on_delete=django.db.models.deletion.CASCADE, related_name='equipment_operating_nominations', to=settings.AUTH_USER_MODEL, verbose_name='Student'),
        ),
        migrations.AddField(
            model_name='studentequipmentnomination',
            name='supervisor',
            field=models.ForeignKey(help_text='Faculty supervisor who nominated the student', limit_choices_to={'user_type': 'faculty'}, on_delete=django.db.models.deletion.CASCADE, related_name='equipment_nominations_given', to=settings.AUTH_USER_MODEL, verbose_name='Supervisor'),
        ),
        migrations.AddConstraint(
            model_name='studentequipmentnomination',
            constraint=models.UniqueConstraint(fields=('student', 'equipment', 'semester'), name='equipment_student_equipment_nomination_student_equipment_semester_uniq'),
        ),
    ]
