# Generated by Django 5.2.9 on 2026-03-10 16:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0079_add_semester_and_student_equipment_nomination'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentOperatingTACall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_operators_required', models.PositiveIntegerField(help_text='Number of TA operators needed for this equipment', verbose_name='Number of operators required')),
                ('eligibility_criteria', models.TextField(blank=True, help_text='Eligibility criteria for nominees', verbose_name='Eligibility criteria')),
                ('expected_duty_hours', models.TextField(blank=True, help_text='Expected duty hours for the TA role', verbose_name='Expected duty hours')),
                ('benefits', models.TextField(blank=True, help_text='Benefits (e.g. certificate, instrument usage coupons)', verbose_name='Benefits')),
                ('nomination_deadline', models.DateField(help_text='Deadline by which faculty must submit nominations', verbose_name='Nomination deadline')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email_sent_at', models.DateTimeField(blank=True, help_text='When the call email was sent to all faculty', null=True, verbose_name='Email sent at')),
                ('created_by', models.ForeignKey(blank=True, help_text='OIC or Admin who initiated the call', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ta_nomination_calls_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('equipment', models.ForeignKey(help_text='Equipment for which TA operators are sought', on_delete=django.db.models.deletion.CASCADE, related_name='ta_nomination_calls', to='equipment.equipment', verbose_name='Equipment')),
                ('semester', models.ForeignKey(help_text='Semester for which the call applies', on_delete=django.db.models.deletion.CASCADE, related_name='ta_nomination_calls', to='equipment.semester', verbose_name='Semester')),
            ],
            options={
                'verbose_name': 'TA operating nomination call',
                'verbose_name_plural': 'TA operating nomination calls',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='studentequipmentnomination',
            name='ta_call',
            field=models.ForeignKey(blank=True, help_text='The TA nomination call this nomination responds to (if any)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nominations', to='equipment.equipmentoperatingtacall', verbose_name='TA call'),
        ),
    ]
