# Generated by Django 5.2.9 on 2026-03-17 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0084_proformainvoiceformat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='weekly_view_time_from',
            field=models.TimeField(blank=True, help_text='Slot window start (24h). Only slots with start time at or after this time are shown and bookable. Leave empty for no limit.', null=True, verbose_name='Slot window time from'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='weekly_view_time_to',
            field=models.TimeField(blank=True, help_text='Slot window end (24h). Only slots with end time at or before this time are shown and bookable. Leave empty for no limit.', null=True, verbose_name='Slot window time to'),
        ),
    ]
