# Generated by Django 5.2.9 on 2026-03-19 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0085_alter_equipment_weekly_view_time_from_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="rating_removed",
            field=models.BooleanField(
                default=False,
                help_text="If True, this booking rating has been removed by admin/OIC and is excluded from equipment aggregates and user-visible lists.",
                verbose_name="Rating removed",
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="rating_removed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the rating was removed by admin/OIC.",
                null=True,
                verbose_name="Rating removed at",
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="rating_removed_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Admin/OIC user who removed this rating.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="booking_ratings_removed",
                to="users.user",
                verbose_name="Rating removed by",
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="rating_removed_reason",
            field=models.TextField(
                blank=True,
                help_text="Optional reason recorded when the rating is removed.",
                null=True,
                verbose_name="Rating removed reason",
            ),
        ),
    ]

