# Generated by Django 5.2.9 on 2026-03-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0086_booking_rating_moderation_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="ICPMSStandardSample",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("s_no", models.CharField(max_length=50, verbose_name="S.NO.")),
                ("part_no", models.CharField(blank=True, default="", max_length=100, verbose_name="Part No.")),
                ("name_of_std", models.CharField(max_length=255, verbose_name="Name of Std")),
                ("list_of_elements", models.TextField(blank=True, default="", verbose_name="List of Element")),
                ("concentration", models.CharField(blank=True, default="", max_length=100, verbose_name="Concentration")),
                ("status", models.PositiveSmallIntegerField(default=1, verbose_name="Status")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "ICPMS Standard Sample",
                "verbose_name_plural": "ICPMS Standard Sample Database",
                "ordering": ["id"],
                "db_table": "icpms_standard_sample_database",
            },
        ),
    ]

