# Generated by Django 5.2.9 on 2026-03-23 11:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0095_equipment_image_local_storage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chargeprofile',
            options={'ordering': ['equipment', 'user_type', 'pricing_profile'], 'verbose_name': 'Charge Profile', 'verbose_name_plural': 'Charge Profiles'},
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('WAITLISTED', 'Waitlisted'), ('BOOKED', 'Booked'), ('HOLD', 'Hold'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('ABSENT', 'Operator Unavailable'), ('REFUNDED', 'Refunded'), ('BOOKING_NOT_UTILIZED', 'Booking Not Utilized')], default='PENDING', help_text='Booking status', max_length=30),
        ),
        migrations.AlterField(
            model_name='bookingevent',
            name='event_type',
            field=models.CharField(choices=[('CREATED', 'Created'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled'), ('RESCHEDULED', 'Rescheduled'), ('COMPLETED', 'Completed'), ('REFUNDED', 'Refunded'), ('ABSENT', 'Operator Unavailable'), ('COMMENT', 'Comment'), ('STATUS_CHANGED', 'Status Changed'), ('CHARGE_RECALCULATED', 'Charge Recalculated'), ('REPEAT_SAMPLE_OFFERED', 'Repeat Sample Request Approved'), ('REPEAT_SAMPLE_CREATED', 'Repeat Sample Booking Confirmed')], help_text='Type of event', max_length=32),
        ),
        migrations.AlterField(
            model_name='bookingevent',
            name='new_status',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('WAITLISTED', 'Waitlisted'), ('BOOKED', 'Booked'), ('HOLD', 'Hold'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('ABSENT', 'Operator Unavailable'), ('REFUNDED', 'Refunded'), ('BOOKING_NOT_UTILIZED', 'Booking Not Utilized')], help_text='New booking status (if status changed)', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='bookingevent',
            name='previous_status',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('WAITLISTED', 'Waitlisted'), ('BOOKED', 'Booked'), ('HOLD', 'Hold'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('ABSENT', 'Operator Unavailable'), ('REFUNDED', 'Refunded'), ('BOOKING_NOT_UTILIZED', 'Booking Not Utilized')], help_text='Previous booking status (if status changed)', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='dynamicinputfield',
            name='help_text',
            field=models.TextField(blank=True, help_text='Help text for this field (e.g. list of standards for ICPMS Standard Coverage)', null=True),
        ),
        migrations.AlterField(
            model_name='icpmsstandardsample',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userdiscountedchargeequipment',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounted_charge_users', to='equipment.equipment', verbose_name='Equipment'),
        ),
        migrations.AlterField(
            model_name='userdiscountedchargeequipment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userdiscountedchargeequipment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounted_charge_equipment', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
