# Generated by Django 5.2.9 on 2026-03-23 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0097_ta_rewards'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='tadutylog',
            new_name='equipment_t_student_517df8_idx',
            old_name='equipment_ta_student_876138_idx',
        ),
        migrations.RenameIndex(
            model_name='tadutylog',
            new_name='equipment_t_equipme_93f56e_idx',
            old_name='equipment_ta_equipme_0bb670_idx',
        ),
        migrations.RenameIndex(
            model_name='tadutylog',
            new_name='equipment_t_booking_6e5016_idx',
            old_name='equipment_ta_booking_9f65d9_idx',
        ),
        migrations.RenameIndex(
            model_name='tarewardledger',
            new_name='equipment_t_student_53fe69_idx',
            old_name='equipment_ta_student_427f46_idx',
        ),
        migrations.RenameIndex(
            model_name='tarewardledger',
            new_name='equipment_t_student_d660c3_idx',
            old_name='equipment_ta_student_197ac0_idx',
        ),
        migrations.RenameIndex(
            model_name='tarewardledger',
            new_name='equipment_t_source__470203_idx',
            old_name='equipment_ta_source__a4d21a_idx',
        ),
    ]
