# Generated by Django 5.2.9 on 2026-03-23 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0098_remove_coupons'),
        ('equipment', '0098_rename_equipment_ta_student_876138_idx_equipment_t_student_517df8_idx_and_more'),
    ]

    operations = [
    ]
