# Generated by Django 5.2.9 on 2026-03-24 03:38

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0100_tarewardconfig_per_equipment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentoperatingtacall',
            name='benefits',
            field=models.TextField(blank=True, help_text='Benefits (e.g. certificate, TA recognition, reward points)', verbose_name='Benefits'),
        ),
        migrations.CreateModel(
            name='TAAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ALLOCATED', 'Allocated'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined'), ('CANCELLED', 'Cancelled')], default='ALLOCATED', max_length=20, verbose_name='Status')),
                ('allocation_notes', models.TextField(blank=True, null=True, verbose_name='Allocation notes')),
                ('expected_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Expected duty hours')),
                ('allocated_at', models.DateTimeField(auto_now_add=True, verbose_name='Allocated at')),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='Responded at')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allocated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ta_assignments_allocated', to=settings.AUTH_USER_MODEL, verbose_name='Allocated by')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ta_assignments', to='equipment.booking', verbose_name='Booking')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ta_assignments', to='equipment.equipment', verbose_name='Equipment')),
                ('nomination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ta_assignments', to='equipment.studentequipmentnomination', verbose_name='Approved TA nomination')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ta_assignments', to='equipment.semester', verbose_name='Semester/Academic cycle')),
                ('ta_student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ta_assignments', to=settings.AUTH_USER_MODEL, verbose_name='TA student')),
            ],
            options={
                'verbose_name': 'TA assignment',
                'verbose_name_plural': 'TA assignments',
                'ordering': ['-allocated_at'],
                'indexes': [models.Index(fields=['ta_student', 'status', 'allocated_at'], name='equipment_t_ta_stud_e49548_idx'), models.Index(fields=['booking', 'status'], name='equipment_t_booking_e00ef3_idx'), models.Index(fields=['equipment', 'allocated_at'], name='equipment_t_equipme_156479_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['ALLOCATED', 'ACCEPTED'])), fields=('booking', 'ta_student'), name='ta_assignment_unique_active_booking_student')],
            },
        ),
    ]
