# Generated by Django 5.2.9 on 2026-03-24 03:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0101_alter_equipmentoperatingtacall_benefits_taassignment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tadutylog',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duty_logs', to='equipment.taassignment', verbose_name='Related TA assignment'),
        ),
        migrations.AddConstraint(
            model_name='tadutylog',
            constraint=models.UniqueConstraint(condition=models.Q(('assignment__isnull', False)), fields=('assignment',), name='ta_duty_unique_assignment'),
        ),
    ]
