# Generated by Django 5.2.9 on 2026-03-24 09:00

import decimal
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0102_tadutylog_assignment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_code', models.CharField(max_length=100, unique=True, verbose_name='Item code')),
                ('name', models.CharField(max_length=255, verbose_name='Item name')),
                ('category', models.CharField(choices=[('CONSUMABLE', 'Consumable'), ('NON_CONSUMABLE', 'Non-consumable')], max_length=20, verbose_name='Category')),
                ('uom', models.CharField(max_length=50, verbose_name='Unit of measure')),
                ('specification', models.TextField(blank=True, default='', verbose_name='Specification')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Inventory item',
                'verbose_name_plural': 'Inventory items',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['category', 'active'], name='equipment_i_categor_cbd3f2_idx')],
            },
        ),
        migrations.CreateModel(
            name='InventoryRequest',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('request_no', models.CharField(blank=True, editable=False, max_length=100, unique=True, verbose_name='Request number')),
                ('request_type', models.CharField(choices=[('CONSUMABLE', 'Consumable'), ('NON_CONSUMABLE', 'Non-consumable'), ('MIXED', 'Mixed')], default='MIXED', max_length=20, verbose_name='Request type')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('PARTIALLY_FULFILLED', 'Partially fulfilled'), ('FULFILLED', 'Fulfilled'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=30, verbose_name='Status')),
                ('justification', models.TextField(blank=True, default='', verbose_name='Justification')),
                ('required_by_date', models.DateField(blank=True, null=True, verbose_name='Required by date')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Submitted at')),
                ('decision_at', models.DateTimeField(blank=True, null=True, verbose_name='Decision at')),
                ('decision_note', models.TextField(blank=True, default='', verbose_name='Decision note')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('decision_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_requests_decided', to=settings.AUTH_USER_MODEL, verbose_name='Decision by')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_requests', to='equipment.equipment', verbose_name='Equipment')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_requests_raised', to=settings.AUTH_USER_MODEL, verbose_name='Requested by')),
            ],
            options={
                'verbose_name': 'Inventory request',
                'verbose_name_plural': 'Inventory requests',
                'ordering': ['-created_at'],
                'indexes': [
                    models.Index(fields=['equipment', 'status', 'created_at'], name='equipment_i_equipme_4f95cf_idx'),
                    models.Index(fields=['requested_by', 'status', 'created_at'], name='equipment_i_request_9b2cf8_idx'),
                ],
            },
        ),
        migrations.CreateModel(
            name='EquipmentInventoryItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('min_level', models.DecimalField(decimal_places=3, default=decimal.Decimal('0.000'), max_digits=12)),
                ('max_level', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('reorder_level', models.DecimalField(decimal_places=3, default=decimal.Decimal('0.000'), max_digits=12)),
                ('critical_level', models.DecimalField(decimal_places=3, default=decimal.Decimal('0.000'), max_digits=12)),
                ('default_store_location', models.CharField(blank=True, default='', max_length=255)),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='equipment.equipment', verbose_name='Equipment')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipment_mappings', to='equipment.inventoryitem', verbose_name='Item')),
            ],
            options={
                'verbose_name': 'Equipment inventory item',
                'verbose_name_plural': 'Equipment inventory items',
                'indexes': [
                    models.Index(fields=['equipment', 'is_enabled'], name='equipment_i_equipme_9e18c4_idx'),
                    models.Index(fields=['item', 'is_enabled'], name='equipment_i_item_id_d4933c_idx'),
                ],
                'unique_together': {('equipment', 'item')},
            },
        ),
        migrations.CreateModel(
            name='EquipmentItemStock',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('current_qty', models.DecimalField(decimal_places=3, default=decimal.Decimal('0.000'), max_digits=14)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_stock_balances', to='equipment.equipment', verbose_name='Equipment')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_balances', to='equipment.inventoryitem', verbose_name='Item')),
            ],
            options={
                'verbose_name': 'Equipment item stock',
                'verbose_name_plural': 'Equipment item stocks',
                'indexes': [
                    models.Index(fields=['equipment', 'item'], name='equipment_i_equipme_f41441_idx'),
                    models.Index(fields=['item', 'current_qty'], name='equipment_i_item_id_6d3950_idx'),
                ],
                'unique_together': {('equipment', 'item')},
            },
        ),
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('tx_type', models.CharField(choices=[('RECEIPT', 'Receipt'), ('ISSUE', 'Issue'), ('RETURN', 'Return'), ('ADJUSTMENT', 'Adjustment'), ('TRANSFER_IN', 'Transfer in'), ('TRANSFER_OUT', 'Transfer out'), ('SCRAP', 'Scrap')], max_length=20, verbose_name='Transaction type')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Quantity')),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Unit cost')),
                ('batch_no', models.CharField(blank=True, default='', max_length=100, verbose_name='Batch number')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Expiry date')),
                ('reference_type', models.CharField(blank=True, default='', max_length=50, verbose_name='Reference type')),
                ('reference_id', models.CharField(blank=True, default='', max_length=100, verbose_name='Reference ID')),
                ('performed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Performed at')),
                ('remarks', models.TextField(blank=True, default='', verbose_name='Remarks')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_transactions', to='equipment.equipment', verbose_name='Equipment')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_transactions', to='equipment.inventoryitem', verbose_name='Item')),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_transactions_performed', to=settings.AUTH_USER_MODEL, verbose_name='Performed by')),
            ],
            options={
                'verbose_name': 'Inventory transaction',
                'verbose_name_plural': 'Inventory transactions',
                'ordering': ['-performed_at', '-transaction_id'],
                'indexes': [
                    models.Index(fields=['equipment', 'item', 'performed_at'], name='equipment_i_equipme_0f9b81_idx'),
                    models.Index(fields=['tx_type', 'performed_at'], name='equipment_i_tx_type_3745ca_idx'),
                    models.Index(fields=['reference_type', 'reference_id'], name='equipment_i_referen_98f42c_idx'),
                ],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='inv_tx_quantity_gt_0')],
            },
        ),
        migrations.CreateModel(
            name='IssuedAsset',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('serial_no', models.CharField(blank=True, default='', max_length=255, verbose_name='Serial number')),
                ('issued_on', models.DateField(default=django.utils.timezone.now, verbose_name='Issued on')),
                ('expected_return_on', models.DateField(blank=True, null=True, verbose_name='Expected return on')),
                ('returned_on', models.DateField(blank=True, null=True, verbose_name='Returned on')),
                ('condition_on_issue', models.TextField(blank=True, default='', verbose_name='Condition on issue')),
                ('condition_on_return', models.TextField(blank=True, default='', verbose_name='Condition on return')),
                ('status', models.CharField(choices=[('IN_USE', 'In use'), ('RETURNED', 'Returned'), ('DAMAGED', 'Damaged'), ('LOST', 'Lost'), ('SCRAPPED', 'Scrapped')], default='IN_USE', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issued_assets', to='equipment.equipment', verbose_name='Equipment')),
                ('issued_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets_issued_to', to=settings.AUTH_USER_MODEL, verbose_name='Issued to')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issued_assets', to='equipment.inventoryitem', verbose_name='Item')),
            ],
            options={
                'verbose_name': 'Issued asset',
                'verbose_name_plural': 'Issued assets',
                'ordering': ['-created_at'],
                'indexes': [
                    models.Index(fields=['equipment', 'status'], name='equipment_i_equipme_8cdf49_idx'),
                    models.Index(fields=['item', 'status'], name='equipment_i_item_id_2f2bba_idx'),
                    models.Index(fields=['serial_no'], name='equipment_i_serial__f0cf58_idx'),
                ],
            },
        ),
        migrations.CreateModel(
            name='InventoryRequestLine',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('requested_qty', models.DecimalField(decimal_places=3, default=decimal.Decimal('0.000'), max_digits=12)),
                ('approved_qty', models.DecimalField(decimal_places=3, default=decimal.Decimal('0.000'), max_digits=12)),
                ('issued_qty', models.DecimalField(decimal_places=3, default=decimal.Decimal('0.000'), max_digits=12)),
                ('estimated_unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Estimated unit cost')),
                ('remarks', models.TextField(blank=True, default='', verbose_name='Remarks')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='request_lines', to='equipment.inventoryitem', verbose_name='Item')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='equipment.inventoryrequest', verbose_name='Request')),
            ],
            options={
                'verbose_name': 'Inventory request line',
                'verbose_name_plural': 'Inventory request lines',
                'indexes': [
                    models.Index(fields=['request', 'item'], name='equipment_i_request_084565_idx'),
                    models.Index(fields=['item'], name='equipment_i_item_id_8ecf87_idx'),
                ],
                'constraints': [
                    models.CheckConstraint(condition=models.Q(('requested_qty__gte', 0)), name='inv_req_line_requested_gte_0'),
                    models.CheckConstraint(condition=models.Q(('approved_qty__gte', 0)), name='inv_req_line_approved_gte_0'),
                    models.CheckConstraint(condition=models.Q(('issued_qty__gte', 0)), name='inv_req_line_issued_gte_0'),
                    models.CheckConstraint(condition=models.Q(('approved_qty__lte', models.F('requested_qty'))), name='inv_req_line_approved_lte_requested'),
                    models.CheckConstraint(condition=models.Q(('issued_qty__lte', models.F('approved_qty'))), name='inv_req_line_issued_lte_approved'),
                ],
                'unique_together': {('request', 'item')},
            },
        ),
    ]
