# Generated by Django 5.2.9 on 2026-03-24 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0103_inventory_management'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='item_code',
            field=models.CharField(blank=True, editable=False, max_length=100, unique=True, verbose_name='Item code'),
        ),
    ]
