# Generated by Django 5.2.9 on 2026-03-24 11:30

from django.db import migrations, models


def forwards_map_inventory_categories(apps, schema_editor):
    InventoryItem = apps.get_model('equipment', 'InventoryItem')
    # Map old categories to new classification codes.
    InventoryItem.objects.filter(category='CONSUMABLE').update(category='CS')
    InventoryItem.objects.filter(category='NON_CONSUMABLE').update(category='MIA_LLTA')


def backwards_map_inventory_categories(apps, schema_editor):
    InventoryItem = apps.get_model('equipment', 'InventoryItem')
    # Best-effort rollback mapping.
    InventoryItem.objects.filter(category='CS').update(category='CONSUMABLE')
    InventoryItem.objects.filter(category='MAS').update(category='NON_CONSUMABLE')
    InventoryItem.objects.filter(category='MIA_LLTA').update(category='NON_CONSUMABLE')


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0104_inventory_item_code_auto'),
    ]

    operations = [
        migrations.RunPython(forwards_map_inventory_categories, backwards_map_inventory_categories),
        migrations.AlterField(
            model_name='inventoryitem',
            name='category',
            field=models.CharField(
                choices=[
                    ('MAS', 'Major Asset (MAS)'),
                    ('MIA_LLTA', 'Minor Asset (MIA) / Limited Life Time Asset (LLTA)'),
                    ('CS', 'Consumable Stores (CS)'),
                ],
                max_length=20,
                verbose_name='Category',
            ),
        ),
    ]
