# Generated by Django 5.2.9 on 2026-03-24 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0105_inventory_item_category_reclassify'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='category',
            field=models.CharField(
                choices=[
                    ('MAS', 'Major Asset (MAS)'),
                    ('MIA_LLTA', 'Minor Asset (MIA) / Limited Life Time Asset (LLTA)'),
                    ('CS', 'Consumable Stores (CS)'),
                ],
                help_text='MAS: Major Assets (long-term durable/high-value assets). MIA/LLTA: Minor/Limited-life assets (typically 4-5 years). CS: Consumable Stores (used up quickly or negligible resale value).',
                max_length=20,
                verbose_name='Category',
            ),
        ),
    ]
