# Generated by Django 5.2.9 on 2026-03-24 12:10

import decimal
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0106_inventory_item_category_help_text'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcurementRequest',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('request_no', models.CharField(blank=True, editable=False, max_length=100, unique=True, verbose_name='Request number')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted by initiator'), ('UNDER_OFFICE_VERIFICATION', 'Under office verification'), ('OFFICE_VERIFIED', 'Office verified'), ('PENDING_STORE_APPROVAL', 'Pending store approval'), ('STORE_APPROVED', 'Store approved'), ('PENDING_HEAD_APPROVAL_EMAIL', 'Pending head approval (email)'), ('PENDING_HEAD_APPROVAL_OFFLINE', 'Pending head approval (offline)'), ('HEAD_APPROVED', 'Head approved'), ('PURCHASE_IN_PROGRESS', 'Purchase in progress'), ('PURCHASE_COMPLETED_PENDING_OFFICE_SEEN', 'Purchase completed pending office seen'), ('OFFICE_SEEN_COMPLETED', 'Office seen and completed'), ('REJECTED_BY_OFFICE', 'Rejected by office'), ('REJECTED_BY_STORE', 'Rejected by store'), ('REJECTED_BY_HEAD', 'Rejected by head'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=50)),
                ('head_approval_required', models.BooleanField(default=False)),
                ('head_approval_mode', models.CharField(choices=[('OFFLINE', 'Offline'), ('EMAIL', 'Email'), ('NOT_REQUIRED', 'Not required')], default='NOT_REQUIRED', max_length=20)),
                ('total_estimated_cost', models.DecimalField(decimal_places=2, default=decimal.Decimal('0.00'), max_digits=14)),
                ('remarks', models.TextField(blank=True, default='')),
                ('office_verified_at', models.DateTimeField(blank=True, null=True)),
                ('store_approved_at', models.DateTimeField(blank=True, null=True)),
                ('head_approved_at', models.DateTimeField(blank=True, null=True)),
                ('purchase_completed_at', models.DateTimeField(blank=True, null=True)),
                ('office_seen_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procurement_requests', to='equipment.equipment')),
                ('head_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_requests_head_approved', to=settings.AUTH_USER_MODEL)),
                ('initiated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='procurement_requests_initiated', to=settings.AUTH_USER_MODEL)),
                ('office_seen_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_requests_office_seen', to=settings.AUTH_USER_MODEL)),
                ('office_verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_requests_office_verified', to=settings.AUTH_USER_MODEL)),
                ('purchase_completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_requests_purchase_completed', to=settings.AUTH_USER_MODEL)),
                ('store_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_requests_store_approved', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['equipment', 'status', 'created_at'], name='equipment_p_equipme_4b00f8_idx'), models.Index(fields=['initiated_by', 'status', 'created_at'], name='equipment_p_initiat_8ef266_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProcurementRequestLine',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('manual_item_name', models.CharField(blank=True, default='', max_length=255)),
                ('classification', models.CharField(choices=[('MAS', 'Major Asset (MAS)'), ('MIA_LLTA', 'Minor Asset (MIA) / Limited Life Time Asset (LLTA)'), ('CS', 'Consumable Stores (CS)')], max_length=20)),
                ('office_corrected_name', models.CharField(blank=True, default='', max_length=255)),
                ('office_corrected_classification', models.CharField(blank=True, choices=[('MAS', 'Major Asset (MAS)'), ('MIA_LLTA', 'Minor Asset (MIA) / Limited Life Time Asset (LLTA)'), ('CS', 'Consumable Stores (CS)')], default='', max_length=20)),
                ('quantity', models.DecimalField(decimal_places=3, default=decimal.Decimal('0.000'), max_digits=12)),
                ('tentative_unit_cost', models.DecimalField(decimal_places=2, default=decimal.Decimal('0.00'), max_digits=12)),
                ('tentative_total_cost', models.DecimalField(decimal_places=2, default=decimal.Decimal('0.00'), max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('finalized_item_master', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_lines_finalized', to='equipment.inventoryitem')),
                ('item_master', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_lines', to='equipment.inventoryitem')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='equipment.procurementrequest')),
            ],
            options={
                'ordering': ['id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='proc_line_qty_gt_0'), models.CheckConstraint(condition=models.Q(('tentative_unit_cost__gte', 0)), name='proc_line_unit_cost_gte_0')],
            },
        ),
        migrations.CreateModel(
            name='ProcurementAttachment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('attachment_type', models.CharField(choices=[('ESTIMATE_COPY', 'Estimate copy'), ('HEAD_APPROVAL_SCAN', 'Head approval scan'), ('INVOICE', 'Invoice'), ('OTHER', 'Other')], max_length=30)),
                ('file', models.FileField(upload_to='procurement/%Y/%m/%d/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='equipment.procurementrequestline')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='equipment.procurementrequest')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_attachments_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcurementActionLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('OFFICE_VERIFIED', 'Office verified'), ('OFFICE_REJECTED', 'Office rejected'), ('STORE_APPROVED', 'Store approved'), ('STORE_REJECTED', 'Store rejected'), ('HEAD_APPROVED', 'Head approved'), ('HEAD_REJECTED', 'Head rejected'), ('PURCHASE_MARKED_COMPLETE', 'Purchase marked complete'), ('OFFICE_SEEN', 'Office seen')], max_length=40)),
                ('comments', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_actions_done', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_logs', to='equipment.procurementrequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
