# Generated by Django 5.2.9 on 2026-04-01 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0122_equipment_operator_absent_disruption_after_booking_end_hours'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='bookingattemptlog',
            index=models.Index(fields=['requested_at'], name='equipment_b_request_1a4c20_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingattemptlog',
            index=models.Index(fields=['equipment', 'requested_at'], name='equipment_b_equipme_1b71d0_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingattemptlog',
            index=models.Index(fields=['user', 'requested_at'], name='equipment_b_user_id_634945_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingattemptlog',
            index=models.Index(fields=['outcome', 'requested_at'], name='equipment_b_outcome_b1b389_idx'),
        ),
        migrations.AddIndex(
            model_name='noslotallocationlog',
            index=models.Index(fields=['user', 'requested_at'], name='equipment_n_user_id_4f832d_idx'),
        ),
        migrations.AddIndex(
            model_name='noslotallocationlog',
            index=models.Index(fields=['equipment', 'requested_at'], name='equipment_n_equipme_6f5bd1_idx'),
        ),
        migrations.AddIndex(
            model_name='urgentbookingrequest',
            index=models.Index(fields=['status', 'requested_at'], name='equipment_u_status_e46285_idx'),
        ),
        migrations.AddIndex(
            model_name='urgentbookingrequest',
            index=models.Index(fields=['user', 'equipment', 'status', 'decided_at'], name='equipment_u_user_id_0f11fd_idx'),
        ),
    ]
