# Generated by Django 5.2.9 on 2026-04-02 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0123_rename_equipment_b_mainten_6a8b2d_idx_equipment_b_mainten_f65288_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="disruption_reason",
            field=models.TextField(
                blank=True,
                null=True,
                verbose_name="Disruption reason",
                help_text='Staff-provided reason for "Other disruption" emails; cleared when resolved.',
            ),
        ),
    ]

