# Generated by Django 5.2.9 on 2026-04-02 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0124_booking_other_disruption_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="waitlistentry",
            name="status",
            field=models.CharField(
                default="ACTIVE",
                help_text="ACTIVE: eligible for auto-booking. CANNOT_FULFILL: removed from queue but kept for audit/visibility.",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="waitlistentry",
            name="cannot_fulfill_remark",
            field=models.TextField(
                blank=True,
                null=True,
                help_text="Reason why this waitlist entry could not be fulfilled/auto-booked.",
            ),
        ),
        migrations.AddField(
            model_name="waitlistentry",
            name="marked_cannot_fulfill_at",
            field=models.DateTimeField(
                blank=True,
                null=True,
                help_text="When this waitlist entry was marked as cannot fulfill.",
            ),
        ),
        migrations.AddIndex(
            model_name="waitlistentry",
            index=models.Index(fields=["equipment", "status", "created_at"], name="equipment_w_equipme_9f0b6b_idx"),
        ),
    ]

