# Generated by Django 5.2.9 on 2026-07-27 11:13

import django.db.models.deletion
import iic_booking.equipment.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0175_equipment_dsa_sync_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipmentmanager',
            options={'verbose_name': 'Officer in Charge', 'verbose_name_plural': 'Equipment Office in Charge'},
        ),
        migrations.RenameIndex(
            model_name='booking',
            new_name='equipment_b_mainten_f65288_idx',
            old_name='equipment_b_mainten_6a8b2d_idx',
        ),
        migrations.RenameIndex(
            model_name='equipmentamccontract',
            new_name='equipment_e_equipme_aa76d9_idx',
            old_name='equipment_e_equipme_d3e0b8_idx',
        ),
        migrations.RenameIndex(
            model_name='equipmentexpense',
            new_name='equipment_e_equipme_4a645c_idx',
            old_name='equipment_e_equipme_7a8c2f_idx',
        ),
        migrations.RenameIndex(
            model_name='equipmentinventoryitem',
            new_name='equipment_e_equipme_734884_idx',
            old_name='equipment_i_equipme_9e18c4_idx',
        ),
        migrations.RenameIndex(
            model_name='equipmentinventoryitem',
            new_name='equipment_e_item_id_fc5cfb_idx',
            old_name='equipment_i_item_id_d4933c_idx',
        ),
        migrations.RenameIndex(
            model_name='equipmentitemstock',
            new_name='equipment_e_equipme_0b251e_idx',
            old_name='equipment_i_equipme_f41441_idx',
        ),
        migrations.RenameIndex(
            model_name='equipmentitemstock',
            new_name='equipment_e_item_id_10e834_idx',
            old_name='equipment_i_item_id_6d3950_idx',
        ),
        migrations.RenameIndex(
            model_name='equipmentmodeschedule',
            new_name='equipment_e_parent__a2e669_idx',
            old_name='equipment_e_parent__7a1b2c_idx',
        ),
        migrations.RenameIndex(
            model_name='equipmentmodeschedule',
            new_name='equipment_e_mode_eq_ffd294_idx',
            old_name='equipment_e_mode_eq_8d3e4f_idx',
        ),
        migrations.RenameIndex(
            model_name='equipmentoperatorcoverage',
            new_name='equipment_e_equipme_d12c93_idx',
            old_name='equip_opcov_equipment_8a9b0a_idx',
        ),
        migrations.RenameIndex(
            model_name='equipmentoperatorcoverage',
            new_name='equipment_e_acting__c418b8_idx',
            old_name='equip_opcov_acting_o_39f0d6_idx',
        ),
        migrations.RenameIndex(
            model_name='equipmentoperatorcoverage',
            new_name='equipment_e_primary_de7690_idx',
            old_name='equip_opcov_primary_o_7c1b6f_idx',
        ),
        migrations.RenameIndex(
            model_name='equipmentoperatorcoverage',
            new_name='equipment_e_mode_67f52e_idx',
            old_name='equip_opcov_mode_02a0e6_idx',
        ),
        migrations.RenameIndex(
            model_name='equipmentwriteoffrequest',
            new_name='equipment_e_equipme_be934c_idx',
            old_name='equipment_e_equipme_9f1a2c_idx',
        ),
        migrations.RenameIndex(
            model_name='equipmentwriteoffrequest',
            new_name='equipment_e_initiat_4e7dc2_idx',
            old_name='equipment_e_initiat_4b5d6e_idx',
        ),
        migrations.RenameIndex(
            model_name='externalweeklyslotquotasnapshot',
            new_name='equipment_e_equipme_6fa8b5_idx',
            old_name='equip_ext_quota_week_idx',
        ),
        migrations.RenameIndex(
            model_name='inventoryitem',
            new_name='equipment_i_categor_de7dad_idx',
            old_name='equipment_i_categor_cbd3f2_idx',
        ),
        migrations.RenameIndex(
            model_name='inventoryrequest',
            new_name='equipment_i_equipme_0e5392_idx',
            old_name='equipment_i_equipme_4f95cf_idx',
        ),
        migrations.RenameIndex(
            model_name='inventoryrequest',
            new_name='equipment_i_request_9f8e12_idx',
            old_name='equipment_i_request_9b2cf8_idx',
        ),
        migrations.RenameIndex(
            model_name='inventoryrequestline',
            new_name='equipment_i_request_acf914_idx',
            old_name='equipment_i_request_084565_idx',
        ),
        migrations.RenameIndex(
            model_name='inventoryrequestline',
            new_name='equipment_i_item_id_f23fad_idx',
            old_name='equipment_i_item_id_8ecf87_idx',
        ),
        migrations.RenameIndex(
            model_name='inventorytransaction',
            new_name='equipment_i_equipme_2e6781_idx',
            old_name='equipment_i_equipme_0f9b81_idx',
        ),
        migrations.RenameIndex(
            model_name='inventorytransaction',
            new_name='equipment_i_tx_type_fbd16b_idx',
            old_name='equipment_i_tx_type_3745ca_idx',
        ),
        migrations.RenameIndex(
            model_name='inventorytransaction',
            new_name='equipment_i_referen_011598_idx',
            old_name='equipment_i_referen_98f42c_idx',
        ),
        migrations.RenameIndex(
            model_name='issuedasset',
            new_name='equipment_i_equipme_005069_idx',
            old_name='equipment_i_equipme_8cdf49_idx',
        ),
        migrations.RenameIndex(
            model_name='issuedasset',
            new_name='equipment_i_item_id_e5aca7_idx',
            old_name='equipment_i_item_id_2f2bba_idx',
        ),
        migrations.RenameIndex(
            model_name='issuedasset',
            new_name='equipment_i_serial__2b85c2_idx',
            old_name='equipment_i_serial__f0cf58_idx',
        ),
        migrations.RenameIndex(
            model_name='operatorleaverequest',
            new_name='equipment_o_operato_014d08_idx',
            old_name='equip_opera_operator_9b9a6a_idx',
        ),
        migrations.RenameIndex(
            model_name='operatorleaverequest',
            new_name='equipment_o_equipme_8b72eb_idx',
            old_name='equip_opera_equipment_2e7b3a_idx',
        ),
        migrations.RenameIndex(
            model_name='procurementrequest',
            new_name='equipment_p_equipme_396568_idx',
            old_name='equipment_p_equipme_4b00f8_idx',
        ),
        migrations.RenameIndex(
            model_name='procurementrequest',
            new_name='equipment_p_initiat_41e0f1_idx',
            old_name='equipment_p_initiat_8ef266_idx',
        ),
        migrations.RenameIndex(
            model_name='waitlistentry',
            new_name='equipment_w_equipme_ef2335_idx',
            old_name='equipment_w_equipme_9f0b6b_idx',
        ),
        migrations.AlterField(
            model_name='booking',
            name='disruption_kind',
            field=models.CharField(blank=True, choices=[('MAINTENANCE', 'Maintenance / equipment'), ('OPERATOR_ABSENT', 'Operator unavailable'), ('OTHER_DISRUPTION', 'Other disruption')], help_text='Set when status is Awaiting your choice (disruption); cleared when resolved.', max_length=32, null=True, verbose_name='Disruption kind'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='istem_fbr_executed_at',
            field=models.DateTimeField(blank=True, help_text='When OIC marked the FBR as verified.', null=True, verbose_name='I-STEM FBR executed at'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='istem_fbr_status',
            field=models.CharField(blank=True, choices=[('PENDING_FBR', 'FBR not submitted'), ('PENDING_OIC', 'Awaiting OIC verification'), ('INVALID', 'FBR rejected — correction required'), ('EXECUTED', 'FBR verified')], help_text='Workflow state for external-user FBR verification by OIC. Null for internal users or pre-migration bookings.', max_length=20, null=True, verbose_name='I-STEM FBR status'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='istem_fbr_verified_by',
            field=models.ForeignKey(blank=True, help_text='OIC (or admin) who last verified or rejected the FBR.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings_istem_fbr_verified', to=settings.AUTH_USER_MODEL, verbose_name='I-STEM FBR verified by'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='maintenance_reschedule_extra_week',
            field=models.BooleanField(default=False, help_text='When True, slots API extends the visible window for this user reschedule (see maintenance operational marked time).', verbose_name='Extra week for maintenance reschedule'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='return_shipping_company',
            field=models.CharField(blank=True, default='', help_text='Shipping/courier company for return dispatch (set by Accounts In Charge).', max_length=128, verbose_name='Return shipping company'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='return_shipping_tracking_id',
            field=models.TextField(blank=True, default='', help_text='Tracking or AWB number for returning samples to the user.', verbose_name='Return shipping tracking ID'),
        ),
        migrations.AlterField(
            model_name='bookingbufferconfig',
            name='auto_archive_enabled',
            field=models.BooleanField(default=True, help_text='When unchecked, the daily auto-dispose task is skipped.', verbose_name='Auto-dispose enabled'),
        ),
        migrations.AlterField(
            model_name='bookingbufferconfig',
            name='sample_retention_days',
            field=models.PositiveIntegerField(default=60, help_text='After the sample is marked "Analyzed" (COMPLETED in trace), wait this many days before auto-marking the sample as Disposed in Sample Lifecycle. Set to 0 to disable auto-dispose.', verbose_name='Sample retention (days)'),
        ),
        migrations.AlterField(
            model_name='bookingevent',
            name='new_status',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('PENDING_PAYMENT', 'Awaiting payment'), ('WAITLISTED', 'Waitlisted'), ('BOOKED', 'Booked'), ('DISRUPTION_PENDING', 'Awaiting your choice (disruption)'), ('UNDER_MAINTENANCE', 'Under Maintenance'), ('OTHER_DISRUPTION', 'Other Disruption'), ('HOLD', 'Hold'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('ABSENT', 'Operator Unavailable'), ('REFUNDED', 'Refunded'), ('BOOKING_NOT_UTILIZED', 'Booking Not Utilized')], help_text='New booking status (if status changed)', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='bookingevent',
            name='previous_status',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('PENDING_PAYMENT', 'Awaiting payment'), ('WAITLISTED', 'Waitlisted'), ('BOOKED', 'Booked'), ('DISRUPTION_PENDING', 'Awaiting your choice (disruption)'), ('UNDER_MAINTENANCE', 'Under Maintenance'), ('OTHER_DISRUPTION', 'Other Disruption'), ('HOLD', 'Hold'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('ABSENT', 'Operator Unavailable'), ('REFUNDED', 'Refunded'), ('BOOKING_NOT_UTILIZED', 'Booking Not Utilized')], help_text='Previous booking status (if status changed)', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='bookingsampletrace',
            name='status',
            field=models.CharField(choices=[('SAMPLE_SENT', 'Sample Sent'), ('HELD_AT_OFFICE', 'Held at Office'), ('FORWARDED_TO_LAB', 'Forwarded to Lab'), ('SAMPLE_ACCEPTED', 'Sample Accepted'), ('SAMPLE_REJECTED', 'Sample Rejected'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Analyzed'), ('RETURNED', 'Returned'), ('ARCHIVED', 'Archived'), ('DISPOSED', 'Disposed'), ('NOT_UTILIZED', 'Booking Not Utilized'), ('OP_UNAVAILABLE', 'Operator Unavailable')], max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='dynamicinputfield',
            name='help_text',
            field=models.TextField(blank=True, help_text='Help text for this field. NUMERIC: line 1 = lower limit (may be negative), line 2 = upper limit, line 3 = step (e.g. 0.01). Defaults 0 / 100 / 1 when blank. Negative defaults are allowed within limits. PERIODIC_TABLE: one element per line to disable (e.g. Fe); prefix with / to lock-preselect without charge (e.g. /C for Carbon). Also used for ICPMS Standard Coverage standards notes.', null=True),
        ),
        migrations.AlterField(
            model_name='dynamicinputfield',
            name='source_element_field_key',
            field=models.CharField(blank=True, help_text='Field key link: ICPMS Standard Coverage — Periodic Table field providing the element list; TABLE — numeric field whose value sets the table row count (first column = S.No.).', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='booking_not_utilize_window_hours',
            field=models.PositiveIntegerField(default=24, help_text='Hours after the last slot end before staff may mark "Booking Not Utilized" (no refund) when the user did not attend or samples were not submitted, and sample lifecycle has no update or only "Sample Sent". Set to 0 to hide/disable this action for this equipment.', verbose_name='Booking Not Utilize Window (hours)'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='image',
            field=models.ImageField(blank=True, help_text='Photo shown when booking. Stored via default media storage (S3 in production) so images survive deploys.', max_length=512, null=True, storage=iic_booking.equipment.models.get_equipment_image_storage, upload_to=iic_booking.equipment.models.equipment_image_upload_to, verbose_name='Equipment image'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='istem_fbr_status_url',
            field=models.URLField(blank=True, default='', help_text='Optional hyperlink for Officer In-charge / Admins to verify FBR status on I-STEM (separate from the user booking page URL).', max_length=500, verbose_name='I-STEM FBR status check URL'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='istem_portal_url',
            field=models.URLField(blank=True, default='', help_text="Optional hyperlink to this equipment's booking page on the I-STEM portal. Shown to booking users when I-STEM FBR is required for their charge profile.", max_length=500, verbose_name='I-STEM portal URL'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='operator_absent_disruption_after_booking_end_hours',
            field=models.PositiveIntegerField(default=48, help_text='After the last slot end time, if the booking is still PENDING or BOOKED and the sample lifecycle status remains stuck at "Sample Accepted" or "Processing" for this many hours, the system treats it as an Operator Absent disruption and triggers the usual disruption flow (refund vs reschedule choice). Set to 0 to disable.', verbose_name='Auto Operator Absent Disruption (hours after booking end)'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='operator_unavailable_after_booking_end_hours',
            field=models.PositiveIntegerField(default=24, help_text='After the last slot end, if the booking is still open and sample lifecycle shows staff activity beyond "Sample Sent" but the run is not finished (no completed/returned/archived/disposed lifecycle), the system automatically marks Operator Unavailable (full refund) once this many hours have passed. Set to 0 to disable. User no-show / sample-not-submitted cases use manual Booking Not Utilized instead.', verbose_name='Auto Operator Unavailable (hours after booking end)'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='parent_equipment',
            field=models.ForeignKey(blank=True, help_text='When set, this equipment is an alternate operating mode of the parent (base) instrument. The parent must have Multi-Mode Equipment enabled. Leave empty for standalone equipment or for the base/parent mode itself.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mode_children', to='equipment.equipment', verbose_name='Parent Equipment (multi-mode)'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='profile_type',
            field=models.CharField(blank=True, choices=[('SAMPLE', 'Sample-based'), ('HOUR', 'Hour-based'), ('SAMPLE_ELEMENT', 'Sample + Element'), ('MULTI_PARAM', 'Multi-parameter'), ('PRINT_3D', '3D Print')], help_text='Type of equipment profile', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='sample_submission_lead_hours',
            field=models.PositiveIntegerField(default=24, help_text='Users must submit samples this many hours before the booked slot starts. If that deadline falls on a weekend or institute public holiday, it is moved to the previous working day (same clock time). Atmosphere-sensitive bookings may submit up to slot start instead. Set to 0 to use slot start as the deadline.', verbose_name='Sample submission lead time (hours before slot start)'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='status',
            field=models.CharField(blank=True, choices=[('ACTIVE', 'Operational'), ('MAINTENANCE', 'Under Maintenance'), ('REPAIR', 'Under Maintenance'), ('INACTIVE', 'Under Maintenance'), ('DISPOSED', 'Disposed'), ('OTHER', 'Other')], help_text='Status of the equipment', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='equipmentaccessory',
            name='is_enabled',
            field=models.BooleanField(default=True, help_text='When disabled, this accessory is shown as Unavailable on booking and equipment views. OIC can toggle this.', verbose_name='Enabled'),
        ),
        migrations.AlterField(
            model_name='equipmentadditionalaccessory',
            name='is_enabled',
            field=models.BooleanField(default=True, help_text='When disabled, this additional accessory is shown as Unavailable on booking and equipment views. OIC can toggle this.', verbose_name='Enabled'),
        ),
        migrations.AlterField(
            model_name='equipmentadditionrequest',
            name='equipment_image',
            field=models.ImageField(blank=True, max_length=512, null=True, upload_to=iic_booking.equipment.models.equipment_addition_image_upload_to, verbose_name='Equipment image'),
        ),
        migrations.AlterField(
            model_name='equipmentadditionrequest',
            name='supporting_document',
            field=models.FileField(blank=True, max_length=512, null=True, upload_to=iic_booking.equipment.models.equipment_addition_document_upload_to, verbose_name='Supporting document'),
        ),
        migrations.AlterField(
            model_name='equipmentexpense',
            name='classification',
            field=models.CharField(blank=True, choices=[('MAS', 'Major Asset (MAS)'), ('MIA_LLTA', 'Minor Asset (MIA) / Limited Life Time Asset (LLTA)'), ('CS', 'Consumable Stores (CS)')], default='', help_text='Consumable / minor / major — optional tag', max_length=20),
        ),
        migrations.AlterField(
            model_name='equipmentmanager',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Date and time this assignment was created'),
        ),
        migrations.AlterField(
            model_name='equipmentmanager',
            name='manager',
            field=models.ForeignKey(help_text='Officer in Charge for this equipment', limit_choices_to={'user_type': 'manager'}, on_delete=django.db.models.deletion.PROTECT, related_name='equipment_manager', to=settings.AUTH_USER_MODEL, verbose_name='Officer in Charge'),
        ),
        migrations.AlterField(
            model_name='equipmentmanager',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Date and time this assignment was last updated'),
        ),
        migrations.AlterField(
            model_name='equipmentoperatorcoverage',
            name='acting_operator',
            field=models.ForeignKey(blank=True, help_text='Operator who will temporarily handle this equipment (for SECONDARY_OPERATOR mode).', limit_choices_to={'user_type': 'operator'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acting_operator_coverages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='equipmentoperatorcoverage',
            name='primary_operator',
            field=models.ForeignKey(limit_choices_to={'user_type': 'operator'}, on_delete=django.db.models.deletion.CASCADE, related_name='primary_operator_coverages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='equipmentwriteoffrequest',
            name='asset_classification',
            field=models.CharField(blank=True, choices=[('MAS', 'Major Asset (MAS)'), ('MIA_LLTA', 'Minor Asset (MIA) / Limited Life Time Asset (LLTA)'), ('CS', 'Consumable Stores (CS)')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='operatorleaverequest',
            name='operator',
            field=models.ForeignKey(limit_choices_to={'user_type': 'operator'}, on_delete=django.db.models.deletion.CASCADE, related_name='operator_leave_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='slotmaster',
            name='close_time',
            field=models.TimeField(help_text='Slot close/end time. Use 00:00 for end-of-day; if earlier than open time the slot spans midnight (e.g. 18:00–00:00).'),
        ),
    ]
