# Generated by Django 5.2.9 on 2026-07-27 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0177_result_processing_m10'),
        ('remote_analysis', '0007_production_hardening_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='analysis_available',
            field=models.BooleanField(default=False, help_text='True when this booking is eligible for Remote Analysis (does not change booking status).', verbose_name='Remote Analysis available'),
        ),
        migrations.AddField(
            model_name='booking',
            name='analysis_available_from',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Analysis available from'),
        ),
        migrations.AddField(
            model_name='booking',
            name='analysis_expiry',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Analysis access expiry'),
        ),
        migrations.AddField(
            model_name='booking',
            name='analysis_last_session',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last analysis session at'),
        ),
        migrations.AddField(
            model_name='booking',
            name='analysis_reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_for_bookings', to='remote_analysis.analysisreservation', verbose_name='Primary analysis reservation'),
        ),
        migrations.AddField(
            model_name='booking',
            name='analysis_session_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Analysis session count'),
        ),
        migrations.AddField(
            model_name='booking',
            name='analysis_workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_for_bookings', to='remote_analysis.analysisworkspace', verbose_name='Primary analysis workspace'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='analysis_access_duration',
            field=models.PositiveIntegerField(default=72, help_text='Hours after availability before analysis access expires.', verbose_name='Analysis access duration (hours)'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='analysis_auto_archive',
            field=models.BooleanField(default=True, help_text='Prefer automatic archive when analysis access expires.', verbose_name='Workspace auto archive'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='analysis_notes',
            field=models.TextField(blank=True, default='', help_text='Operator-facing notes for Remote Analysis on this equipment.', verbose_name='Remote Analysis notes'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='analysis_profile',
            field=models.CharField(blank=True, default='', help_text='Optional software/capability profile name for scheduler matching.', max_length=128, null=True, verbose_name='Analysis profile'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='analysis_requires_experiment_completion',
            field=models.BooleanField(default=True, help_text='When True, booking must be Completed before analysis.', verbose_name='Requires experiment completion'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='analysis_requires_sample_acceptance',
            field=models.BooleanField(default=False, help_text='When True, sample lifecycle must include Sample Accepted before analysis.', verbose_name='Requires sample acceptance'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='analysis_session_limit',
            field=models.PositiveIntegerField(default=5, help_text='Maximum remote desktop sessions allowed per booking (0 = unlimited).', verbose_name='Maximum analysis sessions'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='analysis_workspace_retention_days',
            field=models.PositiveIntegerField(default=90, help_text='Hint for workspace retention; Portal Remote Analysis settings remain authoritative for purge.', verbose_name='Analysis workspace retention (days)'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='enable_remote_analysis',
            field=models.BooleanField(default=False, help_text='When enabled, eligible completed bookings may create analysis reservations.', verbose_name='Enable Remote Analysis'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='remote_analysis_enabled_from_status',
            field=models.CharField(blank=True, default='COMPLETED', help_text='Booking status from which Remote Analysis becomes available (default COMPLETED).', max_length=30, verbose_name='Remote Analysis eligibility rule'),
        ),
    ]
