# Generated by Django 5.2.9 on 2026-09-25 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0196_disable_remote_analysis_all_equipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='alternative_priority',
            field=models.PositiveSmallIntegerField(db_default=100, default=100, help_text='Ordering among equipment of the same group when offered as an alternative (lower = preferred). Ties are broken by equipment ID.', verbose_name='Alternative priority'),
        ),
        migrations.AddField(
            model_name='equipmentgroup',
            name='alternative_booking_enabled',
            field=models.BooleanField(db_default=False, default=False, help_text='When the requested slot is unavailable, offer other equipment of this group before the waitlist. Requires EQUIPMENT_GROUP_ALTERNATIVE_BOOKING_ENABLED.', verbose_name='Use as alternatives for new booking'),
        ),
        migrations.AddField(
            model_name='equipmentgroup',
            name='alternative_search_other_slots',
            field=models.BooleanField(db_default=False, default=False, help_text='When no group member has the exact requested slot, also offer the earliest other available slots within the normal slot window. Off = exact requested slot only.', verbose_name='Also offer other available slots'),
        ),
        migrations.AddField(
            model_name='equipmentgroup',
            name='auto_allocation_enabled',
            field=models.BooleanField(db_default=False, default=False, help_text='Book the best alternative automatically instead of asking the user. Requires alternative booking and EQUIPMENT_GROUP_AUTO_ALLOCATION_ENABLED.', verbose_name='Automatically allocate alternative'),
        ),
        migrations.AddField(
            model_name='equipmentgroup',
            name='cross_rescheduling_enabled',
            field=models.BooleanField(db_default=False, default=False, help_text='Allow bookings to be rescheduled to other equipment of this group. Requires EQUIPMENT_GROUP_CROSS_RESCHEDULING_ENABLED.', verbose_name='Allow cross-equipment rescheduling'),
        ),
    ]
