# Generated by Django 5.2.9 on 2026-09-28 09:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0199_repeat_sample_self_booking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='max_rush_relief_requests_per_week',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum number of approved rush-relief (Type A, surcharge waived) urgent bookings for this equipment in one calendar week (Monday–Sunday), across all users. Leave empty for no cap.', null=True, verbose_name='Max rush-relief urgent bookings per week'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='max_surcharge_urgent_requests_per_week',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum number of surcharge-based (Type B, 50% surcharge) urgent bookings for this equipment in one calendar week (Monday–Sunday), across all users. Requests still awaiting approval count towards the cap. Leave empty for no cap.', null=True, verbose_name='Max surcharge urgent bookings per week'),
        ),
        migrations.AddField(
            model_name='equipmentmanager',
            name='disable_booking_confirmation_email',
            field=models.BooleanField(default=False, help_text='When checked, this Officer in Charge does not receive booking confirmation emails for this equipment.'),
        ),
        migrations.AddField(
            model_name='equipmentoperator',
            name='disable_booking_confirmation_email',
            field=models.BooleanField(default=False, help_text='When checked, this Lab In-charge does not receive booking confirmation emails for this equipment.'),
        ),
        migrations.AddField(
            model_name='urgentbookingrequest',
            name='supervisor',
            field=models.ForeignKey(blank=True, help_text='Faculty supervisor who must approve a surcharge-based urgent request before the OIC decides.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='urgent_requests_to_supervise', to=settings.AUTH_USER_MODEL, verbose_name='Supervisor'),
        ),
        migrations.AddField(
            model_name='urgentbookingrequest',
            name='supervisor_approval_required',
            field=models.BooleanField(default=False, help_text='Surcharge-based request raised by a user who has a supervisor; the OIC cannot decide until the supervisor approves.'),
        ),
        migrations.AddField(
            model_name='urgentbookingrequest',
            name='supervisor_decided_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='urgentbookingrequest',
            name='supervisor_decision',
            field=models.CharField(blank=True, choices=[('', 'Awaiting supervisor'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='', max_length=16),
        ),
    ]
