# Generated by Django 5.2.9 on 2026-10-10 09:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0245_laser_cut_time_estimate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingCancellation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cancelled_at', models.DateTimeField(db_index=True)),
                ('actor_role', models.CharField(choices=[('USER', 'Booking user'), ('SUPERVISOR', 'Supervisor / wallet owner'), ('OIC', 'Officer In Charge'), ('LAB_OPERATOR', 'Lab Operator'), ('DEPT_ADMIN', 'Department Administrator'), ('MAIN_ADMIN', 'Main Administrator'), ('OTHER_STAFF', 'Other staff'), ('SYSTEM', 'System (automatic)'), ('UNKNOWN', 'Not recorded')], db_index=True, default='UNKNOWN', max_length=20)),
                ('reason', models.CharField(choices=[('USER_REQUEST', 'Cancelled by the user'), ('STAFF_CANCEL', 'Cancelled by staff'), ('STAFF_REFUND', 'Refunded by staff'), ('CANCELLATION_REQUEST', 'Cancellation request approved'), ('EQUIPMENT_DOWN', 'Equipment under maintenance'), ('OPERATOR_UNAVAILABLE', 'Operator unavailable'), ('ANALYSIS_NOT_POSSIBLE', 'Analysis not possible'), ('DISRUPTION_DEADLINE', 'No choice after a disruption (automatic)'), ('LAB_REJECTED_FILES', 'Lab rejected the design files'), ('URGENT_HOLD_RELEASED', 'Urgent hold released or expired'), ('NO_SHOW', 'Booking not utilized (no-show)'), ('OTHER', 'Other')], db_index=True, default='OTHER', max_length=32)),
                ('note', models.TextField(blank=True, default='', help_text='Notes typed when cancelling, if any.')),
                ('previous_status', models.CharField(blank=True, default='', max_length=30)),
                ('new_status', models.CharField(blank=True, default='', max_length=30)),
                ('charge_amount', models.DecimalField(decimal_places=2, default=0, help_text='Amount paid for the booking when it was cancelled.', max_digits=12)),
                ('refund_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Empty when the refund is not known.', max_digits=12, null=True)),
                ('refund_estimated', models.BooleanField(default=False, help_text='Refund taken as the full charge because the amount was not recorded.')),
                ('slot_start', models.DateTimeField(blank=True, null=True)),
                ('slot_end', models.DateTimeField(blank=True, null=True)),
                ('lead_minutes', models.IntegerField(blank=True, db_index=True, help_text='Minutes between the cancellation and the first slot start (negative: after it started).', null=True)),
                ('released_slot_ids', models.JSONField(blank=True, default=list)),
                ('data_quality', models.CharField(choices=[('RECORDED', 'Recorded at the time'), ('FROM_HISTORY', 'Rebuilt from booking history'), ('INFERRED', 'Inferred from the booking status only')], db_index=True, default='RECORDED', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cancellation_record', to='equipment.booking')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='equipment.bookingevent')),
            ],
            options={
                'verbose_name': 'Booking cancellation',
                'verbose_name_plural': 'Booking cancellations',
                'ordering': ['-cancelled_at', '-id'],
                'indexes': [models.Index(fields=['cancelled_at', 'reason'], name='equip_bcancel_at_reason')],
            },
        ),
    ]
