# Generated by Django 5.2.9 on 2026-10-10 14:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0246_bookingcancellation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestDataFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('equipment', 'Equipment'), ('category', 'Equipment category')], max_length=16, verbose_name='Kind')),
                ('object_id', models.PositiveIntegerField(verbose_name='Record id')),
                ('label', models.CharField(blank=True, default='', max_length=255, verbose_name='Name when marked')),
                ('reason', models.CharField(blank=True, default='', max_length=255, verbose_name='Why it is test data')),
                ('flagged_at', models.DateTimeField(auto_now_add=True, verbose_name='Marked at')),
                ('flagged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Marked by')),
            ],
            options={
                'verbose_name': 'Test data mark',
                'verbose_name_plural': 'Test data marks',
                'ordering': ['kind', 'object_id'],
                'constraints': [models.UniqueConstraint(fields=('kind', 'object_id'), name='equipment_testdataflag_unique')],
            },
        ),
    ]
