# Generated by Django 5.2.9 on 2026-10-10 07:33

import django.db.models.deletion
import iic_booking.facility_groups.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0244_equipment_flash_messages'),
        ('users', '0138_sric_wallet_recharge_quiet_window'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FacilityUserGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('kind', models.CharField(choices=[('all', 'All booking users'), ('lab', 'Laboratory / facility'), ('category', 'Equipment category'), ('equipment_group', 'Equipment group'), ('equipment', 'Equipment'), ('custom', 'Custom')], db_index=True, max_length=20, verbose_name='Kind')),
                ('auto_key', models.CharField(blank=True, help_text='e.g. equipment:12 or category:3 for automatic groups; empty for custom groups.', max_length=64, null=True, unique=True, verbose_name='Automatic key')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('is_archived', models.BooleanField(default=False, verbose_name='Archived')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='equipment.equipmentcategory')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='equipment.equipment')),
                ('equipment_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='equipment.equipmentgroup')),
                ('lab', models.ForeignKey(blank=True, help_text='Internal department hosting the equipment (e.g. a centre or the Tinkering Lab).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='users.department')),
            ],
            options={
                'verbose_name': 'Facility user group',
                'verbose_name_plural': 'Facility user groups',
                'ordering': ['kind', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GroupEmailCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('body_html', models.TextField(blank=True, default='')),
                ('body_text', models.TextField(blank=True, default='')),
                ('group_names', models.JSONField(blank=True, default=list)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('cc', models.JSONField(blank=True, default=list)),
                ('bcc', models.JSONField(blank=True, default=list)),
                ('cc_mode', models.CharField(choices=[('summary', 'One summary copy to CC / BCC'), ('each', "CC / BCC on every recipient's email")], default='summary', max_length=10)),
                ('reply_to', models.CharField(blank=True, default='', max_length=254)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sending', 'Sending'), ('sent', 'Sent'), ('partial', 'Sent with failures'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='queued', max_length=20)),
                ('total_recipients', models.PositiveIntegerField(default=0)),
                ('sent_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('skipped_count', models.PositiveIntegerField(default=0)),
                ('summary_sent_at', models.DateTimeField(blank=True, null=True)),
                ('idempotency_key', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('groups', models.ManyToManyField(blank=True, related_name='email_campaigns', to='facility_groups.facilityusergroup')),
            ],
            options={
                'verbose_name': 'Group email',
                'verbose_name_plural': 'Group emails',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GroupEmailAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=300, upload_to=iic_booking.facility_groups.models.campaign_attachment_upload_to)),
                ('filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(blank=True, default='', max_length=120)),
                ('size', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='facility_groups.groupemailcampaign')),
            ],
        ),
        migrations.CreateModel(
            name='FacilityUserGroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_count', models.PositiveIntegerField(default=0)),
                ('first_booked_at', models.DateTimeField(blank=True, null=True)),
                ('last_booked_at', models.DateTimeField(blank=True, null=True)),
                ('supervised_booking_count', models.PositiveIntegerField(default=0, help_text='Bookings in this group made by students / project staff linked to this faculty.')),
                ('last_supervised_at', models.DateTimeField(blank=True, null=True)),
                ('added_manually', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='facility_groups.facilityusergroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facility_group_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Facility user group member',
                'verbose_name_plural': 'Facility user group members',
                'indexes': [models.Index(fields=['group', 'last_booked_at'], name='facility_grp_member_last')],
                'constraints': [models.UniqueConstraint(fields=('group', 'user'), name='facility_group_member_unique')],
            },
        ),
        migrations.CreateModel(
            name='GroupEmailRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=254)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('department_name', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed'), ('skipped', 'Skipped')], db_index=True, default='pending', max_length=10)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('error', models.TextField(blank=True, default='')),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='facility_groups.groupemailcampaign')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Group email recipient',
                'verbose_name_plural': 'Group email recipients',
                'constraints': [models.UniqueConstraint(fields=('campaign', 'email'), name='group_email_recipient_unique')],
            },
        ),
    ]
