# Generated by Django 5.2.9 on 2026-07-27 10:32

import django.core.validators
import django.db.models.deletion
import iic_booking.sync.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0175_equipment_dsa_sync_fields'),
        ('users', '0095_initial_payment_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentSyncAgent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('agent_uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Public agent identity used for authentication.', unique=True, verbose_name='Agent UUID')),
                ('agent_name', models.CharField(max_length=200, verbose_name='Agent name')),
                ('machine_name', models.CharField(blank=True, default='', max_length=200, verbose_name='Machine name')),
                ('machine_guid', models.UUIDField(db_index=True, help_text='Stable OS/machine identifier reported by the agent host.', unique=True, verbose_name='Machine GUID')),
                ('version', models.CharField(blank=True, default='', max_length=50, verbose_name='Agent version')),
                ('operating_system', models.CharField(blank=True, default='', max_length=200, verbose_name='Operating system')),
                ('status', models.CharField(choices=[('REGISTERED', 'Registered'), ('ENROLLED', 'Enrolled'), ('DISABLED', 'Disabled'), ('REVOKED', 'Revoked')], db_index=True, default='REGISTERED', help_text='Lifecycle only (REGISTERED / ENROLLED / DISABLED / REVOKED). Never store ONLINE/OFFLINE here.', max_length=20, verbose_name='Lifecycle status')),
                ('agent_secret_hash', models.CharField(blank=True, default='', help_text='Hashed long-lived agent secret. Never store the plaintext secret.', max_length=128, verbose_name='Agent secret hash')),
                ('agent_secret_rotated_at', models.DateTimeField(blank=True, null=True, verbose_name='Agent secret rotated at')),
                ('enrollment_token_hash', models.CharField(blank=True, default='', help_text='Optional one-time enrollment token hash used during registration.', max_length=128, verbose_name='Enrollment token hash')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Convenience flag. Prefer status=DISABLED/REVOKED for durable lifecycle control.', verbose_name='Active')),
                ('last_heartbeat_at', models.DateTimeField(blank=True, null=True, verbose_name='Last heartbeat at')),
                ('last_seen_at', models.DateTimeField(blank=True, null=True, verbose_name='Last seen at')),
                ('last_boot_at', models.DateTimeField(blank=True, null=True, verbose_name='Last boot at')),
                ('last_reported_configuration_version', models.PositiveIntegerField(blank=True, help_text='configuration_version reported by the agent via heartbeat. Used to detect BootstrapRequired without returning full config.', null=True, verbose_name='Last reported configuration version')),
                ('last_reported_schema_version', models.PositiveIntegerField(blank=True, help_text='Bootstrap document schema_version reported by the agent via heartbeat. Mismatch may require agent upgrade or bootstrap refresh.', null=True, verbose_name='Last reported schema version')),
                ('registered_at', models.DateTimeField(auto_now_add=True, verbose_name='Registered at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='department_sync_agents', to='users.department', verbose_name='Department')),
            ],
            options={
                'verbose_name': 'Department Sync Agent',
                'verbose_name_plural': 'Department Sync Agents',
                'ordering': ['-registered_at'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentSyncProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hostname', models.CharField(blank=True, default='', help_text='Instrument PC hostname. Replacing the PC updates this profile, not Equipment.', max_length=200, verbose_name='Instrument hostname')),
                ('ip_address', models.CharField(blank=True, default='', max_length=64, verbose_name='Instrument IP address')),
                ('share_name', models.CharField(blank=True, default='', help_text='SMB share name on the instrument PC (e.g. Results).', max_length=200, verbose_name='Share name')),
                ('unc_path', models.CharField(blank=True, default='', help_text='Full UNC path, e.g. \\\\192.168.1.2\\Results.', max_length=500, verbose_name='UNC path')),
                ('watch_folder', models.CharField(blank=True, default='', help_text='Relative or absolute folder path monitored for new result files.', max_length=500, verbose_name='Watch folder')),
                ('sync_interval_seconds', models.PositiveIntegerField(default=300, validators=[django.core.validators.MinValueValidator(30)], verbose_name='Synchronization interval (seconds)')),
                ('sync_enabled', models.BooleanField(default=True, verbose_name='Sync enabled')),
                ('watch_enabled', models.BooleanField(default=True, help_text="Legacy flag. Prefer enabled_features['watcher'].", verbose_name='Watch folder enabled')),
                ('upload_enabled', models.BooleanField(default=True, help_text="Legacy flag. Prefer enabled_features['upload'].", verbose_name='Upload enabled')),
                ('enabled_features', models.JSONField(blank=True, default=iic_booking.sync.models.default_enabled_features, help_text='Flexible capability map (watcher, upload, analysis, diagnostics, remote_execution, …). Prefer this over new Boolean columns.', verbose_name='Enabled features')),
                ('configuration_version', models.PositiveIntegerField(default=1, help_text='Increment whenever sync configuration changes. Heartbeat mismatch triggers BootstrapRequired.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Configuration version')),
                ('schema_version', models.PositiveIntegerField(default=1, help_text='Version of the bootstrap document structure this profile conforms to. Heartbeat mismatch may require agent upgrade or bootstrap refresh.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Bootstrap schema version')),
                ('smb_credential_reference', models.CharField(blank=True, default='', help_text='Preferred secret handle (vault key, Windows credential name, etc.). Do not store raw SMB passwords in PostgreSQL.', max_length=255, verbose_name='SMB credential reference')),
                ('smb_username', models.CharField(blank=True, default='', help_text='Optional username hint. Pair with credential reference, not a DB password.', max_length=200, verbose_name='SMB username')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('equipment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sync_profile', to='equipment.equipment', verbose_name='Equipment')),
            ],
            options={
                'verbose_name': 'Equipment Sync Profile',
                'verbose_name_plural': 'Equipment Sync Profiles',
                'ordering': ['equipment__code'],
            },
        ),
        migrations.CreateModel(
            name='AgentAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Active')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='Assigned at')),
                ('unassigned_at', models.DateTimeField(blank=True, null=True, verbose_name='Unassigned at')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('sync_agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='sync.departmentsyncagent', verbose_name='Sync agent')),
                ('sync_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='sync.equipmentsyncprofile', verbose_name='Equipment sync profile')),
            ],
            options={
                'verbose_name': 'Agent Assignment',
                'verbose_name_plural': 'Agent Assignments',
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='Laboratory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('code', models.CharField(blank=True, default='', help_text='Optional short code unique within the department.', max_length=50, verbose_name='Code')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('location', models.CharField(blank=True, default='', max_length=255, verbose_name='Location')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='laboratories', to='users.department', verbose_name='Department')),
            ],
            options={
                'verbose_name': 'Laboratory',
                'verbose_name_plural': 'Laboratories',
                'ordering': ['department__name', 'name'],
            },
        ),
        migrations.AddField(
            model_name='departmentsyncagent',
            name='laboratory',
            field=models.ForeignKey(blank=True, help_text='Laboratory workstation location. Prefer setting this for lab-centric ops.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sync_agents', to='sync.laboratory', verbose_name='Laboratory'),
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('event_code', models.CharField(db_index=True, help_text='Stable code such as SYNC-1001, UPLOAD-2001, BOOTSTRAP-3001.', max_length=32, verbose_name='Event code')),
                ('severity', models.CharField(choices=[('DEBUG', 'Debug'), ('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], db_index=True, default='INFO', max_length=20, verbose_name='Severity')),
                ('category', models.CharField(choices=[('SYNC', 'Sync'), ('HEARTBEAT', 'Heartbeat'), ('UPLOAD', 'Upload'), ('BOOTSTRAP', 'Bootstrap'), ('AUTH', 'Authentication'), ('ASSIGNMENT', 'Assignment'), ('WORKSPACE', 'Workspace'), ('BOOKING', 'Booking'), ('DIAGNOSTICS', 'Diagnostics'), ('AGENT', 'Agent'), ('OTHER', 'Other')], db_index=True, default='OTHER', max_length=32, verbose_name='Category')),
                ('message', models.TextField(verbose_name='Message')),
                ('json_payload', models.JSONField(blank=True, default=dict, help_text='Structured event context for diagnostics and support.', verbose_name='JSON payload')),
                ('correlation_id', models.UUIDField(blank=True, db_index=True, help_text='Links related events across heartbeat, bootstrap, and upload flows.', null=True, verbose_name='Correlation ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sync_logs', to='equipment.equipment', verbose_name='Equipment')),
                ('sync_agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='sync.departmentsyncagent', verbose_name='Sync agent')),
            ],
            options={
                'verbose_name': 'Sync Log',
                'verbose_name_plural': 'Sync Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentHeartbeat',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('reported_at', models.DateTimeField(db_index=True, verbose_name='Reported at')),
                ('cpu_percent', models.FloatField(blank=True, null=True, verbose_name='CPU percent')),
                ('memory_percent', models.FloatField(blank=True, null=True, verbose_name='Memory percent')),
                ('disk_percent', models.FloatField(blank=True, null=True, verbose_name='Disk percent')),
                ('queue_size', models.PositiveIntegerField(blank=True, null=True, verbose_name='Queue size')),
                ('active_workers', models.PositiveIntegerField(blank=True, null=True, verbose_name='Active workers')),
                ('last_upload_at', models.DateTimeField(blank=True, null=True, verbose_name='Last upload at')),
                ('agent_uptime_seconds', models.PositiveBigIntegerField(blank=True, help_text='Seconds since the agent process/service started.', null=True, verbose_name='Agent uptime (seconds)')),
                ('service_version', models.CharField(blank=True, default='', help_text='Installed Department Sync Agent service/package version.', max_length=50, verbose_name='Service version')),
                ('sqlite_schema_version', models.CharField(blank=True, default='', help_text='Local agent SQLite schema/migration version.', max_length=50, verbose_name='SQLite schema version')),
                ('windows_build', models.CharField(blank=True, default='', help_text='Host Windows build string (e.g. 10.0.26200).', max_length=100, verbose_name='Windows build')),
                ('hostname', models.CharField(blank=True, default='', help_text='Host machine hostname at heartbeat time.', max_length=200, verbose_name='Hostname')),
                ('reported_configuration_version', models.PositiveIntegerField(blank=True, help_text='configuration_version currently loaded by the agent.', null=True, verbose_name='Reported configuration version')),
                ('reported_schema_version', models.PositiveIntegerField(blank=True, help_text='Bootstrap schema_version currently understood by the agent.', null=True, verbose_name='Reported schema version')),
                ('status_message', models.CharField(blank=True, default='', max_length=500, verbose_name='Status message')),
                ('details', models.JSONField(blank=True, default=dict, help_text='Optional structured runtime counters.', verbose_name='Details')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('sync_agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heartbeats', to='sync.departmentsyncagent', verbose_name='Sync agent')),
            ],
            options={
                'verbose_name': 'Agent Heartbeat',
                'verbose_name_plural': 'Agent Heartbeats',
                'ordering': ['-reported_at'],
                'indexes': [models.Index(fields=['sync_agent', '-reported_at'], name='sync_agenth_sync_ag_9c379b_idx'), models.Index(fields=['reported_configuration_version'], name='sync_agenth_reporte_405b88_idx'), models.Index(fields=['reported_schema_version'], name='sync_agenth_reporte_e5ac4f_idx'), models.Index(fields=['hostname'], name='sync_agenth_hostnam_1fae0f_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='equipmentsyncprofile',
            index=models.Index(fields=['configuration_version'], name='sync_equipm_configu_192fc6_idx'),
        ),
        migrations.AddIndex(
            model_name='equipmentsyncprofile',
            index=models.Index(fields=['schema_version'], name='sync_equipm_schema__95fe01_idx'),
        ),
        migrations.AddIndex(
            model_name='equipmentsyncprofile',
            index=models.Index(fields=['sync_enabled', 'watch_enabled'], name='sync_equipm_sync_en_4cf851_idx'),
        ),
        migrations.AddIndex(
            model_name='agentassignment',
            index=models.Index(fields=['sync_agent', 'is_active'], name='sync_agenta_sync_ag_e3f296_idx'),
        ),
        migrations.AddIndex(
            model_name='agentassignment',
            index=models.Index(fields=['sync_profile', 'is_active'], name='sync_agenta_sync_pr_58cfec_idx'),
        ),
        migrations.AddConstraint(
            model_name='agentassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('sync_profile',), name='sync_agentassignment_one_active_per_profile'),
        ),
        migrations.AddConstraint(
            model_name='agentassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('sync_agent', 'sync_profile'), name='sync_agentassignment_unique_active_pair'),
        ),
        migrations.AddIndex(
            model_name='laboratory',
            index=models.Index(fields=['department', 'is_active'], name='sync_labora_departm_8aa7d6_idx'),
        ),
        migrations.AddConstraint(
            model_name='laboratory',
            constraint=models.UniqueConstraint(condition=models.Q(('code', ''), _negated=True), fields=('department', 'code'), name='sync_laboratory_unique_department_code'),
        ),
        migrations.AddIndex(
            model_name='departmentsyncagent',
            index=models.Index(fields=['department', 'is_active'], name='sync_depart_departm_bfaba8_idx'),
        ),
        migrations.AddIndex(
            model_name='departmentsyncagent',
            index=models.Index(fields=['laboratory', 'is_active'], name='sync_depart_laborat_441246_idx'),
        ),
        migrations.AddIndex(
            model_name='departmentsyncagent',
            index=models.Index(fields=['status', 'last_heartbeat_at'], name='sync_depart_status_8f610d_idx'),
        ),
        migrations.AddIndex(
            model_name='synclog',
            index=models.Index(fields=['sync_agent', '-created_at'], name='sync_synclo_sync_ag_577ca9_idx'),
        ),
        migrations.AddIndex(
            model_name='synclog',
            index=models.Index(fields=['equipment', '-created_at'], name='sync_synclo_equipme_8e44cc_idx'),
        ),
        migrations.AddIndex(
            model_name='synclog',
            index=models.Index(fields=['event_code', 'severity'], name='sync_synclo_event_c_898ef5_idx'),
        ),
        migrations.AddIndex(
            model_name='synclog',
            index=models.Index(fields=['category', 'severity'], name='sync_synclo_categor_a5fb40_idx'),
        ),
        migrations.AddIndex(
            model_name='synclog',
            index=models.Index(fields=['correlation_id', '-created_at'], name='sync_synclo_correla_68fc3d_idx'),
        ),
    ]
