# Generated by Django 5.2.9 on 2026-07-27 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0001_initial_sync_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncOperationsConsole',
            fields=[
            ],
            options={
                'verbose_name': 'Department Sync Operations',
                'verbose_name_plural': 'Department Sync Operations',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('sync.departmentsyncagent',),
        ),
    ]
