# Generated by Django 5.2.9 on 2026-07-27 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0002_sync_operations_console_proxy'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentsyncagent',
            name='access_token_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Access token expires at'),
        ),
        migrations.AddField(
            model_name='departmentsyncagent',
            name='access_token_hash',
            field=models.CharField(blank=True, default='', help_text='Hashed revocable access token. Never store the plaintext token.', max_length=128, verbose_name='Access token hash'),
        ),
        migrations.AddField(
            model_name='departmentsyncagent',
            name='access_token_issued_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Access token issued at'),
        ),
        migrations.AddField(
            model_name='departmentsyncagent',
            name='bootstrap_required',
            field=models.BooleanField(default=True, help_text='When set, heartbeat returns bootstrap_required until a successful bootstrap.', verbose_name='Bootstrap required'),
        ),
        migrations.AddField(
            model_name='departmentsyncagent',
            name='restart_required',
            field=models.BooleanField(default=False, help_text='When set, heartbeat returns restart_required.', verbose_name='Restart required'),
        ),
        migrations.AddField(
            model_name='departmentsyncagent',
            name='upgrade_required',
            field=models.BooleanField(default=False, help_text='When set, heartbeat returns upgrade_required.', verbose_name='Upgrade required'),
        ),
    ]
