# Generated by Django 5.2.9 on 2026-07-27 11:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0176_agent_command_and_workspace'),
        ('sync', '0003_agent_access_token_and_commands'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='synclog',
            name='category',
            field=models.CharField(choices=[('SYNC', 'Sync'), ('HEARTBEAT', 'Heartbeat'), ('UPLOAD', 'Upload'), ('BOOTSTRAP', 'Bootstrap'), ('AUTH', 'Authentication'), ('ASSIGNMENT', 'Assignment'), ('WORKSPACE', 'Workspace'), ('BOOKING', 'Booking'), ('DIAGNOSTICS', 'Diagnostics'), ('AGENT', 'Agent'), ('COMMAND', 'Command'), ('OTHER', 'Other')], db_index=True, default='OTHER', max_length=32, verbose_name='Category'),
        ),
        migrations.CreateModel(
            name='AgentCommand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('command_type', models.CharField(db_index=True, help_text='Extensible type key, e.g. CREATE_WORKSPACE, RETRY_UPLOAD.', max_length=64, verbose_name='Command type')),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], db_index=True, default='NORMAL', max_length=16, verbose_name='Priority')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACKNOWLEDGED', 'Acknowledged'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=20, verbose_name='Status')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Payload')),
                ('result_payload', models.JSONField(blank=True, default=dict, verbose_name='Result payload')),
                ('scheduled_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Scheduled at')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Started at')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed at')),
                ('retry_count', models.PositiveIntegerField(default=0, verbose_name='Retry count')),
                ('last_error', models.TextField(blank=True, default='', verbose_name='Last error')),
                ('correlation_id', models.UUIDField(blank=True, db_index=True, null=True, verbose_name='Correlation ID')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Row version')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Updated at')),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sync_commands', to='equipment.booking', verbose_name='Booking')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sync_commands', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sync_commands', to='equipment.equipment', verbose_name='Equipment')),
                ('sync_agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='sync.departmentsyncagent', verbose_name='Sync agent')),
            ],
            options={
                'verbose_name': 'Agent Command',
                'verbose_name_plural': 'Agent Commands',
                'ordering': ['-priority', 'created_at'],
                'indexes': [models.Index(fields=['sync_agent', 'status', '-created_at'], name='sync_agentc_sync_ag_e7d38d_idx'), models.Index(fields=['sync_agent', 'command_type', 'status'], name='sync_agentc_sync_ag_9419b3_idx'), models.Index(fields=['sync_agent', 'updated_at'], name='sync_agentc_sync_ag_73b79b_idx'), models.Index(fields=['status', 'priority', 'scheduled_at'], name='sync_agentc_status_f17378_idx')],
            },
        ),
        migrations.CreateModel(
            name='BookingWorkspace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workspace_name', models.CharField(max_length=255, verbose_name='Workspace name')),
                ('relative_folder', models.CharField(max_length=500, verbose_name='Relative folder')),
                ('expected_result_folder', models.CharField(blank=True, default='', max_length=500, verbose_name='Expected result folder')),
                ('sample_folder', models.CharField(blank=True, default='', max_length=500, verbose_name='Sample folder')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('READY', 'Ready'), ('ACTIVE', 'Active'), ('ARCHIVED', 'Archived'), ('FAILED', 'Failed')], db_index=True, default='READY', max_length=20, verbose_name='Status')),
                ('configuration_version', models.PositiveIntegerField(default=1, verbose_name='Configuration version')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Row version')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Updated at')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_workspaces', to='equipment.booking', verbose_name='Booking')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sync_workspaces', to='equipment.equipment', verbose_name='Equipment')),
                ('sync_agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspaces', to='sync.departmentsyncagent', verbose_name='Sync agent')),
            ],
            options={
                'verbose_name': 'Booking Workspace',
                'verbose_name_plural': 'Booking Workspaces',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['sync_agent', 'updated_at'], name='sync_bookin_sync_ag_989783_idx'), models.Index(fields=['equipment', 'status'], name='sync_bookin_equipme_62ce7b_idx')],
                'constraints': [models.UniqueConstraint(fields=('booking', 'sync_agent'), name='sync_bookingworkspace_unique_booking_agent')],
            },
        ),
    ]
