# Generated by Django 5.2.9 on 2026-07-27 11:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0176_agent_command_and_workspace'),
        ('sync', '0004_agent_command_and_workspace'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentUploadSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('agent_upload_id', models.UUIDField(db_index=True, help_text="UploadId from the agent's local UploadQueue.", verbose_name='Agent upload ID')),
                ('file_name', models.CharField(max_length=500, verbose_name='File name')),
                ('relative_path', models.CharField(blank=True, default='', max_length=1000, verbose_name='Relative path')),
                ('expected_size', models.BigIntegerField(default=0, verbose_name='Expected size (bytes)')),
                ('expected_chunk_count', models.PositiveIntegerField(default=0, verbose_name='Expected chunk count')),
                ('chunk_size', models.PositiveIntegerField(verbose_name='Chunk size (bytes)')),
                ('resume_token', models.CharField(db_index=True, max_length=64, verbose_name='Resume token')),
                ('server_path', models.CharField(max_length=1000, verbose_name='Server path')),
                ('bytes_received', models.BigIntegerField(default=0, verbose_name='Bytes received')),
                ('chunks_received', models.PositiveIntegerField(default=0, verbose_name='Chunks received')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RECEIVING', 'Receiving'), ('VERIFYING', 'Verifying'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=20, verbose_name='Status')),
                ('expires_at', models.DateTimeField(db_index=True, verbose_name='Expires at')),
                ('correlation_id', models.UUIDField(blank=True, db_index=True, null=True, verbose_name='Correlation ID')),
                ('last_error', models.TextField(blank=True, default='', verbose_name='Last error')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed at')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Row version')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Updated at')),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sync_upload_sessions', to='equipment.booking', verbose_name='Booking')),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sync_upload_sessions', to='equipment.equipment', verbose_name='Equipment')),
                ('sync_agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upload_sessions', to='sync.departmentsyncagent', verbose_name='Sync agent')),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='upload_sessions', to='sync.bookingworkspace', verbose_name='Workspace')),
            ],
            options={
                'verbose_name': 'Agent Upload Session',
                'verbose_name_plural': 'Agent Upload Sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentUploadChunk',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('chunk_index', models.PositiveIntegerField(verbose_name='Chunk index')),
                ('size', models.PositiveIntegerField(verbose_name='Size (bytes)')),
                ('checksum', models.CharField(blank=True, default='', max_length=128, verbose_name='Checksum')),
                ('received_at', models.DateTimeField(auto_now_add=True, verbose_name='Received at')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='sync.agentuploadsession', verbose_name='Upload session')),
            ],
            options={
                'verbose_name': 'Agent Upload Chunk',
                'verbose_name_plural': 'Agent Upload Chunks',
                'ordering': ['chunk_index'],
            },
        ),
        migrations.AddIndex(
            model_name='agentuploadsession',
            index=models.Index(fields=['sync_agent', 'status', '-created_at'], name='sync_agentu_sync_ag_07e389_idx'),
        ),
        migrations.AddIndex(
            model_name='agentuploadsession',
            index=models.Index(fields=['status', 'expires_at'], name='sync_agentu_status_ce15b2_idx'),
        ),
        migrations.AddIndex(
            model_name='agentuploadsession',
            index=models.Index(fields=['resume_token'], name='sync_agentu_resume__830d10_idx'),
        ),
        migrations.AddConstraint(
            model_name='agentuploadsession',
            constraint=models.UniqueConstraint(fields=('sync_agent', 'agent_upload_id'), name='sync_uploadsession_unique_agent_upload'),
        ),
        migrations.AddConstraint(
            model_name='agentuploadchunk',
            constraint=models.UniqueConstraint(fields=('session', 'chunk_index'), name='sync_uploadchunk_unique_session_index'),
        ),
    ]
