# Generated by Django 5.2.9 on 2026-07-27 13:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0006_result_processing_m10'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentApiKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key_id', models.CharField(db_index=True, max_length=64, verbose_name='Key ID')),
                ('key_hash', models.CharField(max_length=128, verbose_name='Key hash')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Expires at')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='Revoked at')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Agent API Key',
                'verbose_name_plural': 'Agent API Keys',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeviceCertificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('thumbprint', models.CharField(db_index=True, max_length=128, verbose_name='Thumbprint')),
                ('public_key', models.TextField(blank=True, default='', verbose_name='Public key')),
                ('certificate_pem', models.TextField(blank=True, default='', verbose_name='Certificate PEM')),
                ('issued_at', models.DateTimeField(verbose_name='Issued at')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Expires at')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='Revoked at')),
                ('is_current', models.BooleanField(db_index=True, default=True, verbose_name='Current')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
            ],
            options={
                'verbose_name': 'Device Certificate',
                'verbose_name_plural': 'Device Certificates',
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='SecurityAuditEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('event_code', models.CharField(db_index=True, max_length=32, verbose_name='Event code')),
                ('message', models.CharField(max_length=500, verbose_name='Message')),
                ('device_id', models.UUIDField(blank=True, db_index=True, null=True, verbose_name='Device ID')),
                ('agent_uuid', models.UUIDField(blank=True, db_index=True, null=True, verbose_name='Agent UUID')),
                ('correlation_id', models.UUIDField(blank=True, db_index=True, null=True, verbose_name='Correlation ID')),
                ('user_name', models.CharField(blank=True, default='', max_length=200, verbose_name='User')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='Details')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
            ],
            options={
                'verbose_name': 'Security Audit Event',
                'verbose_name_plural': 'Security Audit Events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='departmentsyncagent',
            name='api_key_hash',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='API key hash'),
        ),
        migrations.AddField(
            model_name='departmentsyncagent',
            name='api_key_rotated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='API key rotated at'),
        ),
        migrations.AddField(
            model_name='departmentsyncagent',
            name='certificate_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Certificate expires at'),
        ),
        migrations.AddField(
            model_name='departmentsyncagent',
            name='certificate_pem',
            field=models.TextField(blank=True, default='', verbose_name='Certificate PEM'),
        ),
        migrations.AddField(
            model_name='departmentsyncagent',
            name='certificate_revoked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Certificate revoked at'),
        ),
        migrations.AddField(
            model_name='departmentsyncagent',
            name='certificate_thumbprint',
            field=models.CharField(blank=True, db_index=True, default='', max_length=128, verbose_name='Certificate thumbprint'),
        ),
        migrations.AddField(
            model_name='departmentsyncagent',
            name='device_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='Stable device identity (normally equals machine_guid).', null=True, verbose_name='Device ID'),
        ),
        migrations.AddField(
            model_name='departmentsyncagent',
            name='device_public_key',
            field=models.TextField(blank=True, default='', verbose_name='Device public key (PEM/Base64)'),
        ),
        migrations.AddField(
            model_name='departmentsyncagent',
            name='security_registration_status',
            field=models.CharField(blank=True, default='UNREGISTERED', help_text='UNREGISTERED | REGISTERED | RENEWAL_PENDING | REVOKED', max_length=32, verbose_name='Security registration status'),
        ),
        migrations.AddField(
            model_name='departmentsyncagent',
            name='security_version',
            field=models.PositiveIntegerField(default=1, verbose_name='Security version'),
        ),
        migrations.AddField(
            model_name='departmentsyncagent',
            name='signing_required',
            field=models.BooleanField(default=False, help_text='When true, control-plane requests must include X-DSA-Signature headers.', verbose_name='Require request signatures'),
        ),
        migrations.AddField(
            model_name='departmentsyncagent',
            name='signing_secret_hash',
            field=models.CharField(blank=True, default='', help_text='Hashed HMAC signing secret. Never store plaintext.', max_length=128, verbose_name='Request signing secret hash'),
        ),
        migrations.AddIndex(
            model_name='departmentsyncagent',
            index=models.Index(fields=['certificate_thumbprint'], name='sync_depart_certifi_44187a_idx'),
        ),
        migrations.AddIndex(
            model_name='departmentsyncagent',
            index=models.Index(fields=['device_id'], name='sync_depart_device__882673_idx'),
        ),
        migrations.AddField(
            model_name='agentapikey',
            name='rotated_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rotations', to='sync.agentapikey', verbose_name='Rotated from'),
        ),
        migrations.AddField(
            model_name='agentapikey',
            name='sync_agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='sync.departmentsyncagent', verbose_name='Sync agent'),
        ),
        migrations.AddField(
            model_name='devicecertificate',
            name='sync_agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_certificates', to='sync.departmentsyncagent', verbose_name='Sync agent'),
        ),
        migrations.AddField(
            model_name='securityauditevent',
            name='sync_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_audit_events', to='sync.departmentsyncagent', verbose_name='Sync agent'),
        ),
        migrations.AddConstraint(
            model_name='agentapikey',
            constraint=models.UniqueConstraint(fields=('sync_agent', 'key_id'), name='sync_agentapikey_unique_key_id'),
        ),
        migrations.AddIndex(
            model_name='devicecertificate',
            index=models.Index(fields=['sync_agent', '-issued_at'], name='sync_device_sync_ag_d2526f_idx'),
        ),
        migrations.AddIndex(
            model_name='devicecertificate',
            index=models.Index(fields=['thumbprint', 'is_current'], name='sync_device_thumbpr_604f87_idx'),
        ),
        migrations.AddIndex(
            model_name='securityauditevent',
            index=models.Index(fields=['event_code', '-created_at'], name='sync_securi_event_c_bd6cb7_idx'),
        ),
        migrations.AddIndex(
            model_name='securityauditevent',
            index=models.Index(fields=['sync_agent', '-created_at'], name='sync_securi_sync_ag_ab0ac6_idx'),
        ),
    ]
