# Generated by Django 5.2.9 on 2026-07-27 14:22

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0177_result_processing_m10'),
        ('sync', '0008_offline_recovery_m13'),
        ('users', '0095_initial_payment_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentCapability',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('reported_at', models.DateTimeField(db_index=True, verbose_name='Reported at')),
                ('supported_plugins', models.JSONField(blank=True, default=list, verbose_name='Supported plugins')),
                ('plugin_versions', models.JSONField(blank=True, default=dict, verbose_name='Plugin versions')),
                ('storage_free_bytes', models.BigIntegerField(blank=True, null=True, verbose_name='Storage free bytes')),
                ('storage_total_bytes', models.BigIntegerField(blank=True, null=True, verbose_name='Storage total bytes')),
                ('cpu_percent', models.FloatField(blank=True, null=True, verbose_name='CPU percent')),
                ('memory_percent', models.FloatField(blank=True, null=True, verbose_name='Memory percent')),
                ('network_summary', models.CharField(blank=True, default='', max_length=200, verbose_name='Network summary')),
                ('windows_version', models.CharField(blank=True, default='', max_length=100, verbose_name='Windows version')),
                ('schema_version', models.PositiveIntegerField(blank=True, null=True, verbose_name='Schema version')),
                ('recovery_version', models.PositiveIntegerField(blank=True, null=True, verbose_name='Recovery version')),
                ('security_version', models.PositiveIntegerField(blank=True, null=True, verbose_name='Security version')),
                ('processing_capacity', models.PositiveIntegerField(blank=True, null=True, verbose_name='Processing capacity')),
                ('max_parallel_uploads', models.PositiveIntegerField(blank=True, null=True, verbose_name='Max parallel uploads')),
                ('max_parallel_processing', models.PositiveIntegerField(blank=True, null=True, verbose_name='Max parallel processing')),
                ('capabilities', models.JSONField(blank=True, default=dict, verbose_name='Capabilities')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
            ],
            options={
                'verbose_name': 'Agent Capability',
                'verbose_name_plural': 'Agent Capabilities',
                'ordering': ['-reported_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentStatistics',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('period_start', models.DateTimeField(db_index=True, verbose_name='Period start')),
                ('period_end', models.DateTimeField(db_index=True, verbose_name='Period end')),
                ('metrics', models.JSONField(blank=True, default=dict, verbose_name='Metrics')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
            ],
            options={
                'verbose_name': 'Agent Statistics',
                'verbose_name_plural': 'Agent Statistics',
                'ordering': ['-period_end'],
            },
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('code', models.CharField(blank=True, default='', max_length=50, verbose_name='Code')),
                ('address', models.CharField(blank=True, default='', max_length=500, verbose_name='Address')),
                ('campus', models.CharField(blank=True, default='', max_length=200, verbose_name='Campus')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Building',
                'verbose_name_plural': 'Buildings',
                'ordering': ['department__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DepartmentTopology',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Version')),
                ('snapshot', models.JSONField(blank=True, default=dict, verbose_name='Snapshot')),
                ('building_count', models.PositiveIntegerField(default=0, verbose_name='Building count')),
                ('agent_count', models.PositiveIntegerField(default=0, verbose_name='Agent count')),
                ('equipment_count', models.PositiveIntegerField(default=0, verbose_name='Equipment count')),
                ('generated_at', models.DateTimeField(auto_now=True, verbose_name='Generated at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
            ],
            options={
                'verbose_name': 'Department Topology',
                'verbose_name_plural': 'Department Topologies',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='EnterpriseAuditEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('event_code', models.CharField(db_index=True, max_length=32, verbose_name='Event code')),
                ('message', models.CharField(max_length=500, verbose_name='Message')),
                ('department_id', models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='Department ID')),
                ('building_id', models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='Building ID')),
                ('agent_id', models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='Agent ID')),
                ('correlation_id', models.UUIDField(blank=True, db_index=True, null=True, verbose_name='Correlation ID')),
                ('user_name', models.CharField(blank=True, default='', max_length=200, verbose_name='User')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='Details')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
            ],
            options={
                'verbose_name': 'Enterprise Audit Event',
                'verbose_name_plural': 'Enterprise Audit Events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SyncAgentAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assignment_type', models.CharField(choices=[('AUTOMATIC', 'Automatic'), ('MANUAL', 'Manual'), ('PRIORITY', 'Priority'), ('BUILDING', 'Building'), ('EQUIPMENT', 'Equipment'), ('DEPARTMENT', 'Department')], db_index=True, default='MANUAL', max_length=32, verbose_name='Assignment type')),
                ('priority', models.PositiveIntegerField(default=100, verbose_name='Priority')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Active')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('assigned_by', models.CharField(blank=True, default='', max_length=200, verbose_name='Assigned by')),
                ('correlation_id', models.UUIDField(blank=True, db_index=True, null=True, verbose_name='Correlation ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='Assigned at')),
                ('unassigned_at', models.DateTimeField(blank=True, null=True, verbose_name='Unassigned at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Sync Agent Enterprise Assignment',
                'verbose_name_plural': 'Sync Agent Enterprise Assignments',
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='SyncAgentGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('code', models.CharField(blank=True, default='', max_length=64, verbose_name='Code')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('filter_criteria', models.JSONField(blank=True, default=dict, verbose_name='Filter criteria')),
                ('custom_tags', models.JSONField(blank=True, default=list, verbose_name='Custom tags')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Sync Agent Group',
                'verbose_name_plural': 'Sync Agent Groups',
                'ordering': ['department__name', 'name'],
            },
        ),
        migrations.RenameIndex(
            model_name='agentconflictresolution',
            new_name='sync_agentc_sync_ag_4b6fbb_idx',
            old_name='sync_agentc_sync_ag_m13_idx',
        ),
        migrations.RenameIndex(
            model_name='agentrecoveryevent',
            new_name='sync_agentr_event_c_4f9849_idx',
            old_name='sync_agentr_event_c_m13_idx',
        ),
        migrations.RenameIndex(
            model_name='agentrecoveryevent',
            new_name='sync_agentr_sync_ag_6ab5f7_idx',
            old_name='sync_agentr_sync_ag_m13_idx',
        ),
        migrations.AddField(
            model_name='departmentsyncagent',
            name='custom_tags',
            field=models.JSONField(blank=True, default=list, help_text="Free-form tags for enterprise grouping (e.g. ['gpu','floor-2']).", verbose_name='Custom tags'),
        ),
        migrations.AddField(
            model_name='departmentsyncagent',
            name='max_parallel_processing',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Max parallel processing'),
        ),
        migrations.AddField(
            model_name='departmentsyncagent',
            name='max_parallel_uploads',
            field=models.PositiveIntegerField(default=2, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Max parallel uploads'),
        ),
        migrations.AddField(
            model_name='departmentsyncagent',
            name='processing_capacity',
            field=models.PositiveIntegerField(default=100, help_text='Relative capacity used by least-loaded scheduling (higher = more capacity).', verbose_name='Processing capacity score'),
        ),
        migrations.AddField(
            model_name='equipmentsyncprofile',
            name='backup_agent',
            field=models.ForeignKey(blank=True, help_text='Reserved for future HA failover.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backup_equipment_profiles', to='sync.departmentsyncagent', verbose_name='Backup agent'),
        ),
        migrations.AddField(
            model_name='equipmentsyncprofile',
            name='ownership_history',
            field=models.JSONField(blank=True, default=list, help_text='Append-only ownership change records.', verbose_name='Ownership history'),
        ),
        migrations.AddField(
            model_name='equipmentsyncprofile',
            name='primary_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_equipment_profiles', to='sync.departmentsyncagent', verbose_name='Primary agent'),
        ),
        migrations.AlterField(
            model_name='departmentsyncagent',
            name='status',
            field=models.CharField(choices=[('REGISTERED', 'Registered'), ('ENROLLED', 'Enrolled'), ('ACTIVE', 'Active'), ('MAINTENANCE', 'Maintenance'), ('DRAINING', 'Draining'), ('OFFLINE', 'Offline (operational)'), ('RECOVERING', 'Recovering'), ('RETIRED', 'Retired'), ('DELETED', 'Deleted'), ('DISABLED', 'Disabled'), ('REVOKED', 'Revoked')], db_index=True, default='REGISTERED', help_text='Lifecycle (REGISTERED / ENROLLED / ACTIVE / MAINTENANCE / DRAINING / OFFLINE / RECOVERING / RETIRED / DELETED / DISABLED / REVOKED). Connectivity online/offline is still derived from last_heartbeat_at.', max_length=20, verbose_name='Lifecycle status'),
        ),
        migrations.AlterField(
            model_name='synclog',
            name='category',
            field=models.CharField(choices=[('SYNC', 'Sync'), ('HEARTBEAT', 'Heartbeat'), ('UPLOAD', 'Upload'), ('BOOTSTRAP', 'Bootstrap'), ('AUTH', 'Authentication'), ('ASSIGNMENT', 'Assignment'), ('ENTERPRISE', 'Enterprise'), ('WORKSPACE', 'Workspace'), ('BOOKING', 'Booking'), ('DIAGNOSTICS', 'Diagnostics'), ('AGENT', 'Agent'), ('COMMAND', 'Command'), ('OTHER', 'Other')], db_index=True, default='OTHER', max_length=32, verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='agentcapability',
            name='sync_agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capability_snapshots', to='sync.departmentsyncagent', verbose_name='Sync agent'),
        ),
        migrations.AddField(
            model_name='agentstatistics',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_statistics', to='users.department', verbose_name='Department'),
        ),
        migrations.AddField(
            model_name='agentstatistics',
            name='sync_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='sync.departmentsyncagent', verbose_name='Sync agent'),
        ),
        migrations.AddField(
            model_name='building',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sync_buildings', to='users.department', verbose_name='Department'),
        ),
        migrations.AddField(
            model_name='agentstatistics',
            name='building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_statistics', to='sync.building', verbose_name='Building'),
        ),
        migrations.AddField(
            model_name='departmentsyncagent',
            name='building',
            field=models.ForeignKey(blank=True, help_text='Milestone 14 building topology node.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sync_agents', to='sync.building', verbose_name='Building'),
        ),
        migrations.AddField(
            model_name='equipmentsyncprofile',
            name='building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_sync_profiles', to='sync.building', verbose_name='Building'),
        ),
        migrations.AddField(
            model_name='departmenttopology',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_topologies', to='users.department', verbose_name='Department'),
        ),
        migrations.AddIndex(
            model_name='enterpriseauditevent',
            index=models.Index(fields=['event_code', '-created_at'], name='sync_enterp_event_c_499103_idx'),
        ),
        migrations.AddField(
            model_name='syncagentassignment',
            name='building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enterprise_assignments', to='sync.building', verbose_name='Building'),
        ),
        migrations.AddField(
            model_name='syncagentassignment',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enterprise_agent_assignments', to='users.department', verbose_name='Department'),
        ),
        migrations.AddField(
            model_name='syncagentassignment',
            name='equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enterprise_agent_assignments', to='equipment.equipment', verbose_name='Equipment'),
        ),
        migrations.AddField(
            model_name='syncagentassignment',
            name='laboratory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enterprise_assignments', to='sync.laboratory', verbose_name='Laboratory'),
        ),
        migrations.AddField(
            model_name='syncagentassignment',
            name='sync_agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enterprise_assignments', to='sync.departmentsyncagent', verbose_name='Sync agent'),
        ),
        migrations.AddField(
            model_name='syncagentgroup',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_agent_groups', to='users.department', verbose_name='Department'),
        ),
        migrations.AddField(
            model_name='syncagentassignment',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='sync.syncagentgroup', verbose_name='Agent group'),
        ),
        migrations.AddIndex(
            model_name='agentcapability',
            index=models.Index(fields=['sync_agent', '-reported_at'], name='sync_agentc_sync_ag_afc96e_idx'),
        ),
        migrations.AddIndex(
            model_name='building',
            index=models.Index(fields=['department', 'is_active'], name='sync_buildi_departm_7caa44_idx'),
        ),
        migrations.AddConstraint(
            model_name='building',
            constraint=models.UniqueConstraint(condition=models.Q(('code', ''), _negated=True), fields=('department', 'code'), name='sync_building_unique_department_code'),
        ),
        migrations.AddIndex(
            model_name='agentstatistics',
            index=models.Index(fields=['department', '-period_end'], name='sync_agents_departm_dee93f_idx'),
        ),
        migrations.AddIndex(
            model_name='agentstatistics',
            index=models.Index(fields=['sync_agent', '-period_end'], name='sync_agents_sync_ag_a9d96a_idx'),
        ),
        migrations.AddIndex(
            model_name='departmenttopology',
            index=models.Index(fields=['department', '-generated_at'], name='sync_depart_departm_35d438_idx'),
        ),
        migrations.AddIndex(
            model_name='syncagentgroup',
            index=models.Index(fields=['department', 'is_active'], name='sync_syncag_departm_62ce38_idx'),
        ),
        migrations.AddIndex(
            model_name='syncagentassignment',
            index=models.Index(fields=['department', 'is_active'], name='sync_syncag_departm_d4ab17_idx'),
        ),
        migrations.AddIndex(
            model_name='syncagentassignment',
            index=models.Index(fields=['sync_agent', 'is_active'], name='sync_syncag_sync_ag_3f27fe_idx'),
        ),
        migrations.AddIndex(
            model_name='syncagentassignment',
            index=models.Index(fields=['assignment_type', '-assigned_at'], name='sync_syncag_assignm_874f86_idx'),
        ),
    ]
