# Generated by Django 5.2.9 on 2026-07-27 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0177_result_processing_m10'),
        ('sync', '0012_instrument_experiments_m18'),
        ('users', '0095_initial_payment_models'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='agenthealthsnapshot',
            index=models.Index(fields=['-reported_at'], name='sync_agenth_reporte_95d3ec_idx'),
        ),
        migrations.AddIndex(
            model_name='agenthealthsnapshot',
            index=models.Index(fields=['overall_severity', '-reported_at'], name='sync_agenth_overall_de2a54_idx'),
        ),
        migrations.AddIndex(
            model_name='synclog',
            index=models.Index(fields=['severity', '-created_at'], name='sync_synclo_severit_953a79_idx'),
        ),
        migrations.AddIndex(
            model_name='synclog',
            index=models.Index(fields=['event_code', '-created_at'], name='sync_synclo_event_c_c9c5c8_idx'),
        ),
    ]
