#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

CELERY_CONCURRENCY="${CELERY_CONCURRENCY:-4}"
CELERY_PREFETCH_MULTIPLIER="${CELERY_PREFETCH_MULTIPLIER:-1}"
CELERY_MAX_TASKS_PER_CHILD="${CELERY_MAX_TASKS_PER_CHILD:-200}"

exec celery -A config.celery_app worker \
  -l INFO \
  --concurrency="${CELERY_CONCURRENCY}" \
  --prefetch-multiplier="${CELERY_PREFETCH_MULTIPLIER}" \
  --max-tasks-per-child="${CELERY_MAX_TASKS_PER_CHILD}"
