# Generated by Django 5.2.9 on 2026-09-26 04:17

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


CLEANUP_TASK_NAME = 'My Research stale upload cleanup (hourly)'


def create_cleanup_schedule(apps, schema_editor):
    CrontabSchedule = apps.get_model('django_celery_beat', 'CrontabSchedule')
    PeriodicTask = apps.get_model('django_celery_beat', 'PeriodicTask')
    crontab, _ = CrontabSchedule.objects.get_or_create(
        minute='35',
        hour='*',
        day_of_week='*',
        day_of_month='*',
        month_of_year='*',
    )
    if not PeriodicTask.objects.filter(name=CLEANUP_TASK_NAME).exists():
        # Created disabled; it is switched on as part of enabling MY_RESEARCH_ENABLED.
        PeriodicTask.objects.create(
            name=CLEANUP_TASK_NAME,
            task='my_research.cleanup_stale_uploads',
            crontab=crontab,
            enabled=False,
        )


def remove_cleanup_schedule(apps, schema_editor):
    PeriodicTask = apps.get_model('django_celery_beat', 'PeriodicTask')
    PeriodicTask.objects.filter(name=CLEANUP_TASK_NAME).delete()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0198_booking_result_views_and_data_shares'),
        ('django_celery_beat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchWorkspace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('last_activity_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='research_workspaces', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_activity_at'],
            },
        ),
        migrations.CreateModel(
            name='ResearchFolder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='my_research.researchfolder')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='folders', to='my_research.researchworkspace')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ResearchFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_name', models.CharField(max_length=255)),
                ('display_name', models.CharField(max_length=255)),
                ('storage_key', models.CharField(max_length=1024, unique=True)),
                ('declared_content_type', models.CharField(blank=True, default='', max_length=150)),
                ('detected_type', models.CharField(blank=True, default='', max_length=30)),
                ('size_bytes', models.BigIntegerField()),
                ('checksum_sha256', models.CharField(blank=True, default='', max_length=64)),
                ('checksum_verified', models.BooleanField(default=False)),
                ('etag', models.CharField(blank=True, default='', max_length=200)),
                ('etag_is_md5', models.BooleanField(default=False)),
                ('multipart_upload_id', models.CharField(blank=True, default='', max_length=1024)),
                ('status', models.CharField(choices=[('PENDING_UPLOAD', 'Pending upload'), ('AVAILABLE', 'Available'), ('FAILED', 'Failed'), ('DELETED', 'Deleted')], default='PENDING_UPLOAD', max_length=20)),
                ('failure_reason', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='research_files', to='equipment.booking')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='research_files', to=settings.AUTH_USER_MODEL)),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='files', to='my_research.researchfolder')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='files', to='my_research.researchworkspace')),
            ],
            options={
                'ordering': ['display_name'],
            },
        ),
        migrations.CreateModel(
            name='ResearchActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('WORKSPACE_CREATED', 'Workspace created'), ('WORKSPACE_UPDATED', 'Workspace updated'), ('WORKSPACE_ARCHIVED', 'Workspace archived'), ('WORKSPACE_RESTORED', 'Workspace restored'), ('FOLDER_CREATED', 'Folder created'), ('FOLDER_RENAMED', 'Folder renamed'), ('FOLDER_MOVED', 'Folder moved'), ('FOLDER_DELETED', 'Folder deleted'), ('FILE_UPLOADED', 'File uploaded'), ('FILE_RENAMED', 'File renamed'), ('FILE_MOVED', 'File moved'), ('FILE_DELETED', 'File deleted'), ('BOOKING_LINKED', 'Booking associated'), ('BOOKING_UNLINKED', 'Booking removed'), ('PUBLICATION_LINKED', 'Publication associated'), ('PUBLICATION_UNLINKED', 'Publication removed'), ('MEMBER_ADDED', 'Viewer added'), ('MEMBER_REMOVED', 'Viewer removed')], max_length=40)),
                ('target_type', models.CharField(blank=True, default='', max_length=20)),
                ('target_id', models.CharField(blank=True, default='', max_length=64)),
                ('target_label', models.CharField(blank=True, default='', max_length=300)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='my_research.researchworkspace')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResearchWorkspaceBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_workspace_links', to='equipment.booking')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_links', to='my_research.researchworkspace')),
            ],
            options={
                'ordering': ['-added_at'],
            },
        ),
        migrations.CreateModel(
            name='ResearchWorkspaceMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('OWNER', 'Owner'), ('VIEWER', 'Viewer')], default='VIEWER', max_length=10)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_memberships', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='my_research.researchworkspace')),
            ],
            options={
                'ordering': ['added_at'],
            },
        ),
        migrations.CreateModel(
            name='ResearchWorkspacePublication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_workspace_links', to='equipment.equipmentpublicationclaim')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publication_links', to='my_research.researchworkspace')),
            ],
            options={
                'ordering': ['-added_at'],
            },
        ),
        migrations.AddIndex(
            model_name='researchworkspace',
            index=models.Index(fields=['owner', 'status'], name='mr_ws_owner_status_idx'),
        ),
        migrations.AddIndex(
            model_name='researchworkspace',
            index=models.Index(fields=['-last_activity_at'], name='mr_ws_activity_idx'),
        ),
        migrations.AddIndex(
            model_name='researchfolder',
            index=models.Index(fields=['workspace', 'parent', 'deleted_at'], name='mr_folder_parent_idx'),
        ),
        migrations.AddConstraint(
            model_name='researchfolder',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('parent__isnull', False)), fields=('workspace', 'parent', 'name'), name='mr_uniq_folder_name_in_parent'),
        ),
        migrations.AddConstraint(
            model_name='researchfolder',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('parent__isnull', True)), fields=('workspace', 'name'), name='mr_uniq_folder_name_at_root'),
        ),
        migrations.AddIndex(
            model_name='researchfile',
            index=models.Index(fields=['workspace', 'folder', 'status'], name='mr_file_folder_idx'),
        ),
        migrations.AddIndex(
            model_name='researchfile',
            index=models.Index(fields=['workspace', 'status', '-created_at'], name='mr_file_recent_idx'),
        ),
        migrations.AddIndex(
            model_name='researchfile',
            index=models.Index(fields=['status', 'created_at'], name='mr_file_cleanup_idx'),
        ),
        migrations.AddIndex(
            model_name='researchfile',
            index=models.Index(fields=['uploaded_by', 'status'], name='mr_file_uploader_idx'),
        ),
        migrations.AddIndex(
            model_name='researchfile',
            index=models.Index(fields=['booking'], name='mr_file_booking_idx'),
        ),
        migrations.AddIndex(
            model_name='researchactivity',
            index=models.Index(fields=['workspace', '-created_at'], name='mr_activity_ws_idx'),
        ),
        migrations.AddConstraint(
            model_name='researchworkspacebooking',
            constraint=models.UniqueConstraint(fields=('workspace', 'booking'), name='mr_uniq_workspace_booking'),
        ),
        migrations.AddIndex(
            model_name='researchworkspacemember',
            index=models.Index(fields=['user', 'revoked_at'], name='mr_member_user_idx'),
        ),
        migrations.AddConstraint(
            model_name='researchworkspacemember',
            constraint=models.UniqueConstraint(condition=models.Q(('revoked_at__isnull', True)), fields=('workspace', 'user'), name='mr_uniq_active_member'),
        ),
        migrations.AddConstraint(
            model_name='researchworkspacemember',
            constraint=models.UniqueConstraint(condition=models.Q(('revoked_at__isnull', True), ('role', 'OWNER')), fields=('workspace',), name='mr_uniq_active_owner'),
        ),
        migrations.AddConstraint(
            model_name='researchworkspacepublication',
            constraint=models.UniqueConstraint(fields=('workspace', 'claim'), name='mr_uniq_workspace_publication'),
        ),
        migrations.RunPython(create_cleanup_schedule, remove_cleanup_schedule),
    ]
