# Generated by Django 5.2.9 on 2026-09-26 17:50
# Additive only: new tables, indexes and a disabled reminder schedule. Existing tables are untouched.

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


REMINDER_TASK_NAME = 'My Research group update reminders (daily)'


def create_reminder_schedule(apps, schema_editor):
    CrontabSchedule = apps.get_model('django_celery_beat', 'CrontabSchedule')
    PeriodicTask = apps.get_model('django_celery_beat', 'PeriodicTask')
    crontab, _ = CrontabSchedule.objects.get_or_create(
        minute='15',
        hour='8',
        day_of_week='*',
        day_of_month='*',
        month_of_year='*',
    )
    if not PeriodicTask.objects.filter(name=REMINDER_TASK_NAME).exists():
        # Created disabled; it is switched on as part of enabling MY_RESEARCH_GROUPS_ENABLED.
        PeriodicTask.objects.create(
            name=REMINDER_TASK_NAME,
            task='my_research.group_update_reminders',
            crontab=crontab,
            enabled=False,
        )


def remove_reminder_schedule(apps, schema_editor):
    PeriodicTask = apps.get_model('django_celery_beat', 'PeriodicTask')
    PeriodicTask.objects.filter(name=REMINDER_TASK_NAME).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0198_booking_result_views_and_data_shares'),
        ('my_research', '0002_workspace_booking_folder'),
        ('django_celery_beat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('short_code', models.CharField(blank=True, default='', max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_research_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ResearchGroupActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Not started'), ('IN_PROGRESS', 'In progress'), ('WAITING', 'Waiting'), ('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under review'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='NOT_STARTED', max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High')], default='NORMAL', max_length=10)),
                ('progress_percent', models.PositiveSmallIntegerField(default=0)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='research_group_activities', to='equipment.booking')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='research_group_activities', to='equipment.equipment')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activities', to='my_research.researchgroup')),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_activities', to='my_research.researchworkspace')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResearchGroupActivityAssignee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Not started'), ('IN_PROGRESS', 'In progress'), ('WAITING', 'Waiting'), ('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under review'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='NOT_STARTED', max_length=20)),
                ('progress_percent', models.PositiveSmallIntegerField(default=0)),
                ('note', models.TextField(blank=True, default='')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('removed_at', models.DateTimeField(blank=True, null=True)),
                ('due_reminder_sent_at', models.DateTimeField(blank=True, null=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignees', to='my_research.researchgroupactivity')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='research_group_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='ResearchGroupCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='categories', to='my_research.researchgroup')),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='researchgroupactivity',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='my_research.researchgroupcategory'),
        ),
        migrations.CreateModel(
            name='ResearchGroupEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('GROUP_CREATED', 'Group created'), ('GROUP_UPDATED', 'Group updated'), ('GROUP_ARCHIVED', 'Group archived'), ('MEMBER_ADDED', 'Member added'), ('MEMBER_UPDATED', 'Member updated'), ('MEMBER_REMOVED', 'Member removed'), ('CATEGORY_CREATED', 'Category created'), ('CATEGORY_UPDATED', 'Category updated'), ('ACTIVITY_CREATED', 'Activity created'), ('ACTIVITY_ASSIGNED', 'Activity assigned'), ('ACTIVITY_UNASSIGNED', 'Activity unassigned'), ('ACTIVITY_UPDATED', 'Activity updated'), ('ACTIVITY_COMPLETED', 'Activity completed'), ('PROGRESS_UPDATED', 'Progress updated'), ('UPDATE_REQUESTED', 'Update requested'), ('UPDATE_SUBMITTED', 'Update submitted'), ('UPDATE_REVIEWED', 'Update reviewed'), ('UPDATE_CANCELLED', 'Update request cancelled'), ('WORKSPACE_LINKED', 'Workspace linked'), ('WORKSPACE_UNLINKED', 'Workspace unlinked'), ('PUBLICATION_LINKED', 'Publication linked'), ('PUBLICATION_UNLINKED', 'Publication unlinked')], max_length=40)),
                ('target_type', models.CharField(blank=True, default='', max_length=20)),
                ('target_id', models.CharField(blank=True, default='', max_length=64)),
                ('target_label', models.CharField(blank=True, default='', max_length=300)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='my_research.researchgroup')),
                ('subject_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResearchGroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('OWNER', 'Owner'), ('MANAGER', 'Manager'), ('MEMBER', 'Member')], default='MEMBER', max_length=10)),
                ('member_type', models.CharField(choices=[('PHD', 'Ph.D.'), ('MTECH', 'M.Tech'), ('BTECH', 'B.Tech'), ('RESEARCH_ASSOCIATE', 'Research Associate'), ('JRF', 'JRF'), ('SRF', 'SRF'), ('PROJECT_STAFF', 'Project Staff'), ('INTERN', 'Intern'), ('OTHER', 'Other')], default='OTHER', max_length=30)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('LEFT', 'Left')], default='ACTIVE', max_length=10)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='my_research.researchgroupcategory')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='members', to='my_research.researchgroup')),
                ('removed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='research_group_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['joined_at'],
            },
        ),
        migrations.CreateModel(
            name='ResearchGroupPublication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_group_links', to='equipment.equipmentpublicationclaim')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publication_links', to='my_research.researchgroup')),
            ],
            options={
                'ordering': ['-added_at'],
            },
        ),
        migrations.CreateModel(
            name='ResearchGroupWorkspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_links', to='my_research.researchgroup')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_links', to='my_research.researchworkspace')),
            ],
            options={
                'ordering': ['-added_at'],
            },
        ),
        migrations.CreateModel(
            name='ResearchUpdate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('work_completed', models.TextField(blank=True, default='')),
                ('current_status', models.TextField(blank=True, default='')),
                ('blockers', models.TextField(blank=True, default='')),
                ('next_steps', models.TextField(blank=True, default='')),
                ('progress_percent', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('expected_completion_date', models.DateField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ResearchUpdateRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250)),
                ('instructions', models.TextField(blank=True, default='')),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUBMITTED', 'Submitted'), ('REVIEWED', 'Reviewed'), ('CANCELLED', 'Cancelled'), ('OVERDUE', 'Overdue')], default='PENDING', max_length=20)),
                ('recurrence', models.CharField(choices=[('NONE', 'One-time'), ('WEEKLY', 'Weekly'), ('FORTNIGHTLY', 'Fortnightly'), ('MONTHLY', 'Monthly')], default='NONE', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_comment', models.TextField(blank=True, default='')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('overdue_notified_at', models.DateTimeField(blank=True, null=True)),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='update_requests', to='my_research.researchgroupactivity')),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='research_update_requests', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='update_requests', to='my_research.researchgroup')),
                ('recurrence_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurrences', to='my_research.researchupdaterequest')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='ResearchUpdateAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_name', models.CharField(max_length=255)),
                ('display_name', models.CharField(max_length=255)),
                ('storage_key', models.CharField(max_length=1024, unique=True)),
                ('declared_content_type', models.CharField(blank=True, default='', max_length=150)),
                ('detected_type', models.CharField(blank=True, default='', max_length=30)),
                ('size_bytes', models.BigIntegerField()),
                ('status', models.CharField(choices=[('PENDING_UPLOAD', 'Pending upload'), ('AVAILABLE', 'Available'), ('FAILED', 'Failed'), ('DELETED', 'Deleted')], default='PENDING_UPLOAD', max_length=20)),
                ('failure_reason', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('update', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attachments', to='my_research.researchupdate')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attachments', to='my_research.researchupdaterequest')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='researchupdate',
            name='request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='submission', to='my_research.researchupdaterequest'),
        ),
        migrations.AddIndex(
            model_name='researchgroup',
            index=models.Index(fields=['owner', 'status'], name='mr_grp_owner_status_idx'),
        ),
        migrations.AddIndex(
            model_name='researchgroup',
            index=models.Index(fields=['status'], name='mr_grp_status_idx'),
        ),
        migrations.AddIndex(
            model_name='researchgroupactivityassignee',
            index=models.Index(fields=['user', 'removed_at'], name='mr_grp_assignee_user_idx'),
        ),
        migrations.AddConstraint(
            model_name='researchgroupactivityassignee',
            constraint=models.UniqueConstraint(condition=models.Q(('removed_at__isnull', True)), fields=('activity', 'user'), name='mr_grp_uniq_active_assignee'),
        ),
        migrations.AddIndex(
            model_name='researchgroupcategory',
            index=models.Index(fields=['group', 'active', 'display_order'], name='mr_grp_category_idx'),
        ),
        migrations.AddConstraint(
            model_name='researchgroupcategory',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True)), fields=('group', 'name'), name='mr_grp_uniq_active_category'),
        ),
        migrations.AddIndex(
            model_name='researchgroupactivity',
            index=models.Index(fields=['group', 'status'], name='mr_grp_act_status_idx'),
        ),
        migrations.AddIndex(
            model_name='researchgroupactivity',
            index=models.Index(fields=['group', 'due_date'], name='mr_grp_act_due_idx'),
        ),
        migrations.AddIndex(
            model_name='researchgroupevent',
            index=models.Index(fields=['group', '-created_at'], name='mr_grp_event_idx'),
        ),
        migrations.AddIndex(
            model_name='researchgroupevent',
            index=models.Index(fields=['subject_user', '-created_at'], name='mr_grp_event_subject_idx'),
        ),
        migrations.AddIndex(
            model_name='researchgroupmember',
            index=models.Index(fields=['user', 'status'], name='mr_grp_member_user_idx'),
        ),
        migrations.AddIndex(
            model_name='researchgroupmember',
            index=models.Index(fields=['group', 'status'], name='mr_grp_member_group_idx'),
        ),
        migrations.AddConstraint(
            model_name='researchgroupmember',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('group', 'user'), name='mr_grp_uniq_active_member'),
        ),
        migrations.AddConstraint(
            model_name='researchgrouppublication',
            constraint=models.UniqueConstraint(fields=('group', 'claim'), name='mr_grp_uniq_publication'),
        ),
        migrations.AddConstraint(
            model_name='researchgroupworkspace',
            constraint=models.UniqueConstraint(fields=('group', 'workspace'), name='mr_grp_uniq_workspace'),
        ),
        migrations.AddIndex(
            model_name='researchupdaterequest',
            index=models.Index(fields=['group', 'status'], name='mr_grp_req_status_idx'),
        ),
        migrations.AddIndex(
            model_name='researchupdaterequest',
            index=models.Index(fields=['assigned_to', 'status'], name='mr_grp_req_assignee_idx'),
        ),
        migrations.AddIndex(
            model_name='researchupdaterequest',
            index=models.Index(fields=['status', 'due_date'], name='mr_grp_req_due_idx'),
        ),
        migrations.AddIndex(
            model_name='researchupdateattachment',
            index=models.Index(fields=['request', 'status'], name='mr_grp_attach_req_idx'),
        ),
        migrations.RunPython(create_reminder_schedule, remove_reminder_schedule),
    ]
