# Generated by Django 5.2.9 on 2026-10-05 03:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='procurementmanagementconfiguration',
            name='pilot_mode',
            field=models.BooleanField(default=True, help_text='While on, only the pilot users below can use the module in this department; everyone else sees it as disabled.'),
        ),
        migrations.AddField(
            model_name='procurementmanagementconfiguration',
            name='pilot_users',
            field=models.ManyToManyField(blank=True, related_name='procurement_pilot_configs', to=settings.AUTH_USER_MODEL),
        ),
    ]
