# Generated by Django 5.2.9 on 2026-10-10 08:27

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0244_equipment_flash_messages'),
        ('procurement_management', '0002_pilot_gate'),
        ('sync', '0018_equipment_pc_ip_reservation'),
        ('users', '0138_sric_wallet_recharge_quiet_window'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verified_on', models.DateField(default=django.utils.timezone.localdate)),
                ('result', models.CharField(choices=[('FOUND', 'Found (in order)'), ('FOUND_DAMAGED', 'Found — damaged / unserviceable'), ('SHORTAGE', 'Found — quantity short'), ('NOT_FOUND', 'Not found')], max_length=16)),
                ('condition', models.CharField(blank=True, choices=[('NEW', 'New'), ('GOOD', 'Good / serviceable'), ('FAIR', 'Fair'), ('POOR', 'Poor / needs repair'), ('UNSERVICEABLE', 'Unserviceable')], default='', max_length=16)),
                ('quantity_found', models.PositiveIntegerField(blank=True, null=True)),
                ('location_seen', models.CharField(blank=True, default='', max_length=255)),
                ('remarks', models.TextField(blank=True, default='')),
                ('method', models.CharField(choices=[('SCAN', 'QR scan'), ('MANUAL', 'Manual'), ('IMPORT', 'Imported')], default='MANUAL', max_length=8)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-verified_on', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ItemEquipmentLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usage', models.CharField(choices=[('CONSUMABLE', 'Consumable'), ('SPARE', 'Spare part'), ('ACCESSORY', 'Accessory')], default='CONSUMABLE', max_length=12)),
                ('typical_quantity', models.DecimalField(decimal_places=3, default=Decimal('1.000'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))])),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['usage', 'item__name'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('archive_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=40, unique=True)),
                ('kind', models.CharField(choices=[('BREAKDOWN', 'Breakdown repair'), ('PREVENTIVE', 'Preventive maintenance'), ('CALIBRATION', 'Calibration'), ('AMC_VISIT', 'AMC / CMC visit'), ('UPGRADE', 'Upgrade / modification'), ('OTHER', 'Other')], default='BREAKDOWN', max_length=12)),
                ('downtime_start', models.DateTimeField(blank=True, null=True)),
                ('downtime_end', models.DateTimeField(blank=True, null=True)),
                ('cause', models.TextField(blank=True, default='')),
                ('action_taken', models.TextField(blank=True, default='')),
                ('service_provider', models.CharField(blank=True, default='', max_length=255)),
                ('service_report_reference', models.CharField(blank=True, default='', max_length=120)),
                ('service_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('other_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('parts_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('under_warranty_or_amc', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-downtime_start', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VerificationCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=40, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('financial_year', models.CharField(max_length=7)),
                ('committee', models.TextField(blank=True, default='', help_text='Verification committee members.')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN', max_length=8)),
                ('started_on', models.DateField(default=django.utils.timezone.localdate)),
                ('closed_on', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-started_on', '-id'],
            },
        ),
        migrations.AddField(
            model_name='asset',
            name='amc_until',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='condition',
            field=models.CharField(blank=True, choices=[('NEW', 'New'), ('GOOD', 'Good / serviceable'), ('FAIR', 'Fair'), ('POOR', 'Poor / needs repair'), ('UNSERVICEABLE', 'Unserviceable')], db_default='', default='', max_length=16),
        ),
        migrations.AddField(
            model_name='asset',
            name='depreciation_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='funding_source',
            field=models.CharField(blank=True, db_default='', default='', max_length=255),
        ),
        migrations.AddField(
            model_name='asset',
            name='installation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='invoice_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='invoice_number',
            field=models.CharField(blank=True, db_default='', default='', max_length=80),
        ),
        migrations.AddField(
            model_name='asset',
            name='last_verification_result',
            field=models.CharField(blank=True, choices=[('FOUND', 'Found (in order)'), ('FOUND_DAMAGED', 'Found — damaged / unserviceable'), ('SHORTAGE', 'Found — quantity short'), ('NOT_FOUND', 'Not found')], db_default='', default='', max_length=16),
        ),
        migrations.AddField(
            model_name='asset',
            name='last_verified_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='legacy_ref',
            field=models.CharField(blank=True, db_default='', default='', help_text='Old stock / asset number.', max_length=120),
        ),
        migrations.AddField(
            model_name='asset',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Main asset this accessory / sub-asset belongs to.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accessories', to='procurement_management.asset'),
        ),
        migrations.AddField(
            model_name='asset',
            name='po_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='po_number',
            field=models.CharField(blank=True, db_default='', default='', max_length=80),
        ),
        migrations.AddField(
            model_name='asset',
            name='project_code',
            field=models.CharField(blank=True, db_default='', default='', max_length=80),
        ),
        migrations.AddField(
            model_name='asset',
            name='quantity',
            field=models.PositiveIntegerField(db_default=1, default=1),
        ),
        migrations.AddField(
            model_name='asset',
            name='register_entry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='register_page',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='register_serial',
            field=models.CharField(blank=True, db_default='', default='', help_text='Serial number on the page.', max_length=20),
        ),
        migrations.AddField(
            model_name='asset',
            name='supplier_name',
            field=models.CharField(blank=True, db_default='', default='', max_length=255),
        ),
        migrations.AddField(
            model_name='asset',
            name='useful_life_years',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='forward_note',
            field=models.TextField(blank=True, db_default='', default=''),
        ),
        migrations.AddField(
            model_name='invoice',
            name='forwarded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoice',
            name='forwarded_to_accounts_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='part_number',
            field=models.CharField(blank=True, db_default='', default='', help_text='Make / part number (spares).', max_length=120),
        ),
        migrations.AddField(
            model_name='item',
            name='tracks_batch',
            field=models.BooleanField(db_default=False, default=False, help_text='Record batch / lot and expiry on receipts.'),
        ),
        migrations.AddField(
            model_name='procurementmanagementconfiguration',
            name='accounts_budget_check',
            field=models.BooleanField(db_default=False, default=False, help_text='Add an Accounts In Charge budget-availability check before HOD approval.'),
        ),
        migrations.AddField(
            model_name='procurementmanagementconfiguration',
            name='direct_purchase_limit',
            field=models.DecimalField(db_default=Decimal('50000.00'), decimal_places=2, default=Decimal('50000.00'), help_text='GFR Rule 154: purchase without quotation up to this value (incl. GST).', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='procurementmanagementconfiguration',
            name='limited_tender_limit',
            field=models.DecimalField(db_default=Decimal('5000000.00'), decimal_places=2, default=Decimal('5000000.00'), help_text='GFR Rule 162: limited tender enquiry up to this value; open tender above.', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='procurementmanagementconfiguration',
            name='purchase_committee_limit',
            field=models.DecimalField(db_default=Decimal('1000000.00'), decimal_places=2, default=Decimal('1000000.00'), help_text='GFR Rule 155: purchase through a local purchase committee up to this value.', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='procurementrecord',
            name='gem_reference',
            field=models.CharField(blank=True, db_default='', default='', help_text='GeM order / contract number.', max_length=120),
        ),
        migrations.AddField(
            model_name='procurementrecord',
            name='purchase_mode',
            field=models.CharField(blank=True, choices=[('DIRECT', 'Direct purchase (without quotation)'), ('GEM', 'GeM (Government e-Marketplace)'), ('PURCHASE_COMMITTEE', 'Local Purchase Committee'), ('LIMITED_TENDER', 'Limited tender'), ('OPEN_TENDER', 'Open / advertised tender'), ('SINGLE_TENDER', 'Single tender'), ('PROPRIETARY', 'Proprietary article (PAC)'), ('RATE_CONTRACT', 'Rate contract')], db_default='', default='', max_length=24),
        ),
        migrations.AddField(
            model_name='procurementrecord',
            name='purchase_mode_reason',
            field=models.TextField(blank=True, db_default='', default=''),
        ),
        migrations.AddField(
            model_name='procurementroleassignment',
            name='equipment_ids',
            field=models.JSONField(blank=True, db_default=[], default=list, help_text='Lab In Charge: equipment in their charge (empty = every equipment of the department).'),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='disruption_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pm_requests', to='equipment.disruptionevent'),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='stage_entered_at',
            field=models.DateTimeField(blank=True, help_text='When the request reached its current status (SLA ageing).', null=True),
        ),
        migrations.AddField(
            model_name='purchaserequestline',
            name='added_by_stores',
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AddField(
            model_name='purchaserequestline',
            name='fulfilment',
            field=models.CharField(blank=True, choices=[('', 'Not decided'), ('STOCK', 'Issue from stock'), ('PROCURE', 'Procure')], db_default='', default='', max_length=10),
        ),
        migrations.AddField(
            model_name='purchaserequestline',
            name='store_note',
            field=models.TextField(blank=True, db_default='', default=''),
        ),
        migrations.AddField(
            model_name='purchaserequestline',
            name='store_original',
            field=models.JSONField(blank=True, db_default={}, default=dict, help_text="The requester's values before OC Stores modified the line."),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='batch_number',
            field=models.CharField(blank=True, db_default='', default='', max_length=60),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pm_stock_transactions', to='equipment.equipment'),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='reason_code',
            field=models.CharField(blank=True, choices=[('DAMAGED', 'Damaged / broken'), ('EXPIRED', 'Expired'), ('COUNT_CORRECTION', 'Physical count correction'), ('LOST', 'Lost / pilferage'), ('CONSUMED_IN_REPAIR', 'Used in repair / maintenance'), ('OTHER', 'Other')], db_default='', default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='approvalaction',
            name='action',
            field=models.CharField(choices=[('SUBMIT', 'Submitted'), ('APPROVE', 'Approved'), ('REJECT', 'Rejected'), ('HOLD', 'Put on hold'), ('RESUME', 'Resumed'), ('RESUBMIT', 'Resubmitted'), ('CANCEL', 'Cancelled'), ('OFFLINE_APPROVE', 'Approved offline'), ('OFFLINE_REJECT', 'Rejected offline'), ('STORES_AVAILABLE', 'Stores: available'), ('STORES_PARTIAL', 'Stores: partially available'), ('STORES_NOT_AVAILABLE', 'Stores: not available'), ('ISSUE', 'Issued from stores'), ('START_PROCUREMENT', 'Procurement started'), ('MARK_PURCHASED', 'Purchased'), ('INVOICE_RECORDED', 'Bill recorded'), ('COMPLETE', 'Completed'), ('SEND_FOR_APPROVAL', 'Sent for approval'), ('REAPPROVAL_REQUIRED', 'Re-approval required (bill variance)'), ('STORES_EDIT', 'Lines modified by OC Stores')], max_length=24),
        ),
        migrations.AlterField(
            model_name='approvalaction',
            name='stage',
            field=models.CharField(choices=[('REQUESTER', 'Requester'), ('OIC', 'OIC'), ('STORES', 'OC Stores'), ('HOD', 'HOD / Competent Authority'), ('OFFICE', 'Office'), ('SYSTEM', 'System'), ('ACCOUNTS', 'Accounts In Charge')], max_length=12),
        ),
        migrations.AlterField(
            model_name='procurementroleassignment',
            name='role',
            field=models.CharField(choices=[('OC_STORES', 'OC Stores'), ('OFFICE', 'Office'), ('HOD', 'HOD / Competent Authority'), ('AUDITOR', 'Auditor (read-only)'), ('ACCOUNTS', 'Accounts In Charge'), ('LAB_INCHARGE', 'Lab In Charge')], max_length=20),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='held_from_status',
            field=models.CharField(blank=True, choices=[('DRAFT', 'Draft'), ('PENDING_OIC', 'Pending OIC approval'), ('PENDING_STORES', 'Pending OC Stores review'), ('PENDING_HOD', 'Pending HOD approval'), ('PENDING_ACCOUNTS', 'Pending Accounts budget check'), ('ON_HOLD', 'On hold'), ('REJECTED', 'Rejected'), ('APPROVED', 'Approved'), ('STORES_AVAILABLE', 'Available in stores'), ('STORES_PARTIAL', 'Partially available in stores'), ('STORES_NOT_AVAILABLE', 'Not available in stores'), ('ISSUED', 'Issued'), ('IN_PROCUREMENT', 'In procurement'), ('AWAITING_INVOICE', 'Purchased — awaiting bill'), ('AWAITING_RECEIPT', 'Bill recorded — awaiting receipt / asset entry'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='', max_length=24),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='raised_as_role',
            field=models.CharField(choices=[('LAB_OPERATOR', 'Lab Operator'), ('OIC', 'Officer in Charge'), ('OC_STORES', 'OC Stores'), ('OFFICE', 'Office'), ('HOD', 'HOD / Competent Authority'), ('AUDITOR', 'Auditor (read-only)'), ('MAIN_ADMIN', 'Main Administrator'), ('ACCOUNTS', 'Accounts In Charge'), ('LAB_INCHARGE', 'Lab In Charge')], max_length=20),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_OIC', 'Pending OIC approval'), ('PENDING_STORES', 'Pending OC Stores review'), ('PENDING_HOD', 'Pending HOD approval'), ('PENDING_ACCOUNTS', 'Pending Accounts budget check'), ('ON_HOLD', 'On hold'), ('REJECTED', 'Rejected'), ('APPROVED', 'Approved'), ('STORES_AVAILABLE', 'Available in stores'), ('STORES_PARTIAL', 'Partially available in stores'), ('STORES_NOT_AVAILABLE', 'Not available in stores'), ('ISSUED', 'Issued'), ('IN_PROCUREMENT', 'In procurement'), ('AWAITING_INVOICE', 'Purchased — awaiting bill'), ('AWAITING_RECEIPT', 'Bill recorded — awaiting receipt / asset entry'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=24),
        ),
        migrations.CreateModel(
            name='AssetDisposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=40, unique=True)),
                ('action', models.CharField(choices=[('CONDEMN', 'Condemned (survey / condemnation board)'), ('WRITE_OFF', 'Written off (loss / shortage)'), ('DISPOSE', 'Disposed')], max_length=10)),
                ('mode', models.CharField(blank=True, choices=[('AUCTION', 'Public auction / e-auction'), ('SCRAP', 'Sold as scrap'), ('BUY_BACK', 'Buy-back / exchange'), ('TRANSFER', 'Transferred (free of cost)'), ('WRITE_OFF', 'Written off'), ('OTHER', 'Other')], default='', max_length=12)),
                ('board_reference', models.CharField(blank=True, default='', max_length=255)),
                ('sanction_reference', models.CharField(blank=True, default='', max_length=255)),
                ('sanction_date', models.DateField(blank=True, null=True)),
                ('book_value', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=14, null=True)),
                ('realised_value', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=14, null=True)),
                ('from_status', models.CharField(blank=True, default='', max_length=24)),
                ('to_status', models.CharField(max_length=24)),
                ('remarks', models.TextField(blank=True, default='')),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disposals', to='procurement_management.asset')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pm_asset_disposals', to='users.department')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-recorded_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AssetRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('archive_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('register_type', models.CharField(choices=[('MAJOR', 'Major (fixed / non-consumable assets)'), ('MINOR', 'Minor (low-value / dead stock)'), ('LIMITED_LIFE', 'Limited-life assets'), ('CONSUMABLE', 'Consumable stock')], max_length=16)),
                ('code', models.CharField(help_text='Short code written on the register cover, e.g. MAJ-1.', max_length=40)),
                ('name', models.CharField(max_length=255)),
                ('volume', models.CharField(blank=True, default='', max_length=40)),
                ('opened_on', models.DateField(blank=True, null=True)),
                ('closed_on', models.DateField(blank=True, null=True)),
                ('total_pages', models.PositiveIntegerField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, default='')),
                ('active', models.BooleanField(default=True)),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('custodian', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pm_asset_registers', to='users.department')),
                ('laboratory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='sync.laboratory')),
            ],
            options={
                'ordering': ['register_type', 'code'],
            },
        ),
        migrations.AddField(
            model_name='asset',
            name='register',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='procurement_management.assetregister'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['register', 'register_page'], name='procurement_registe_7b16bc_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['asset_tag'], name='procurement_asset_t_26c18a_idx'),
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.UniqueConstraint(condition=models.Q(('is_archived', False), ('register__isnull', False), ('register_page__isnull', False), models.Q(('register_serial', ''), _negated=True)), fields=('register', 'register_page', 'register_serial'), name='pm_asset_unique_register_entry'),
        ),
        migrations.AddField(
            model_name='assetverification',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='verifications', to='procurement_management.asset'),
        ),
        migrations.AddField(
            model_name='assetverification',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pm_asset_verifications', to='users.department'),
        ),
        migrations.AddField(
            model_name='assetverification',
            name='verified_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='itemequipmentlink',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='itemequipmentlink',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pm_item_links', to='users.department'),
        ),
        migrations.AddField(
            model_name='itemequipmentlink',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pm_item_links', to='equipment.equipment'),
        ),
        migrations.AddField(
            model_name='itemequipmentlink',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_links', to='procurement_management.item'),
        ),
        migrations.AddField(
            model_name='maintenancerecord',
            name='amc_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_records', to='procurement_management.amcservicerecord'),
        ),
        migrations.AddField(
            model_name='maintenancerecord',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='maintenancerecord',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_records', to='procurement_management.asset'),
        ),
        migrations.AddField(
            model_name='maintenancerecord',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pm_maintenance_records', to='users.department'),
        ),
        migrations.AddField(
            model_name='maintenancerecord',
            name='disruption_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pm_maintenance_records', to='equipment.disruptionevent'),
        ),
        migrations.AddField(
            model_name='maintenancerecord',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pm_maintenance_records', to='equipment.equipment'),
        ),
        migrations.AddField(
            model_name='maintenancerecord',
            name='recorded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='maintenancerecord',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='procurement_management.vendor'),
        ),
        migrations.AddField(
            model_name='procurementdocument',
            name='maintenance_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='procurement_management.maintenancerecord'),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='maintenance_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='procurement_management.maintenancerecord'),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='maintenance_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='parts_used', to='procurement_management.maintenancerecord'),
        ),
        migrations.AddField(
            model_name='verificationcampaign',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='verificationcampaign',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='verificationcampaign',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pm_verification_campaigns', to='users.department'),
        ),
        migrations.AddField(
            model_name='verificationcampaign',
            name='laboratory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='sync.laboratory'),
        ),
        migrations.AddField(
            model_name='verificationcampaign',
            name='register',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='procurement_management.assetregister'),
        ),
        migrations.AddField(
            model_name='assetverification',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='verifications', to='procurement_management.verificationcampaign'),
        ),
        migrations.AddConstraint(
            model_name='assetregister',
            constraint=models.UniqueConstraint(fields=('department', 'code'), name='pm_register_unique_code'),
        ),
        migrations.AddIndex(
            model_name='itemequipmentlink',
            index=models.Index(fields=['equipment', 'active'], name='procurement_equipme_80136e_idx'),
        ),
        migrations.AddConstraint(
            model_name='itemequipmentlink',
            constraint=models.UniqueConstraint(fields=('item', 'equipment'), name='pm_item_link_unique'),
        ),
        migrations.AddIndex(
            model_name='maintenancerecord',
            index=models.Index(fields=['equipment', 'downtime_start'], name='procurement_equipme_3a8b3a_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancerecord',
            index=models.Index(fields=['department', 'created_at'], name='procurement_departm_1a4a4b_idx'),
        ),
        migrations.AddIndex(
            model_name='assetverification',
            index=models.Index(fields=['campaign', 'asset'], name='procurement_campaig_0e1985_idx'),
        ),
        migrations.AddIndex(
            model_name='assetverification',
            index=models.Index(fields=['asset', 'verified_on'], name='procurement_asset_i_63c607_idx'),
        ),
    ]
