# Generated by Django 5.2.9 on 2026-10-03 04:50

import django.db.models.deletion
import iic_booking.deployment.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployment', '0002_compatibility_repair_packages'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileAppRelease',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform', models.CharField(choices=[('android', 'Android')], default='android', max_length=16)),
                ('version_name', models.CharField(max_length=32)),
                ('version_code', models.PositiveIntegerField()),
                ('release_date', models.DateField()),
                ('release_notes', models.TextField(blank=True, default='')),
                ('min_android', models.CharField(blank=True, default='Android 7.0 or newer', max_length=32)),
                ('file', models.FileField(blank=True, max_length=512, null=True, upload_to='mobile_app/%Y/%m/%d/')),
                ('original_name', models.CharField(blank=True, default='', max_length=255)),
                ('download_size_bytes', models.BigIntegerField(default=0)),
                ('sha256', models.CharField(blank=True, default='', max_length=64)),
                ('signing_cert_sha256', models.CharField(blank=True, default='', max_length=128)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('is_latest', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mobile app release',
                'verbose_name_plural': 'Mobile app releases',
                'ordering': ['-version_code', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MobileAppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audience_user_types', models.JSONField(blank=True, default=iic_booking.deployment.models.default_mobile_app_audience, help_text='User type codes allowed to sign in through the app, e.g. manager, operator, admin.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mobile app settings',
                'verbose_name_plural': 'Mobile app settings',
            },
        ),
    ]
