# Generated by Django 5.2.9 on 2026-07-27 17:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0177_result_processing_m10'),
        ('remote_analysis', '0001_initial_remote_analysis'),
        ('users', '0095_initial_payment_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SoftwareRequirement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('software', models.CharField(blank=True, default='', max_length=512)),
                ('minimum_version', models.CharField(blank=True, default='', max_length=128)),
                ('required', models.BooleanField(default=True)),
                ('optional', models.BooleanField(default=False)),
                ('license_required', models.BooleanField(default=False)),
                ('gpu_required', models.BooleanField(default=False)),
                ('minimum_ram_gb', models.FloatField(default=0)),
                ('minimum_storage_gb', models.FloatField(default=0)),
                ('minimum_cpu_cores', models.PositiveIntegerField(default=0)),
                ('operating_system', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Software requirement',
                'verbose_name_plural': 'Software requirements',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AllocationRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('rule_type', models.CharField(choices=[('DEPARTMENT_PRIORITY', 'Department priority'), ('EQUIPMENT_PRIORITY', 'Equipment priority'), ('USER_PRIORITY', 'User priority'), ('FACULTY_OVERRIDE', 'Faculty override'), ('RESEARCH_PROJECT', 'Research project'), ('ADMINISTRATIVE', 'Administrative reservation'), ('VIP', 'VIP (future)')], max_length=64)),
                ('priority_boost', models.IntegerField(default=0)),
                ('weight_overrides', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ra_allocation_rules', to='users.department')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ra_allocation_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-priority_boost', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisReservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('VALIDATING', 'Validating'), ('QUEUED', 'Queued'), ('RESERVED', 'Reserved'), ('PREPARING', 'Preparing'), ('READY', 'Ready'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled'), ('FAILED', 'Failed')], db_index=True, default='REQUESTED', max_length=32)),
                ('requested_start', models.DateTimeField()),
                ('requested_end', models.DateTimeField()),
                ('reserved_start', models.DateTimeField(blank=True, null=True)),
                ('reserved_end', models.DateTimeField(blank=True, null=True)),
                ('allocated_at', models.DateTimeField(blank=True, null=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('priority', models.IntegerField(db_index=True, default=100)),
                ('requested_capabilities', models.JSONField(blank=True, default=dict)),
                ('requested_resources', models.JSONField(blank=True, default=dict)),
                ('allocation_score', models.FloatField(blank=True, null=True)),
                ('allocation_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analysis_reservations', to='equipment.booking')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ra_reservations_created', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analysis_reservations', to='users.department')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='analysis_reservations', to=settings.AUTH_USER_MODEL)),
                ('workstation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='remote_analysis.analysisworkstation')),
                ('software_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='remote_analysis.softwarerequirement')),
            ],
            options={
                'verbose_name': 'Analysis reservation',
                'verbose_name_plural': 'Analysis reservations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceWindow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('reason', models.CharField(blank=True, default='', max_length=512)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ra_maintenance_windows', to=settings.AUTH_USER_MODEL)),
                ('workstation', models.ForeignKey(blank=True, help_text='Null = applies to all workstations', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_windows', to='remote_analysis.analysisworkstation')),
            ],
            options={
                'ordering': ['-start'],
            },
        ),
        migrations.CreateModel(
            name='ReservationAudit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=128)),
                ('details', models.TextField(blank=True, default='')),
                ('success', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audits', to='remote_analysis.analysisreservation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReservationConflict',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('conflict_type', models.CharField(choices=[('DOUBLE_BOOKING', 'Double booking'), ('MAINTENANCE_OVERLAP', 'Maintenance overlap'), ('WORKSTATION_OFFLINE', 'Workstation offline'), ('EXTENSION_CONFLICT', 'Reservation extension'), ('MANUAL_OVERRIDE', 'Manual override'), ('PRIORITY_OVERRIDE', 'Priority override')], max_length=64)),
                ('resolution', models.CharField(blank=True, default='', max_length=512)),
                ('resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conflicting_reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conflicted_by', to='remote_analysis.analysisreservation')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicts', to='remote_analysis.analysisreservation')),
                ('workstation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='remote_analysis.analysisworkstation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReservationEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(db_index=True, max_length=64)),
                ('details', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='remote_analysis.analysisreservation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReservationHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_status', models.CharField(blank=True, default='', max_length=32)),
                ('to_status', models.CharField(choices=[('REQUESTED', 'Requested'), ('VALIDATING', 'Validating'), ('QUEUED', 'Queued'), ('RESERVED', 'Reserved'), ('PREPARING', 'Preparing'), ('READY', 'Ready'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled'), ('FAILED', 'Failed')], max_length=32)),
                ('reason', models.CharField(blank=True, default='', max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='remote_analysis.analysisreservation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReservationPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('preferred_building', models.CharField(blank=True, default='', max_length=255)),
                ('preferred_capabilities', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('preferred_workstation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='remote_analysis.analysisworkstation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ra_reservation_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reservation preference',
                'verbose_name_plural': 'Reservation preferences',
            },
        ),
        migrations.CreateModel(
            name='ReservationQueue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('WAITING', 'Waiting'), ('ALLOCATING', 'Allocating'), ('RESERVED', 'Reserved'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], db_index=True, default='WAITING', max_length=32)),
                ('priority', models.IntegerField(db_index=True, default=100)),
                ('enqueued_at', models.DateTimeField(auto_now_add=True)),
                ('dequeued_at', models.DateTimeField(blank=True, null=True)),
                ('position_hint', models.PositiveIntegerField(default=0)),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='queue_entry', to='remote_analysis.analysisreservation')),
            ],
            options={
                'verbose_name': 'Reservation queue entry',
                'verbose_name_plural': 'Reservation queue',
                'ordering': ['priority', 'enqueued_at'],
            },
        ),
        migrations.CreateModel(
            name='SchedulerTelemetry',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('metric_name', models.CharField(db_index=True, max_length=128)),
                ('value', models.FloatField()),
                ('unit', models.CharField(blank=True, default='', max_length=32)),
                ('tags', models.JSONField(blank=True, default=dict)),
                ('recorded_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['metric_name', 'recorded_at'], name='remote_anal_metric__c74ac3_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='analysisreservation',
            index=models.Index(fields=['status', 'requested_start'], name='remote_anal_status_8eb277_idx'),
        ),
        migrations.AddIndex(
            model_name='analysisreservation',
            index=models.Index(fields=['workstation', 'reserved_start', 'reserved_end'], name='remote_anal_worksta_e88c7a_idx'),
        ),
    ]
