# Generated by Django 5.2.9 on 2026-07-27 18:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0177_result_processing_m10'),
        ('remote_analysis', '0003_browser_remote_desktop_guacamole'),
        ('users', '0095_initial_payment_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='remoteanalysissettings',
            name='allowed_extensions',
            field=models.TextField(blank=True, default='', help_text='Comma-separated allowlist. Empty = allow all except blocked.'),
        ),
        migrations.AddField(
            model_name='remoteanalysissettings',
            name='archive_root',
            field=models.CharField(blank=True, default='', help_text='Absolute archive root. Empty = MEDIA_ROOT/remote_analysis/archives', max_length=1024),
        ),
        migrations.AddField(
            model_name='remoteanalysissettings',
            name='blocked_extensions',
            field=models.TextField(blank=True, default='.exe,.bat,.cmd,.ps1,.msi,.scr,.vbs'),
        ),
        migrations.AddField(
            model_name='remoteanalysissettings',
            name='checksum_algorithm',
            field=models.CharField(default='sha256', max_length=32),
        ),
        migrations.AddField(
            model_name='remoteanalysissettings',
            name='chunk_size_bytes',
            field=models.PositiveIntegerField(default=5242880),
        ),
        migrations.AddField(
            model_name='remoteanalysissettings',
            name='compression_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='remoteanalysissettings',
            name='default_quota_gb',
            field=models.FloatField(default=50.0),
        ),
        migrations.AddField(
            model_name='remoteanalysissettings',
            name='folder_template',
            field=models.JSONField(blank=True, default=list, help_text='Folder names created for each workspace. Empty = default template.'),
        ),
        migrations.AddField(
            model_name='remoteanalysissettings',
            name='maximum_download_size',
            field=models.BigIntegerField(default=2147483648),
        ),
        migrations.AddField(
            model_name='remoteanalysissettings',
            name='maximum_upload_size',
            field=models.BigIntegerField(default=2147483648),
        ),
        migrations.AddField(
            model_name='remoteanalysissettings',
            name='retention_days',
            field=models.PositiveIntegerField(default=90),
        ),
        migrations.AddField(
            model_name='remoteanalysissettings',
            name='version_history_limit',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AddField(
            model_name='remoteanalysissettings',
            name='virus_scanner',
            field=models.CharField(blank=True, default='noop', help_text='noop | defender | clamav (only noop implemented in Milestone 5)', max_length=64),
        ),
        migrations.AddField(
            model_name='remoteanalysissettings',
            name='workspace_root',
            field=models.CharField(blank=True, default='', help_text='Absolute Portal storage root for workspaces. Empty = MEDIA_ROOT/remote_analysis/workspaces', max_length=1024),
        ),
        migrations.AlterField(
            model_name='remotecommand',
            name='command_type',
            field=models.CharField(choices=[('PING', 'Ping'), ('REFRESH', 'Refresh'), ('REFRESH_SOFTWARE', 'Refresh software'), ('COLLECT_LOGS', 'Collect logs'), ('RESTART_AGENT', 'Restart agent'), ('PREPARE_WORKSTATION', 'Prepare workstation'), ('CLEAN_WORKSTATION', 'Clean workstation'), ('SYNC_WORKSPACE', 'Synchronize analysis workspace'), ('COLLECT_WORKSPACE', 'Collect workspace outputs')], max_length=64),
        ),
        migrations.CreateModel(
            name='AnalysisWorkspace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('CREATING', 'Creating'), ('READY', 'Ready'), ('SYNCING', 'Syncing'), ('ACTIVE', 'Active'), ('COLLECTING', 'Collecting outputs'), ('ARCHIVING', 'Archiving'), ('ARCHIVED', 'Archived'), ('RESTORING', 'Restoring'), ('DELETED', 'Deleted'), ('FAILED', 'Failed')], db_index=True, default='CREATING', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('retention_until', models.DateTimeField(blank=True, null=True)),
                ('quota_gb', models.FloatField(default=50.0)),
                ('current_usage_bytes', models.BigIntegerField(default=0)),
                ('read_only', models.BooleanField(default=False)),
                ('archive_status', models.CharField(choices=[('NONE', 'Not archived'), ('PENDING', 'Pending'), ('ARCHIVED', 'Archived'), ('RESTORED', 'Restored'), ('FAILED', 'Failed')], default='NONE', max_length=32)),
                ('storage_key', models.CharField(max_length=255, unique=True)),
                ('local_agent_path', models.CharField(blank=True, default='', help_text='Agent-local relative path hint (not a Portal filesystem path).', max_length=1024)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analysis_workspaces', to='equipment.booking')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analysis_workspaces', to='users.department')),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='workspace', to='remote_analysis.analysisreservation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='analysis_workspaces', to=settings.AUTH_USER_MODEL)),
                ('workstation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analysis_workspaces', to='remote_analysis.analysisworkstation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransferPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('max_file_size', models.BigIntegerField(blank=True, null=True)),
                ('allowed_extensions', models.TextField(blank=True, default='')),
                ('blocked_extensions', models.TextField(blank=True, default='')),
                ('read_only_folders', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workspace_transfer_policies', to='users.department')),
                ('workstation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workspace_transfer_policies', to='remote_analysis.analysisworkstation')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WorkspaceArchive',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('archive_key', models.CharField(max_length=255)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('sha256', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.CharField(blank=True, default='', max_length=512)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archives', to='remote_analysis.analysisworkspace')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkspaceAudit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(db_index=True, max_length=64)),
                ('details', models.TextField(blank=True, default='')),
                ('success', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audits', to='remote_analysis.analysisworkspace')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkspaceFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_name', models.CharField(max_length=512)),
                ('stored_name', models.CharField(max_length=512)),
                ('relative_path', models.CharField(db_index=True, max_length=1024)),
                ('size', models.BigIntegerField(default=0)),
                ('sha256', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('mime_type', models.CharField(blank=True, default='', max_length=255)),
                ('category', models.CharField(choices=[('RAW', 'Raw data'), ('PROCESSED', 'Processed'), ('REPORT', 'Report'), ('EXPORT', 'Export'), ('TEMP', 'Temporary'), ('LOG', 'Log'), ('METADATA', 'Metadata'), ('OTHER', 'Other')], default='OTHER', max_length=32)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_current', models.BooleanField(default=True)),
                ('virus_status', models.CharField(choices=[('PENDING', 'Pending'), ('CLEAN', 'Clean'), ('INFECTED', 'Infected'), ('ERROR', 'Scan error'), ('SKIPPED', 'Skipped')], default='PENDING', max_length=32)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('locked', models.BooleanField(default=False)),
                ('deleted', models.BooleanField(default=False)),
                ('storage_relpath', models.CharField(blank=True, default='', max_length=1024)),
                ('source', models.CharField(blank=True, default='portal', max_length=64)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workspace_uploads', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='remote_analysis.analysisworkspace')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='VirusScanResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scanner', models.CharField(default='noop', max_length=64)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CLEAN', 'Clean'), ('INFECTED', 'Infected'), ('ERROR', 'Scan error'), ('SKIPPED', 'Skipped')], default='PENDING', max_length=32)),
                ('detail', models.CharField(blank=True, default='', max_length=512)),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_results', to='remote_analysis.workspacefile')),
            ],
            options={
                'ordering': ['-scanned_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkspaceFolder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('relative_path', models.CharField(max_length=1024)),
                ('read_only', models.BooleanField(default=False)),
                ('category', models.CharField(choices=[('RAW', 'Raw data'), ('PROCESSED', 'Processed'), ('REPORT', 'Report'), ('EXPORT', 'Export'), ('TEMP', 'Temporary'), ('LOG', 'Log'), ('METADATA', 'Metadata'), ('OTHER', 'Other')], default='OTHER', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='remote_analysis.analysisworkspace')),
            ],
            options={
                'ordering': ['relative_path'],
            },
        ),
        migrations.AddField(
            model_name='workspacefile',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='remote_analysis.workspacefolder'),
        ),
        migrations.CreateModel(
            name='WorkspaceQuota',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('soft_limit_bytes', models.BigIntegerField(default=0)),
                ('hard_limit_bytes', models.BigIntegerField(default=0)),
                ('warning_percent', models.PositiveSmallIntegerField(default=80)),
                ('override_allowed', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workspace_quotas', to='users.department')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workspace_quotas', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quota', to='remote_analysis.analysisworkspace')),
            ],
        ),
        migrations.CreateModel(
            name='WorkspaceShare',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('department_only', models.BooleanField(default=False)),
                ('read_only', models.BooleanField(default=True)),
                ('token_hash', models.CharField(blank=True, default='', max_length=128)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_shares_created', to=settings.AUTH_USER_MODEL)),
                ('shared_with', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workspace_shares_received', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='remote_analysis.analysisworkspace')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkspaceTelemetry',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('metric_name', models.CharField(db_index=True, max_length=128)),
                ('value', models.FloatField()),
                ('unit', models.CharField(blank=True, default='', max_length=32)),
                ('tags', models.JSONField(blank=True, default=dict)),
                ('recorded_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telemetry', to='remote_analysis.analysisworkspace')),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkspaceTransfer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('direction', models.CharField(choices=[('PORTAL_TO_WORKSPACE', 'Portal to workspace'), ('WORKSPACE_TO_PORTAL', 'Workspace to portal'), ('AGENT_PULL', 'Agent pull'), ('AGENT_PUSH', 'Agent push')], max_length=32)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In progress'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=32)),
                ('bytes_total', models.BigIntegerField(default=0)),
                ('bytes_transferred', models.BigIntegerField(default=0)),
                ('chunk_size', models.PositiveIntegerField(default=0)),
                ('checksum_expected', models.CharField(blank=True, default='', max_length=64)),
                ('checksum_actual', models.CharField(blank=True, default='', max_length=64)),
                ('error_message', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers', to='remote_analysis.workspacefile')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='remote_analysis.analysisworkspace')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransferHistory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('event', models.CharField(max_length=64)),
                ('detail', models.CharField(blank=True, default='', max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='remote_analysis.workspacetransfer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkspaceVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField()),
                ('size', models.BigIntegerField(default=0)),
                ('sha256', models.CharField(blank=True, default='', max_length=64)),
                ('storage_relpath', models.CharField(blank=True, default='', max_length=1024)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(blank=True, default='', max_length=512)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='remote_analysis.workspacefile')),
            ],
            options={
                'ordering': ['-version'],
            },
        ),
        migrations.AddIndex(
            model_name='analysisworkspace',
            index=models.Index(fields=['status', 'created_at'], name='remote_anal_status_660d3c_idx'),
        ),
        migrations.AddIndex(
            model_name='analysisworkspace',
            index=models.Index(fields=['user', 'status'], name='remote_anal_user_id_421139_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='workspacefolder',
            unique_together={('workspace', 'relative_path')},
        ),
        migrations.AddIndex(
            model_name='workspacefile',
            index=models.Index(fields=['workspace', 'relative_path', 'is_current'], name='remote_anal_workspa_07ab7d_idx'),
        ),
        migrations.AddIndex(
            model_name='workspacefile',
            index=models.Index(fields=['workspace', 'deleted'], name='remote_anal_workspa_c3b517_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='workspaceversion',
            unique_together={('file', 'version')},
        ),
    ]
