# Generated by Django 5.2.9 on 2026-07-27 19:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0177_result_processing_m10'),
        ('remote_analysis', '0006_collaboration_center'),
        ('users', '0095_initial_payment_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='activityevent',
            index=models.Index(fields=['feed', 'created_at'], name='remote_anal_feed_id_f44f54_idx'),
        ),
        migrations.AddIndex(
            model_name='activityevent',
            index=models.Index(fields=['verb', 'created_at'], name='remote_anal_verb_d35a3b_idx'),
        ),
        migrations.AddIndex(
            model_name='analysisworkspace',
            index=models.Index(fields=['status', 'retention_until'], name='remote_anal_status_e61a9c_idx'),
        ),
        migrations.AddIndex(
            model_name='remotedesktopsession',
            index=models.Index(fields=['status', 'expires_at'], name='remote_anal_status_6104fe_idx'),
        ),
        migrations.AddIndex(
            model_name='remotedesktopsession',
            index=models.Index(fields=['status', 'last_activity_at'], name='remote_anal_status_7e5b72_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionassistancerequest',
            index=models.Index(fields=['status', 'created_at'], name='remote_anal_status_258465_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionassistancerequest',
            index=models.Index(fields=['assigned_to', 'status'], name='remote_anal_assigne_e4737a_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionassistancerequest',
            index=models.Index(fields=['requested_by', 'status'], name='remote_anal_request_c50f85_idx'),
        ),
        migrations.AddIndex(
            model_name='sessioninvitation',
            index=models.Index(fields=['status', 'expires_at'], name='remote_anal_status_e08ab0_idx'),
        ),
        migrations.AddIndex(
            model_name='sessioninvitation',
            index=models.Index(fields=['invited_user', 'status'], name='remote_anal_invited_a714a0_idx'),
        ),
    ]
