# Generated by Django 5.2.9 on 2026-07-30 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remote_analysis', '0008_workstation_status_heartbeat_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisworkspace',
            name='sync_message',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AddField(
            model_name='analysisworkspace',
            name='sync_phase',
            field=models.CharField(choices=[('QUEUED', 'Queued'), ('PREPARING', 'Preparing workspace'), ('DOWNLOADING', 'Downloading data'), ('READY', 'Ready'), ('UPLOADING', 'Uploading results'), ('RETRYING', 'Retrying'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], db_index=True, default='QUEUED', help_text='Automatic data sync progress shown to users.', max_length=32),
        ),
        migrations.AddField(
            model_name='analysisworkspace',
            name='sync_progress_percent',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='remoteanalysissettings',
            name='bandwidth_limit_kbps',
            field=models.PositiveIntegerField(default=0, help_text='Advisory agent bandwidth cap; 0 = unlimited.'),
        ),
        migrations.AddField(
            model_name='remoteanalysissettings',
            name='compression_min_bytes',
            field=models.BigIntegerField(default=5242880, help_text='Compress agent uploads at or above this size when compression_enabled.'),
        ),
        migrations.AddField(
            model_name='remoteanalysissettings',
            name='transfer_max_retries',
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='remoteanalysissettings',
            name='workspace_sync_interval_seconds',
            field=models.PositiveIntegerField(default=300, help_text='Used when workspace_sync_mode=interval.'),
        ),
        migrations.AddField(
            model_name='remoteanalysissettings',
            name='workspace_sync_mode',
            field=models.CharField(default='end_of_session', help_text='end_of_session | interval', max_length=32),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('RESERVATION_CONFIRMED', 'Reservation confirmed'), ('RESERVATION_REMINDER', 'Reservation reminder'), ('SESSION_STARTING', 'Session starting'), ('SESSION_ENDING', 'Session ending'), ('WORKSPACE_SYNCED', 'Workspace synchronized'), ('WORKSPACE_READY', 'Workspace ready'), ('WORKSPACE_SYNC_STARTED', 'Synchronization started'), ('WORKSPACE_SYNC_FAILED', 'Synchronization failed'), ('FILES_AVAILABLE', 'Files available'), ('UPLOAD_COMPLETE', 'Upload complete'), ('DOWNLOAD_COMPLETE', 'Download complete'), ('AGENT_OFFLINE', 'Agent offline'), ('MAINTENANCE_SCHEDULED', 'Maintenance scheduled'), ('SESSION_TERMINATED', 'Session terminated'), ('ALERT', 'Alert'), ('INVITATION', 'Invitation'), ('ASSISTANCE', 'Assistance'), ('COMMENT', 'Comment'), ('SHARE', 'Share'), ('ANNOUNCEMENT', 'Announcement')], db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='workspacetransfer',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In progress'), ('RETRYING', 'Retrying'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=32),
        ),
        migrations.AddIndex(
            model_name='analysisworkspace',
            index=models.Index(fields=['sync_phase', 'updated_at'], name='remote_anal_sync_ph_19a095_idx'),
        ),
    ]
