# Generated by Django 5.2.9 on 2026-07-30 21:24

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone
from django.utils.text import slugify


def forwards_backfill_single_step_workflows(apps, schema_editor):
    """EquipmentAnalysisSoftware → published single-step AnalysisWorkflow + mapping."""
    Mapping = apps.get_model("remote_analysis", "EquipmentAnalysisSoftware")
    Workflow = apps.get_model("remote_analysis", "AnalysisWorkflow")
    Version = apps.get_model("remote_analysis", "AnalysisWorkflowVersion")
    Step = apps.get_model("remote_analysis", "AnalysisWorkflowStep")
    EqWorkflow = apps.get_model("remote_analysis", "EquipmentAnalysisWorkflow")
    Equipment = apps.get_model("equipment", "Equipment")

    for row in Mapping.objects.select_related("catalog").all():
        catalog = row.catalog
        eq = Equipment.objects.filter(pk=row.equipment_id).first()
        eq_code = (getattr(eq, "code", None) or str(row.equipment_id)).strip()
        name = f"{eq_code} / {catalog.name}"
        base_slug = slugify(name)[:240] or f"wf-{row.pk.hex[:12]}"
        slug = base_slug
        n = 1
        while Workflow.objects.filter(slug=slug).exists():
            n += 1
            slug = f"{base_slug}-{n}"

        wf = Workflow.objects.create(
            id=uuid.uuid4(),
            name=name[:255],
            slug=slug,
            description=f"Auto-migrated single-step workflow from {catalog.name}.",
            is_active=True,
            is_template=False,
            estimated_duration_minutes=int(getattr(catalog, "default_session_duration_hours", 4) or 4) * 60,
            require_raw_data=True,
        )
        version = Version.objects.create(
            id=uuid.uuid4(),
            workflow=wf,
            version_number=1,
            label="v1",
            changelog="Migrated from Equipment → Software mapping",
            is_published=True,
            published_at=timezone.now(),
        )
        Step.objects.create(
            id=uuid.uuid4(),
            version=version,
            step_number=1,
            title=catalog.name,
            software_id=catalog.pk,
            mandatory=True,
            estimated_duration_minutes=60,
            expected_output_folder="Step01",
            expected_outputs=[],
            environment_label=f"{catalog.name} Environment",
            operator_instructions="",
        )
        EqWorkflow.objects.get_or_create(
            equipment_id=row.equipment_id,
            workflow_id=wf.pk,
            defaults={
                "id": uuid.uuid4(),
                "is_default": bool(row.is_default),
                "sort_order": int(row.sort_order or 0),
                "button_label_override": row.button_label_override or "",
            },
        )


def backwards_noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0181_waitlistentry_opt_out_and_sample'),
        ('remote_analysis', '0013_analyze_data_catalog_and_settings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisCapability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('slug', models.SlugField(max_length=128, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Analysis capability',
                'verbose_name_plural': 'Analysis capabilities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PREPARING', 'Preparing Analysis Workspace'), ('ACTIVE', 'Analysis Session Active'), ('PAUSED', 'Paused'), ('NEEDS_REVIEW', 'Needs Operator Review'), ('COMPLETED', 'Analysis Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=32)),
                ('current_step_number', models.PositiveIntegerField(default=1)),
                ('variables', models.JSONField(blank=True, default=dict)),
                ('ux_status', models.CharField(blank=True, default='', max_length=128)),
                ('status_detail', models.TextField(blank=True, default='')),
                ('same_environment', models.BooleanField(default=False, help_text='True when all mandatory steps stay on one Analysis Environment.')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('paused_at', models.DateTimeField(blank=True, null=True)),
                ('resumed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Analysis job',
                'verbose_name_plural': 'Analysis jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisJobCollaborator',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('OWNER', 'Owner'), ('COLLABORATOR', 'Collaborator'), ('VIEWER', 'Viewer'), ('OBSERVER', 'Observer')], default='VIEWER', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Analysis job collaborator (v2 reserved)',
                'verbose_name_plural': 'Analysis job collaborators (v2 reserved)',
            },
        ),
        migrations.CreateModel(
            name='AnalysisJobStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('step_number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('READY', 'Ready'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('SKIPPED', 'Skipped'), ('FAILED', 'Failed'), ('NEEDS_REVIEW', 'Needs Operator Review')], db_index=True, default='PENDING', max_length=32)),
                ('input_folder', models.CharField(blank=True, default='', max_length=64)),
                ('output_folder', models.CharField(blank=True, default='', max_length=64)),
                ('environment_label', models.CharField(blank=True, default='', max_length=128)),
                ('verification_result', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('checkpoint_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Analysis job step',
                'verbose_name_plural': 'Analysis job steps',
                'ordering': ['step_number'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisWorkflow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('is_template', models.BooleanField(default=False, help_text='When True, this workflow is a cloneable lab template.')),
                ('estimated_duration_minutes', models.PositiveIntegerField(default=60)),
                ('require_raw_data', models.BooleanField(default=True)),
                ('require_calibration', models.BooleanField(default=False)),
                ('require_reference_files', models.BooleanField(default=False)),
                ('optional_input_types', models.JSONField(blank=True, default=list, help_text='Optional input labels, e.g. ["Crystal database", "Previous experiment"].')),
                ('input_requirements', models.JSONField(blank=True, default=dict, help_text='Extensible input schema: {raw, calibration, reference, optional: [...]}.')),
                ('variables_schema', models.JSONField(blank=True, default=list)),
                ('ai_assistance_enabled', models.BooleanField(default=False)),
                ('ai_suggested_parameters', models.JSONField(blank=True, default=dict)),
                ('ai_auto_classification', models.JSONField(blank=True, default=dict)),
                ('ai_quality_score_schema', models.JSONField(blank=True, default=dict)),
                ('ai_analysis_notes_prompt', models.TextField(blank=True, default='')),
                ('collaboration_enabled', models.BooleanField(default=False, help_text='Reserved for multi-user Analysis Jobs (v2).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Analysis workflow',
                'verbose_name_plural': 'Analysis workflows',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisWorkflowStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('step_number', models.PositiveIntegerField()),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('version_constraint', models.CharField(blank=True, default='', max_length=128)),
                ('mandatory', models.BooleanField(default=True)),
                ('estimated_duration_minutes', models.PositiveIntegerField(default=30)),
                ('expected_output_folder', models.CharField(blank=True, default='', help_text='Defaults to StepNN from step_number when blank.', max_length=64)),
                ('expected_outputs', models.JSONField(blank=True, default=list, help_text='Glob patterns for automatic verification, e.g. ["*.xy", "*.pdf"].')),
                ('allowed_file_types', models.JSONField(blank=True, default=list)),
                ('validation_rules', models.JSONField(blank=True, default=dict)),
                ('description', models.TextField(blank=True, default='')),
                ('operator_instructions', models.TextField(blank=True, default='')),
                ('help_url', models.URLField(blank=True, default='')),
                ('reference_manual_url', models.URLField(blank=True, default='')),
                ('environment_label', models.CharField(blank=True, default='', help_text='User-facing Analysis Environment name, e.g. "OriginPro Environment".', max_length=128)),
                ('ai_suggested_parameters', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Analysis workflow step',
                'verbose_name_plural': 'Analysis workflow steps',
                'ordering': ['step_number'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisWorkflowVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField(default=1)),
                ('label', models.CharField(blank=True, default='', max_length=64)),
                ('changelog', models.TextField(blank=True, default='')),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Analysis workflow version',
                'verbose_name_plural': 'Analysis workflow versions',
                'ordering': ['-version_number'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentAnalysisWorkflow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_default', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('button_label_override', models.CharField(blank=True, default='', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Equipment analysis workflow',
                'verbose_name_plural': 'Equipment analysis workflows',
                'ordering': ['sort_order', 'workflow__name'],
            },
        ),
        migrations.RenameIndex(
            model_name='commissioningrunstep',
            new_name='remote_anal_run_id_dbc176_idx',
            old_name='remote_anal_run_id_0a2f1e_idx',
        ),
        migrations.AddField(
            model_name='remoteanalysissettings',
            name='analyze_data_prefer_workflow',
            field=models.BooleanField(default=True, help_text='When True, Analyze Data prefers Equipment→Workflow mappings over legacy single-software.'),
        ),
        migrations.AddField(
            model_name='analysissoftwarecatalog',
            name='capabilities',
            field=models.ManyToManyField(blank=True, help_text='Capability tags advertised by this software (Peak Fitting, Image Analysis, …).', related_name='software_packages', to='remote_analysis.analysiscapability'),
        ),
        migrations.AddField(
            model_name='analysisjob',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_jobs', to='equipment.booking'),
        ),
        migrations.AddField(
            model_name='analysisjob',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='analysisjob',
            name='preferred_workstation',
            field=models.ForeignKey(blank=True, help_text='Internal same-PC preference when all mandatory software is present.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_analysis_jobs', to='remote_analysis.analysisworkstation'),
        ),
        migrations.AddField(
            model_name='analysisjob',
            name='reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analysis_jobs', to='remote_analysis.analysisreservation'),
        ),
        migrations.AddField(
            model_name='analysisjob',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analysis_jobs', to='remote_analysis.analysisworkspace'),
        ),
        migrations.AddField(
            model_name='analysisjobcollaborator',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborators', to='remote_analysis.analysisjob'),
        ),
        migrations.AddField(
            model_name='analysisjobcollaborator',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_job_collaborations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='analysisjobstep',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='remote_analysis.analysisjob'),
        ),
        migrations.AddField(
            model_name='analysisjobstep',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analysis_job_steps', to='remote_analysis.remotedesktopsession'),
        ),
        migrations.AddField(
            model_name='analysisjobstep',
            name='workstation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analysis_job_steps', to='remote_analysis.analysisworkstation'),
        ),
        migrations.AddField(
            model_name='analysisworkflow',
            name='cloned_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clones', to='remote_analysis.analysisworkflow'),
        ),
        migrations.AddField(
            model_name='analysisworkflow',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_analysis_workflows', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='analysisworkflowstep',
            name='capability',
            field=models.ForeignKey(blank=True, help_text='Prefer capability tags so software can be swapped without editing workflows.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_steps', to='remote_analysis.analysiscapability'),
        ),
        migrations.AddField(
            model_name='analysisworkflowstep',
            name='software',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_steps', to='remote_analysis.analysissoftwarecatalog'),
        ),
        migrations.AddField(
            model_name='analysisjobstep',
            name='workflow_step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_steps', to='remote_analysis.analysisworkflowstep'),
        ),
        migrations.AddField(
            model_name='analysisworkflowversion',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='remote_analysis.analysisworkflow'),
        ),
        migrations.AddField(
            model_name='analysisworkflowstep',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='remote_analysis.analysisworkflowversion'),
        ),
        migrations.AddField(
            model_name='analysisjob',
            name='workflow_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='remote_analysis.analysisworkflowversion'),
        ),
        migrations.AddField(
            model_name='equipmentanalysisworkflow',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_workflow_mappings', to='equipment.equipment'),
        ),
        migrations.AddField(
            model_name='equipmentanalysisworkflow',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_mappings', to='remote_analysis.analysisworkflow'),
        ),
        migrations.AddConstraint(
            model_name='analysisjobcollaborator',
            constraint=models.UniqueConstraint(fields=('job', 'user'), name='uniq_analysis_job_collaborator'),
        ),
        migrations.AddConstraint(
            model_name='analysisjobstep',
            constraint=models.UniqueConstraint(fields=('job', 'step_number'), name='uniq_analysis_job_step'),
        ),
        migrations.AddConstraint(
            model_name='analysisworkflowversion',
            constraint=models.UniqueConstraint(fields=('workflow', 'version_number'), name='uniq_analysis_workflow_version'),
        ),
        migrations.AddConstraint(
            model_name='analysisworkflowstep',
            constraint=models.UniqueConstraint(fields=('version', 'step_number'), name='uniq_analysis_workflow_step_number'),
        ),
        migrations.AddIndex(
            model_name='analysisjob',
            index=models.Index(fields=['booking', 'status'], name='remote_anal_booking_8e6fe6_idx'),
        ),
        migrations.AddIndex(
            model_name='analysisjob',
            index=models.Index(fields=['status', 'updated_at'], name='remote_anal_status_8b346a_idx'),
        ),
        migrations.AddConstraint(
            model_name='equipmentanalysisworkflow',
            constraint=models.UniqueConstraint(fields=('equipment', 'workflow'), name='uniq_equipment_analysis_workflow'),
        ),
        migrations.RunPython(forwards_backfill_single_step_workflows, backwards_noop),
    ]
