# Generated by Django 5.x — retire Direct RDP; Reverse Tunnel only.

from django.db import migrations, models


def coerce_transport_to_reverse_tunnel(apps, schema_editor):
    RemoteAnalysisSettings = apps.get_model("remote_analysis", "RemoteAnalysisSettings")
    RemoteAnalysisSettings.objects.exclude(transport_mode="reverse_tunnel").update(
        transport_mode="reverse_tunnel"
    )


class Migration(migrations.Migration):

    dependencies = [
        ("remote_analysis", "0020_reservation_checkin_window"),
    ]

    operations = [
        migrations.RunPython(coerce_transport_to_reverse_tunnel, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="remoteanalysissettings",
            name="transport_mode",
            field=models.CharField(
                choices=[("reverse_tunnel", "Reverse tunnel")],
                default="reverse_tunnel",
                help_text=(
                    "Sole supported mode: reverse_tunnel — guacd dials the AWS adapter; "
                    "the agent bridges to localhost RDP."
                ),
                max_length=32,
            ),
        ),
    ]
