# Generated by Django 5.2.9 on 2026-10-02 13:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0217_booking_template_preferred_slot'),
        ('training', '0002_seed_levels_badges_policy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingModuleSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_enabled', models.BooleanField(default=False, help_text='Turns Training & Certification on without editing the server env (env TRAINING_MODULE_ENABLED also turns it on).')),
                ('audience', models.CharField(choices=[('TEST_ACCOUNTS', 'Test accounts only'), ('EVERYONE', 'Everyone eligible')], default='TEST_ACCOUNTS', help_text='Test accounts only: only flagged test faculty/students see Training. OICs, operators and admins of enabled equipment always can.', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Training module settings',
                'verbose_name_plural': 'Training module settings',
            },
        ),
        migrations.CreateModel(
            name='TrainingEquipmentSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('equipment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='training_setting', to='equipment.equipment')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['enabled'], name='training_tr_enabled_eaa458_idx')],
            },
        ),
    ]
