#!/bin/sh
set -e
# Substitute only ACME_EMAIL and TRAEFIK_DOMAIN; Traefik does not expand ${VAR} in the static file.
envsubst '${ACME_EMAIL} ${TRAEFIK_DOMAIN}' < /etc/traefik/traefik.yml.template > /etc/traefik/traefik.yml
exec "$@"
